// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: meridian/forecasting/v1/forecasting.proto

package forecastingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ForecastingService_ComputeForwardCurve_FullMethodName = "/meridian.forecasting.v1.ForecastingService/ComputeForwardCurve"
)

// ForecastingServiceClient is the client API for ForecastingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ForecastingService provides operations for managing and executing forecasting
// strategies that generate forward curves from market data observations.
type ForecastingServiceClient interface {
	// ComputeForwardCurve executes a forecasting strategy to generate a forward curve.
	//
	// The RPC orchestrates:
	//  1. Strategy retrieval and ACTIVE status validation
	//  2. Historical observation fetching from Market Data Service
	//  3. Reference data resolution (if configured)
	//  4. Starlark strategy execution
	//  5. Forecast point publishing to MDS as ESTIMATE quality observations
	//
	// Returns FAILED_PRECONDITION if the strategy is not in ACTIVE status.
	// Returns NOT_FOUND if the strategy does not exist.
	// Returns INTERNAL if the Starlark script fails during execution.
	ComputeForwardCurve(ctx context.Context, in *ComputeForwardCurveRequest, opts ...grpc.CallOption) (*ComputeForwardCurveResponse, error)
}

type forecastingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewForecastingServiceClient(cc grpc.ClientConnInterface) ForecastingServiceClient {
	return &forecastingServiceClient{cc}
}

func (c *forecastingServiceClient) ComputeForwardCurve(ctx context.Context, in *ComputeForwardCurveRequest, opts ...grpc.CallOption) (*ComputeForwardCurveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeForwardCurveResponse)
	err := c.cc.Invoke(ctx, ForecastingService_ComputeForwardCurve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForecastingServiceServer is the server API for ForecastingService service.
// All implementations must embed UnimplementedForecastingServiceServer
// for forward compatibility.
//
// ForecastingService provides operations for managing and executing forecasting
// strategies that generate forward curves from market data observations.
type ForecastingServiceServer interface {
	// ComputeForwardCurve executes a forecasting strategy to generate a forward curve.
	//
	// The RPC orchestrates:
	//  1. Strategy retrieval and ACTIVE status validation
	//  2. Historical observation fetching from Market Data Service
	//  3. Reference data resolution (if configured)
	//  4. Starlark strategy execution
	//  5. Forecast point publishing to MDS as ESTIMATE quality observations
	//
	// Returns FAILED_PRECONDITION if the strategy is not in ACTIVE status.
	// Returns NOT_FOUND if the strategy does not exist.
	// Returns INTERNAL if the Starlark script fails during execution.
	ComputeForwardCurve(context.Context, *ComputeForwardCurveRequest) (*ComputeForwardCurveResponse, error)
	mustEmbedUnimplementedForecastingServiceServer()
}

// UnimplementedForecastingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForecastingServiceServer struct{}

func (UnimplementedForecastingServiceServer) ComputeForwardCurve(context.Context, *ComputeForwardCurveRequest) (*ComputeForwardCurveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComputeForwardCurve not implemented")
}
func (UnimplementedForecastingServiceServer) mustEmbedUnimplementedForecastingServiceServer() {}
func (UnimplementedForecastingServiceServer) testEmbeddedByValue()                            {}

// UnsafeForecastingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForecastingServiceServer will
// result in compilation errors.
type UnsafeForecastingServiceServer interface {
	mustEmbedUnimplementedForecastingServiceServer()
}

func RegisterForecastingServiceServer(s grpc.ServiceRegistrar, srv ForecastingServiceServer) {
	// If the following call pancis, it indicates UnimplementedForecastingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForecastingService_ServiceDesc, srv)
}

func _ForecastingService_ComputeForwardCurve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeForwardCurveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastingServiceServer).ComputeForwardCurve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForecastingService_ComputeForwardCurve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastingServiceServer).ComputeForwardCurve(ctx, req.(*ComputeForwardCurveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForecastingService_ServiceDesc is the grpc.ServiceDesc for ForecastingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForecastingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meridian.forecasting.v1.ForecastingService",
	HandlerType: (*ForecastingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComputeForwardCurve",
			Handler:    _ForecastingService_ComputeForwardCurve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meridian/forecasting/v1/forecasting.proto",
}
