// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: meridian/common/v1/error.proto

package commonv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode defines standardized error codes for Meridian services.
type ErrorCode int32

const (
	// ERROR_CODE_UNSPECIFIED means no specific error code.
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	// General errors (1000-1999)
	// ERROR_CODE_INTERNAL is an internal server error.
	ErrorCode_ERROR_CODE_INTERNAL ErrorCode = 1000
	// ERROR_CODE_INVALID_ARGUMENT means the request contains invalid data.
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT ErrorCode = 1001
	// ERROR_CODE_NOT_FOUND means the requested resource was not found.
	ErrorCode_ERROR_CODE_NOT_FOUND ErrorCode = 1002
	// ERROR_CODE_ALREADY_EXISTS means the resource already exists.
	ErrorCode_ERROR_CODE_ALREADY_EXISTS ErrorCode = 1003
	// ERROR_CODE_PERMISSION_DENIED means the caller lacks permission.
	ErrorCode_ERROR_CODE_PERMISSION_DENIED ErrorCode = 1004
	// ERROR_CODE_UNAUTHENTICATED means the request lacks valid authentication.
	ErrorCode_ERROR_CODE_UNAUTHENTICATED ErrorCode = 1005
	// ERROR_CODE_RESOURCE_EXHAUSTED means quota or rate limit exceeded.
	ErrorCode_ERROR_CODE_RESOURCE_EXHAUSTED ErrorCode = 1006
	// ERROR_CODE_PRECONDITION_FAILED means operation rejected due to system state.
	ErrorCode_ERROR_CODE_PRECONDITION_FAILED ErrorCode = 1007
	// ERROR_CODE_ABORTED means the operation was aborted (typically due to concurrency).
	ErrorCode_ERROR_CODE_ABORTED ErrorCode = 1008
	// ERROR_CODE_OUT_OF_RANGE means operation attempted past valid range.
	ErrorCode_ERROR_CODE_OUT_OF_RANGE ErrorCode = 1009
	// ERROR_CODE_UNIMPLEMENTED means the operation is not implemented.
	ErrorCode_ERROR_CODE_UNIMPLEMENTED ErrorCode = 1010
	// ERROR_CODE_UNAVAILABLE means the service is currently unavailable.
	ErrorCode_ERROR_CODE_UNAVAILABLE ErrorCode = 1011
	// ERROR_CODE_DEADLINE_EXCEEDED means the operation deadline expired.
	ErrorCode_ERROR_CODE_DEADLINE_EXCEEDED ErrorCode = 1012
	// Financial errors (2000-2999)
	// ERROR_CODE_INSUFFICIENT_FUNDS means the account has insufficient balance.
	ErrorCode_ERROR_CODE_INSUFFICIENT_FUNDS ErrorCode = 2000
	// ERROR_CODE_INVALID_CURRENCY means the currency code is not supported.
	ErrorCode_ERROR_CODE_INVALID_CURRENCY ErrorCode = 2001
	// ERROR_CODE_INVALID_AMOUNT means the transaction amount is invalid.
	ErrorCode_ERROR_CODE_INVALID_AMOUNT ErrorCode = 2002
	// ERROR_CODE_DOUBLE_ENTRY_VIOLATION means double-entry accounting rules violated.
	ErrorCode_ERROR_CODE_DOUBLE_ENTRY_VIOLATION ErrorCode = 2003
	// ERROR_CODE_POSTING_FAILED means the ledger posting operation failed.
	ErrorCode_ERROR_CODE_POSTING_FAILED ErrorCode = 2004
	// ERROR_CODE_ACCOUNT_CLOSED means the account is closed.
	ErrorCode_ERROR_CODE_ACCOUNT_CLOSED ErrorCode = 2005
	// ERROR_CODE_ACCOUNT_FROZEN means the account is frozen.
	ErrorCode_ERROR_CODE_ACCOUNT_FROZEN ErrorCode = 2006
	// ERROR_CODE_LIMIT_EXCEEDED means a financial limit was exceeded.
	ErrorCode_ERROR_CODE_LIMIT_EXCEEDED ErrorCode = 2007
	// ERROR_CODE_INVALID_VALUE_DATE means the value date is invalid.
	ErrorCode_ERROR_CODE_INVALID_VALUE_DATE ErrorCode = 2008
	// ERROR_CODE_DUPLICATE_TRANSACTION means duplicate transaction detected.
	ErrorCode_ERROR_CODE_DUPLICATE_TRANSACTION ErrorCode = 2009
	// BIAN-specific errors (3000-3999)
	// ERROR_CODE_CONTROL_RECORD_NOT_FOUND means the BIAN control record was not found.
	ErrorCode_ERROR_CODE_CONTROL_RECORD_NOT_FOUND ErrorCode = 3000
	// ERROR_CODE_BEHAVIOR_QUALIFIER_INVALID means the behavior qualifier is invalid.
	ErrorCode_ERROR_CODE_BEHAVIOR_QUALIFIER_INVALID ErrorCode = 3001
	// ERROR_CODE_SERVICE_DOMAIN_UNAVAILABLE means the BIAN service domain is unavailable.
	ErrorCode_ERROR_CODE_SERVICE_DOMAIN_UNAVAILABLE ErrorCode = 3002
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:    "ERROR_CODE_UNSPECIFIED",
		1000: "ERROR_CODE_INTERNAL",
		1001: "ERROR_CODE_INVALID_ARGUMENT",
		1002: "ERROR_CODE_NOT_FOUND",
		1003: "ERROR_CODE_ALREADY_EXISTS",
		1004: "ERROR_CODE_PERMISSION_DENIED",
		1005: "ERROR_CODE_UNAUTHENTICATED",
		1006: "ERROR_CODE_RESOURCE_EXHAUSTED",
		1007: "ERROR_CODE_PRECONDITION_FAILED",
		1008: "ERROR_CODE_ABORTED",
		1009: "ERROR_CODE_OUT_OF_RANGE",
		1010: "ERROR_CODE_UNIMPLEMENTED",
		1011: "ERROR_CODE_UNAVAILABLE",
		1012: "ERROR_CODE_DEADLINE_EXCEEDED",
		2000: "ERROR_CODE_INSUFFICIENT_FUNDS",
		2001: "ERROR_CODE_INVALID_CURRENCY",
		2002: "ERROR_CODE_INVALID_AMOUNT",
		2003: "ERROR_CODE_DOUBLE_ENTRY_VIOLATION",
		2004: "ERROR_CODE_POSTING_FAILED",
		2005: "ERROR_CODE_ACCOUNT_CLOSED",
		2006: "ERROR_CODE_ACCOUNT_FROZEN",
		2007: "ERROR_CODE_LIMIT_EXCEEDED",
		2008: "ERROR_CODE_INVALID_VALUE_DATE",
		2009: "ERROR_CODE_DUPLICATE_TRANSACTION",
		3000: "ERROR_CODE_CONTROL_RECORD_NOT_FOUND",
		3001: "ERROR_CODE_BEHAVIOR_QUALIFIER_INVALID",
		3002: "ERROR_CODE_SERVICE_DOMAIN_UNAVAILABLE",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":                0,
		"ERROR_CODE_INTERNAL":                   1000,
		"ERROR_CODE_INVALID_ARGUMENT":           1001,
		"ERROR_CODE_NOT_FOUND":                  1002,
		"ERROR_CODE_ALREADY_EXISTS":             1003,
		"ERROR_CODE_PERMISSION_DENIED":          1004,
		"ERROR_CODE_UNAUTHENTICATED":            1005,
		"ERROR_CODE_RESOURCE_EXHAUSTED":         1006,
		"ERROR_CODE_PRECONDITION_FAILED":        1007,
		"ERROR_CODE_ABORTED":                    1008,
		"ERROR_CODE_OUT_OF_RANGE":               1009,
		"ERROR_CODE_UNIMPLEMENTED":              1010,
		"ERROR_CODE_UNAVAILABLE":                1011,
		"ERROR_CODE_DEADLINE_EXCEEDED":          1012,
		"ERROR_CODE_INSUFFICIENT_FUNDS":         2000,
		"ERROR_CODE_INVALID_CURRENCY":           2001,
		"ERROR_CODE_INVALID_AMOUNT":             2002,
		"ERROR_CODE_DOUBLE_ENTRY_VIOLATION":     2003,
		"ERROR_CODE_POSTING_FAILED":             2004,
		"ERROR_CODE_ACCOUNT_CLOSED":             2005,
		"ERROR_CODE_ACCOUNT_FROZEN":             2006,
		"ERROR_CODE_LIMIT_EXCEEDED":             2007,
		"ERROR_CODE_INVALID_VALUE_DATE":         2008,
		"ERROR_CODE_DUPLICATE_TRANSACTION":      2009,
		"ERROR_CODE_CONTROL_RECORD_NOT_FOUND":   3000,
		"ERROR_CODE_BEHAVIOR_QUALIFIER_INVALID": 3001,
		"ERROR_CODE_SERVICE_DOMAIN_UNAVAILABLE": 3002,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_meridian_common_v1_error_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_meridian_common_v1_error_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_meridian_common_v1_error_proto_rawDescGZIP(), []int{0}
}

// Error represents a structured error response.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code is the error code.
	Code ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=meridian.common.v1.ErrorCode" json:"code,omitempty"`
	// message is a human-readable error message.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// details contains additional error context (optional).
	Details []*anypb.Any `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	// field_violations contains field-specific validation errors (optional).
	FieldViolations []*FieldViolation `protobuf:"bytes,4,rep,name=field_violations,json=fieldViolations,proto3" json:"field_violations,omitempty"`
	// trace_id is a correlation ID for tracing (optional).
	TraceId string `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// retry_info provides guidance on retry behavior (optional).
	RetryInfo     *RetryInfo `protobuf:"bytes,6,opt,name=retry_info,json=retryInfo,proto3" json:"retry_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_meridian_common_v1_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_common_v1_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_meridian_common_v1_error_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() []*anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Error) GetFieldViolations() []*FieldViolation {
	if x != nil {
		return x.FieldViolations
	}
	return nil
}

func (x *Error) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Error) GetRetryInfo() *RetryInfo {
	if x != nil {
		return x.RetryInfo
	}
	return nil
}

// FieldViolation describes a single field validation error.
type FieldViolation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// field is the field path (e.g., "amount.currency_code").
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// description explains why the field is invalid.
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldViolation) Reset() {
	*x = FieldViolation{}
	mi := &file_meridian_common_v1_error_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldViolation) ProtoMessage() {}

func (x *FieldViolation) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_common_v1_error_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldViolation.ProtoReflect.Descriptor instead.
func (*FieldViolation) Descriptor() ([]byte, []int) {
	return file_meridian_common_v1_error_proto_rawDescGZIP(), []int{1}
}

func (x *FieldViolation) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldViolation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// RetryInfo provides guidance on when and how to retry a failed request.
type RetryInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// retryable indicates whether the operation can be retried.
	Retryable bool `protobuf:"varint,1,opt,name=retryable,proto3" json:"retryable,omitempty"`
	// retry_delay_seconds suggests how long to wait before retrying.
	RetryDelaySeconds int32 `protobuf:"varint,2,opt,name=retry_delay_seconds,json=retryDelaySeconds,proto3" json:"retry_delay_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RetryInfo) Reset() {
	*x = RetryInfo{}
	mi := &file_meridian_common_v1_error_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryInfo) ProtoMessage() {}

func (x *RetryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_common_v1_error_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryInfo.ProtoReflect.Descriptor instead.
func (*RetryInfo) Descriptor() ([]byte, []int) {
	return file_meridian_common_v1_error_proto_rawDescGZIP(), []int{2}
}

func (x *RetryInfo) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *RetryInfo) GetRetryDelaySeconds() int32 {
	if x != nil {
		return x.RetryDelaySeconds
	}
	return 0
}

var File_meridian_common_v1_error_proto protoreflect.FileDescriptor

const file_meridian_common_v1_error_proto_rawDesc = "" +
	"\n" +
	"\x1emeridian/common/v1/error.proto\x12\x12meridian.common.v1\x1a\x1bbuf/validate/validate.proto\x1a\x19google/protobuf/any.proto\"\xbd\x02\n" +
	"\x05Error\x129\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1d.meridian.common.v1.ErrorCodeB\x06\xbaH\x03\xc8\x01\x01R\x04code\x12!\n" +
	"\amessage\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\amessage\x12.\n" +
	"\adetails\x18\x03 \x03(\v2\x14.google.protobuf.AnyR\adetails\x12M\n" +
	"\x10field_violations\x18\x04 \x03(\v2\".meridian.common.v1.FieldViolationR\x0ffieldViolations\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12<\n" +
	"\n" +
	"retry_info\x18\x06 \x01(\v2\x1d.meridian.common.v1.RetryInfoR\tretryInfo\"Z\n" +
	"\x0eFieldViolation\x12\x1d\n" +
	"\x05field\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05field\x12)\n" +
	"\vdescription\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vdescription\"e\n" +
	"\tRetryInfo\x12\x1c\n" +
	"\tretryable\x18\x01 \x01(\bR\tretryable\x12:\n" +
	"\x13retry_delay_seconds\x18\x02 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\x90\x1c(\x00R\x11retryDelaySeconds*\x9c\a\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x13ERROR_CODE_INTERNAL\x10\xe8\a\x12 \n" +
	"\x1bERROR_CODE_INVALID_ARGUMENT\x10\xe9\a\x12\x19\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\xea\a\x12\x1e\n" +
	"\x19ERROR_CODE_ALREADY_EXISTS\x10\xeb\a\x12!\n" +
	"\x1cERROR_CODE_PERMISSION_DENIED\x10\xec\a\x12\x1f\n" +
	"\x1aERROR_CODE_UNAUTHENTICATED\x10\xed\a\x12\"\n" +
	"\x1dERROR_CODE_RESOURCE_EXHAUSTED\x10\xee\a\x12#\n" +
	"\x1eERROR_CODE_PRECONDITION_FAILED\x10\xef\a\x12\x17\n" +
	"\x12ERROR_CODE_ABORTED\x10\xf0\a\x12\x1c\n" +
	"\x17ERROR_CODE_OUT_OF_RANGE\x10\xf1\a\x12\x1d\n" +
	"\x18ERROR_CODE_UNIMPLEMENTED\x10\xf2\a\x12\x1b\n" +
	"\x16ERROR_CODE_UNAVAILABLE\x10\xf3\a\x12!\n" +
	"\x1cERROR_CODE_DEADLINE_EXCEEDED\x10\xf4\a\x12\"\n" +
	"\x1dERROR_CODE_INSUFFICIENT_FUNDS\x10\xd0\x0f\x12 \n" +
	"\x1bERROR_CODE_INVALID_CURRENCY\x10\xd1\x0f\x12\x1e\n" +
	"\x19ERROR_CODE_INVALID_AMOUNT\x10\xd2\x0f\x12&\n" +
	"!ERROR_CODE_DOUBLE_ENTRY_VIOLATION\x10\xd3\x0f\x12\x1e\n" +
	"\x19ERROR_CODE_POSTING_FAILED\x10\xd4\x0f\x12\x1e\n" +
	"\x19ERROR_CODE_ACCOUNT_CLOSED\x10\xd5\x0f\x12\x1e\n" +
	"\x19ERROR_CODE_ACCOUNT_FROZEN\x10\xd6\x0f\x12\x1e\n" +
	"\x19ERROR_CODE_LIMIT_EXCEEDED\x10\xd7\x0f\x12\"\n" +
	"\x1dERROR_CODE_INVALID_VALUE_DATE\x10\xd8\x0f\x12%\n" +
	" ERROR_CODE_DUPLICATE_TRANSACTION\x10\xd9\x0f\x12(\n" +
	"#ERROR_CODE_CONTROL_RECORD_NOT_FOUND\x10\xb8\x17\x12*\n" +
	"%ERROR_CODE_BEHAVIOR_QUALIFIER_INVALID\x10\xb9\x17\x12*\n" +
	"%ERROR_CODE_SERVICE_DOMAIN_UNAVAILABLE\x10\xba\x17BDZBgithub.com/meridianhub/meridian/api/proto/meridian/common/v1;commonv1b\x06proto3"

var (
	file_meridian_common_v1_error_proto_rawDescOnce sync.Once
	file_meridian_common_v1_error_proto_rawDescData []byte
)

func file_meridian_common_v1_error_proto_rawDescGZIP() []byte {
	file_meridian_common_v1_error_proto_rawDescOnce.Do(func() {
		file_meridian_common_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meridian_common_v1_error_proto_rawDesc), len(file_meridian_common_v1_error_proto_rawDesc)))
	})
	return file_meridian_common_v1_error_proto_rawDescData
}

var file_meridian_common_v1_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meridian_common_v1_error_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_meridian_common_v1_error_proto_goTypes = []any{
	(ErrorCode)(0),         // 0: meridian.common.v1.ErrorCode
	(*Error)(nil),          // 1: meridian.common.v1.Error
	(*FieldViolation)(nil), // 2: meridian.common.v1.FieldViolation
	(*RetryInfo)(nil),      // 3: meridian.common.v1.RetryInfo
	(*anypb.Any)(nil),      // 4: google.protobuf.Any
}
var file_meridian_common_v1_error_proto_depIdxs = []int32{
	0, // 0: meridian.common.v1.Error.code:type_name -> meridian.common.v1.ErrorCode
	4, // 1: meridian.common.v1.Error.details:type_name -> google.protobuf.Any
	2, // 2: meridian.common.v1.Error.field_violations:type_name -> meridian.common.v1.FieldViolation
	3, // 3: meridian.common.v1.Error.retry_info:type_name -> meridian.common.v1.RetryInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_meridian_common_v1_error_proto_init() }
func file_meridian_common_v1_error_proto_init() {
	if File_meridian_common_v1_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meridian_common_v1_error_proto_rawDesc), len(file_meridian_common_v1_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meridian_common_v1_error_proto_goTypes,
		DependencyIndexes: file_meridian_common_v1_error_proto_depIdxs,
		EnumInfos:         file_meridian_common_v1_error_proto_enumTypes,
		MessageInfos:      file_meridian_common_v1_error_proto_msgTypes,
	}.Build()
	File_meridian_common_v1_error_proto = out.File
	file_meridian_common_v1_error_proto_goTypes = nil
	file_meridian_common_v1_error_proto_depIdxs = nil
}
