// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: meridian/common/v1/health.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServingStatus describes the health status of a service.
type CheckResponse_ServingStatus int32

const (
	// SERVING_STATUS_UNSPECIFIED means the status is unknown.
	CheckResponse_SERVING_STATUS_UNSPECIFIED CheckResponse_ServingStatus = 0
	// SERVING_STATUS_SERVING means the service is healthy and serving requests.
	CheckResponse_SERVING_STATUS_SERVING CheckResponse_ServingStatus = 1
	// SERVING_STATUS_NOT_SERVING means the service is not serving requests.
	CheckResponse_SERVING_STATUS_NOT_SERVING CheckResponse_ServingStatus = 2
	// SERVING_STATUS_UNKNOWN means the service health status cannot be determined.
	CheckResponse_SERVING_STATUS_UNKNOWN CheckResponse_ServingStatus = 3
)

// Enum value maps for CheckResponse_ServingStatus.
var (
	CheckResponse_ServingStatus_name = map[int32]string{
		0: "SERVING_STATUS_UNSPECIFIED",
		1: "SERVING_STATUS_SERVING",
		2: "SERVING_STATUS_NOT_SERVING",
		3: "SERVING_STATUS_UNKNOWN",
	}
	CheckResponse_ServingStatus_value = map[string]int32{
		"SERVING_STATUS_UNSPECIFIED": 0,
		"SERVING_STATUS_SERVING":     1,
		"SERVING_STATUS_NOT_SERVING": 2,
		"SERVING_STATUS_UNKNOWN":     3,
	}
)

func (x CheckResponse_ServingStatus) Enum() *CheckResponse_ServingStatus {
	p := new(CheckResponse_ServingStatus)
	*p = x
	return p
}

func (x CheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_meridian_common_v1_health_proto_enumTypes[0].Descriptor()
}

func (CheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_meridian_common_v1_health_proto_enumTypes[0]
}

func (x CheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckResponse_ServingStatus.Descriptor instead.
func (CheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_meridian_common_v1_health_proto_rawDescGZIP(), []int{1, 0}
}

// CheckRequest is the request for a health check.
type CheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// service is the name of the service to check (optional).
	Service       string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_meridian_common_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_common_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_meridian_common_v1_health_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// CheckResponse is the response for a health check.
type CheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is the health status of the service.
	Status        CheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=meridian.common.v1.CheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_meridian_common_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_common_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_meridian_common_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetStatus() CheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return CheckResponse_SERVING_STATUS_UNSPECIFIED
}

var File_meridian_common_v1_health_proto protoreflect.FileDescriptor

const file_meridian_common_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x1fmeridian/common/v1/health.proto\x12\x12meridian.common.v1\"(\n" +
	"\fCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xe2\x01\n" +
	"\rCheckResponse\x12G\n" +
	"\x06status\x18\x01 \x01(\x0e2/.meridian.common.v1.CheckResponse.ServingStatusR\x06status\"\x87\x01\n" +
	"\rServingStatus\x12\x1e\n" +
	"\x1aSERVING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SERVING_STATUS_SERVING\x10\x01\x12\x1e\n" +
	"\x1aSERVING_STATUS_NOT_SERVING\x10\x02\x12\x1a\n" +
	"\x16SERVING_STATUS_UNKNOWN\x10\x032]\n" +
	"\rHealthService\x12L\n" +
	"\x05Check\x12 .meridian.common.v1.CheckRequest\x1a!.meridian.common.v1.CheckResponseBDZBgithub.com/bjcoombs/meridian/api/proto/meridian/common/v1;commonv1b\x06proto3"

var (
	file_meridian_common_v1_health_proto_rawDescOnce sync.Once
	file_meridian_common_v1_health_proto_rawDescData []byte
)

func file_meridian_common_v1_health_proto_rawDescGZIP() []byte {
	file_meridian_common_v1_health_proto_rawDescOnce.Do(func() {
		file_meridian_common_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meridian_common_v1_health_proto_rawDesc), len(file_meridian_common_v1_health_proto_rawDesc)))
	})
	return file_meridian_common_v1_health_proto_rawDescData
}

var file_meridian_common_v1_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meridian_common_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meridian_common_v1_health_proto_goTypes = []any{
	(CheckResponse_ServingStatus)(0), // 0: meridian.common.v1.CheckResponse.ServingStatus
	(*CheckRequest)(nil),             // 1: meridian.common.v1.CheckRequest
	(*CheckResponse)(nil),            // 2: meridian.common.v1.CheckResponse
}
var file_meridian_common_v1_health_proto_depIdxs = []int32{
	0, // 0: meridian.common.v1.CheckResponse.status:type_name -> meridian.common.v1.CheckResponse.ServingStatus
	1, // 1: meridian.common.v1.HealthService.Check:input_type -> meridian.common.v1.CheckRequest
	2, // 2: meridian.common.v1.HealthService.Check:output_type -> meridian.common.v1.CheckResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_meridian_common_v1_health_proto_init() }
func file_meridian_common_v1_health_proto_init() {
	if File_meridian_common_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meridian_common_v1_health_proto_rawDesc), len(file_meridian_common_v1_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meridian_common_v1_health_proto_goTypes,
		DependencyIndexes: file_meridian_common_v1_health_proto_depIdxs,
		EnumInfos:         file_meridian_common_v1_health_proto_enumTypes,
		MessageInfos:      file_meridian_common_v1_health_proto_msgTypes,
	}.Build()
	File_meridian_common_v1_health_proto = out.File
	file_meridian_common_v1_health_proto_goTypes = nil
	file_meridian_common_v1_health_proto_depIdxs = nil
}
