// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: meridian/position_keeping/v1/position_keeping.proto

package positionkeepingv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/meridianhub/meridian/api/proto/meridian/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransactionLogEntry represents a single entry in the financial position log.
type TransactionLogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entry_id is the unique identifier for this log entry.
	EntryId string `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	// transaction_id is the identifier of the related transaction (UUID format).
	TransactionId string `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// account_id is the account involved in this transaction.
	AccountId string `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// amount is the monetary amount of this transaction.
	Amount *v1.MoneyAmount `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// direction indicates whether this is a debit or credit posting.
	Direction v1.PostingDirection `protobuf:"varint,5,opt,name=direction,proto3,enum=meridian.common.v1.PostingDirection" json:"direction,omitempty"`
	// timestamp is when this transaction occurred.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// description provides additional context for this entry.
	Description string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	// reference is an external reference number (e.g., invoice number, payment reference).
	Reference     string `protobuf:"bytes,8,opt,name=reference,proto3" json:"reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionLogEntry) Reset() {
	*x = TransactionLogEntry{}
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionLogEntry) ProtoMessage() {}

func (x *TransactionLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionLogEntry.ProtoReflect.Descriptor instead.
func (*TransactionLogEntry) Descriptor() ([]byte, []int) {
	return file_meridian_position_keeping_v1_position_keeping_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionLogEntry) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *TransactionLogEntry) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionLogEntry) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *TransactionLogEntry) GetAmount() *v1.MoneyAmount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *TransactionLogEntry) GetDirection() v1.PostingDirection {
	if x != nil {
		return x.Direction
	}
	return v1.PostingDirection(0)
}

func (x *TransactionLogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TransactionLogEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransactionLogEntry) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

// TransactionLineage captures the relationship between transactions.
type TransactionLineage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// transaction_id is the current transaction identifier (UUID format).
	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// parent_transaction_id is the identifier of the parent transaction (optional, UUID format when present).
	ParentTransactionId string `protobuf:"bytes,2,opt,name=parent_transaction_id,json=parentTransactionId,proto3" json:"parent_transaction_id,omitempty"`
	// child_transaction_ids are identifiers of any child transactions (UUID format).
	ChildTransactionIds []string `protobuf:"bytes,3,rep,name=child_transaction_ids,json=childTransactionIds,proto3" json:"child_transaction_ids,omitempty"`
	// related_transaction_ids are identifiers of related transactions (UUID format, e.g., reversals, adjustments).
	RelatedTransactionIds []string `protobuf:"bytes,4,rep,name=related_transaction_ids,json=relatedTransactionIds,proto3" json:"related_transaction_ids,omitempty"`
	// transaction_type describes the type of transaction (e.g., "payment", "reversal", "adjustment").
	TransactionType string `protobuf:"bytes,5,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	// created_at is when this lineage record was created.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionLineage) Reset() {
	*x = TransactionLineage{}
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionLineage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionLineage) ProtoMessage() {}

func (x *TransactionLineage) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionLineage.ProtoReflect.Descriptor instead.
func (*TransactionLineage) Descriptor() ([]byte, []int) {
	return file_meridian_position_keeping_v1_position_keeping_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionLineage) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionLineage) GetParentTransactionId() string {
	if x != nil {
		return x.ParentTransactionId
	}
	return ""
}

func (x *TransactionLineage) GetChildTransactionIds() []string {
	if x != nil {
		return x.ChildTransactionIds
	}
	return nil
}

func (x *TransactionLineage) GetRelatedTransactionIds() []string {
	if x != nil {
		return x.RelatedTransactionIds
	}
	return nil
}

func (x *TransactionLineage) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *TransactionLineage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// AuditTrailEntry captures audit information for compliance.
type AuditTrailEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// audit_id is the unique identifier for this audit entry.
	AuditId string `protobuf:"bytes,1,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	// timestamp is when this audit event occurred.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// user_id is the identifier of the user who performed the action.
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// action describes what action was performed (e.g., "created", "updated", "approved").
	Action string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	// details provides additional context about the action.
	Details string `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	// ip_address is the IP address from which the action was performed (IPv4 or IPv6).
	IpAddress string `protobuf:"bytes,6,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// system_context provides additional system-level context (e.g., service name, version).
	SystemContext map[string]string `protobuf:"bytes,7,rep,name=system_context,json=systemContext,proto3" json:"system_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditTrailEntry) Reset() {
	*x = AuditTrailEntry{}
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditTrailEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditTrailEntry) ProtoMessage() {}

func (x *AuditTrailEntry) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditTrailEntry.ProtoReflect.Descriptor instead.
func (*AuditTrailEntry) Descriptor() ([]byte, []int) {
	return file_meridian_position_keeping_v1_position_keeping_proto_rawDescGZIP(), []int{2}
}

func (x *AuditTrailEntry) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

func (x *AuditTrailEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AuditTrailEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuditTrailEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditTrailEntry) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *AuditTrailEntry) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AuditTrailEntry) GetSystemContext() map[string]string {
	if x != nil {
		return x.SystemContext
	}
	return nil
}

// StatusTracking captures the lifecycle status of the financial position log.
type StatusTracking struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// current_status is the current status of the transaction.
	CurrentStatus v1.TransactionStatus `protobuf:"varint,1,opt,name=current_status,json=currentStatus,proto3,enum=meridian.common.v1.TransactionStatus" json:"current_status,omitempty"`
	// previous_status is the previous status before the current one.
	PreviousStatus v1.TransactionStatus `protobuf:"varint,2,opt,name=previous_status,json=previousStatus,proto3,enum=meridian.common.v1.TransactionStatus" json:"previous_status,omitempty"`
	// status_updated_at is when the status was last updated.
	StatusUpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=status_updated_at,json=statusUpdatedAt,proto3" json:"status_updated_at,omitempty"`
	// status_reason provides context for status changes.
	StatusReason string `protobuf:"bytes,4,opt,name=status_reason,json=statusReason,proto3" json:"status_reason,omitempty"`
	// failure_reason provides details if the transaction failed.
	FailureReason string `protobuf:"bytes,5,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusTracking) Reset() {
	*x = StatusTracking{}
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusTracking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusTracking) ProtoMessage() {}

func (x *StatusTracking) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusTracking.ProtoReflect.Descriptor instead.
func (*StatusTracking) Descriptor() ([]byte, []int) {
	return file_meridian_position_keeping_v1_position_keeping_proto_rawDescGZIP(), []int{3}
}

func (x *StatusTracking) GetCurrentStatus() v1.TransactionStatus {
	if x != nil {
		return x.CurrentStatus
	}
	return v1.TransactionStatus(0)
}

func (x *StatusTracking) GetPreviousStatus() v1.TransactionStatus {
	if x != nil {
		return x.PreviousStatus
	}
	return v1.TransactionStatus(0)
}

func (x *StatusTracking) GetStatusUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StatusUpdatedAt
	}
	return nil
}

func (x *StatusTracking) GetStatusReason() string {
	if x != nil {
		return x.StatusReason
	}
	return ""
}

func (x *StatusTracking) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

// FinancialPositionLog represents a comprehensive log of financial position for an account or transaction set.
type FinancialPositionLog struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// log_id is the unique identifier for this financial position log.
	LogId string `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	// account_id is the account this log pertains to.
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// transaction_log_entries contains all transaction entries for this position.
	TransactionLogEntries []*TransactionLogEntry `protobuf:"bytes,3,rep,name=transaction_log_entries,json=transactionLogEntries,proto3" json:"transaction_log_entries,omitempty"`
	// transaction_lineage captures the relationship between transactions.
	TransactionLineage *TransactionLineage `protobuf:"bytes,4,opt,name=transaction_lineage,json=transactionLineage,proto3" json:"transaction_lineage,omitempty"`
	// audit_trail contains the complete audit history.
	AuditTrail []*AuditTrailEntry `protobuf:"bytes,5,rep,name=audit_trail,json=auditTrail,proto3" json:"audit_trail,omitempty"`
	// status_tracking contains the current and historical status information.
	StatusTracking *StatusTracking `protobuf:"bytes,6,opt,name=status_tracking,json=statusTracking,proto3" json:"status_tracking,omitempty"`
	// created_at is when this log was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at is when this log was last updated.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// version is used for optimistic concurrency control.
	Version       int64 `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinancialPositionLog) Reset() {
	*x = FinancialPositionLog{}
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinancialPositionLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancialPositionLog) ProtoMessage() {}

func (x *FinancialPositionLog) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancialPositionLog.ProtoReflect.Descriptor instead.
func (*FinancialPositionLog) Descriptor() ([]byte, []int) {
	return file_meridian_position_keeping_v1_position_keeping_proto_rawDescGZIP(), []int{4}
}

func (x *FinancialPositionLog) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *FinancialPositionLog) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *FinancialPositionLog) GetTransactionLogEntries() []*TransactionLogEntry {
	if x != nil {
		return x.TransactionLogEntries
	}
	return nil
}

func (x *FinancialPositionLog) GetTransactionLineage() *TransactionLineage {
	if x != nil {
		return x.TransactionLineage
	}
	return nil
}

func (x *FinancialPositionLog) GetAuditTrail() []*AuditTrailEntry {
	if x != nil {
		return x.AuditTrail
	}
	return nil
}

func (x *FinancialPositionLog) GetStatusTracking() *StatusTracking {
	if x != nil {
		return x.StatusTracking
	}
	return nil
}

func (x *FinancialPositionLog) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FinancialPositionLog) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *FinancialPositionLog) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// InitiateFinancialPositionLogRequest initiates a new financial position log.
type InitiateFinancialPositionLogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// account_id is the account for which to create the log.
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// initial_entry is the first transaction entry (optional).
	InitialEntry *TransactionLogEntry `protobuf:"bytes,2,opt,name=initial_entry,json=initialEntry,proto3" json:"initial_entry,omitempty"`
	// transaction_lineage captures initial lineage information.
	TransactionLineage *TransactionLineage `protobuf:"bytes,3,opt,name=transaction_lineage,json=transactionLineage,proto3" json:"transaction_lineage,omitempty"`
	// idempotency_key ensures exactly-once processing.
	IdempotencyKey *v1.IdempotencyKey `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitiateFinancialPositionLogRequest) Reset() {
	*x = InitiateFinancialPositionLogRequest{}
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateFinancialPositionLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateFinancialPositionLogRequest) ProtoMessage() {}

func (x *InitiateFinancialPositionLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateFinancialPositionLogRequest.ProtoReflect.Descriptor instead.
func (*InitiateFinancialPositionLogRequest) Descriptor() ([]byte, []int) {
	return file_meridian_position_keeping_v1_position_keeping_proto_rawDescGZIP(), []int{5}
}

func (x *InitiateFinancialPositionLogRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *InitiateFinancialPositionLogRequest) GetInitialEntry() *TransactionLogEntry {
	if x != nil {
		return x.InitialEntry
	}
	return nil
}

func (x *InitiateFinancialPositionLogRequest) GetTransactionLineage() *TransactionLineage {
	if x != nil {
		return x.TransactionLineage
	}
	return nil
}

func (x *InitiateFinancialPositionLogRequest) GetIdempotencyKey() *v1.IdempotencyKey {
	if x != nil {
		return x.IdempotencyKey
	}
	return nil
}

// InitiateFinancialPositionLogResponse returns the created log.
type InitiateFinancialPositionLogResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// log is the created financial position log (always present on success).
	Log           *FinancialPositionLog `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateFinancialPositionLogResponse) Reset() {
	*x = InitiateFinancialPositionLogResponse{}
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateFinancialPositionLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateFinancialPositionLogResponse) ProtoMessage() {}

func (x *InitiateFinancialPositionLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateFinancialPositionLogResponse.ProtoReflect.Descriptor instead.
func (*InitiateFinancialPositionLogResponse) Descriptor() ([]byte, []int) {
	return file_meridian_position_keeping_v1_position_keeping_proto_rawDescGZIP(), []int{6}
}

func (x *InitiateFinancialPositionLogResponse) GetLog() *FinancialPositionLog {
	if x != nil {
		return x.Log
	}
	return nil
}

// UpdateFinancialPositionLogRequest updates an existing financial position log.
type UpdateFinancialPositionLogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// log_id is the identifier of the log to update.
	LogId string `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	// new_entry is a new transaction entry to add (optional).
	NewEntry *TransactionLogEntry `protobuf:"bytes,2,opt,name=new_entry,json=newEntry,proto3" json:"new_entry,omitempty"`
	// status_update is a status change to apply (optional).
	StatusUpdate *StatusTracking `protobuf:"bytes,3,opt,name=status_update,json=statusUpdate,proto3" json:"status_update,omitempty"`
	// audit_entry is an audit trail entry to add.
	AuditEntry *AuditTrailEntry `protobuf:"bytes,4,opt,name=audit_entry,json=auditEntry,proto3" json:"audit_entry,omitempty"`
	// version is used for optimistic concurrency control.
	Version int64 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	// idempotency_key ensures exactly-once processing.
	IdempotencyKey *v1.IdempotencyKey `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateFinancialPositionLogRequest) Reset() {
	*x = UpdateFinancialPositionLogRequest{}
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFinancialPositionLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFinancialPositionLogRequest) ProtoMessage() {}

func (x *UpdateFinancialPositionLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFinancialPositionLogRequest.ProtoReflect.Descriptor instead.
func (*UpdateFinancialPositionLogRequest) Descriptor() ([]byte, []int) {
	return file_meridian_position_keeping_v1_position_keeping_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateFinancialPositionLogRequest) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *UpdateFinancialPositionLogRequest) GetNewEntry() *TransactionLogEntry {
	if x != nil {
		return x.NewEntry
	}
	return nil
}

func (x *UpdateFinancialPositionLogRequest) GetStatusUpdate() *StatusTracking {
	if x != nil {
		return x.StatusUpdate
	}
	return nil
}

func (x *UpdateFinancialPositionLogRequest) GetAuditEntry() *AuditTrailEntry {
	if x != nil {
		return x.AuditEntry
	}
	return nil
}

func (x *UpdateFinancialPositionLogRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UpdateFinancialPositionLogRequest) GetIdempotencyKey() *v1.IdempotencyKey {
	if x != nil {
		return x.IdempotencyKey
	}
	return nil
}

// UpdateFinancialPositionLogResponse returns the updated log.
type UpdateFinancialPositionLogResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// log is the updated financial position log (always present on success).
	Log           *FinancialPositionLog `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFinancialPositionLogResponse) Reset() {
	*x = UpdateFinancialPositionLogResponse{}
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFinancialPositionLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFinancialPositionLogResponse) ProtoMessage() {}

func (x *UpdateFinancialPositionLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFinancialPositionLogResponse.ProtoReflect.Descriptor instead.
func (*UpdateFinancialPositionLogResponse) Descriptor() ([]byte, []int) {
	return file_meridian_position_keeping_v1_position_keeping_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateFinancialPositionLogResponse) GetLog() *FinancialPositionLog {
	if x != nil {
		return x.Log
	}
	return nil
}

// RetrieveFinancialPositionLogRequest retrieves a financial position log.
type RetrieveFinancialPositionLogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// log_id is the identifier of the log to retrieve.
	LogId         string `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveFinancialPositionLogRequest) Reset() {
	*x = RetrieveFinancialPositionLogRequest{}
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveFinancialPositionLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveFinancialPositionLogRequest) ProtoMessage() {}

func (x *RetrieveFinancialPositionLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveFinancialPositionLogRequest.ProtoReflect.Descriptor instead.
func (*RetrieveFinancialPositionLogRequest) Descriptor() ([]byte, []int) {
	return file_meridian_position_keeping_v1_position_keeping_proto_rawDescGZIP(), []int{9}
}

func (x *RetrieveFinancialPositionLogRequest) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

// RetrieveFinancialPositionLogResponse returns the requested log.
type RetrieveFinancialPositionLogResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// log is the requested financial position log (always present on success).
	Log           *FinancialPositionLog `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveFinancialPositionLogResponse) Reset() {
	*x = RetrieveFinancialPositionLogResponse{}
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveFinancialPositionLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveFinancialPositionLogResponse) ProtoMessage() {}

func (x *RetrieveFinancialPositionLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveFinancialPositionLogResponse.ProtoReflect.Descriptor instead.
func (*RetrieveFinancialPositionLogResponse) Descriptor() ([]byte, []int) {
	return file_meridian_position_keeping_v1_position_keeping_proto_rawDescGZIP(), []int{10}
}

func (x *RetrieveFinancialPositionLogResponse) GetLog() *FinancialPositionLog {
	if x != nil {
		return x.Log
	}
	return nil
}

// BulkImportTransactionsRequest imports multiple transactions at once.
type BulkImportTransactionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// log_id is the identifier of the log to import transactions into.
	LogId string `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	// entries are the transaction entries to import.
	Entries []*TransactionLogEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	// audit_entry is an audit trail entry for this bulk import (required for compliance).
	AuditEntry *AuditTrailEntry `protobuf:"bytes,3,opt,name=audit_entry,json=auditEntry,proto3" json:"audit_entry,omitempty"`
	// version is used for optimistic concurrency control.
	Version       int64 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkImportTransactionsRequest) Reset() {
	*x = BulkImportTransactionsRequest{}
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkImportTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkImportTransactionsRequest) ProtoMessage() {}

func (x *BulkImportTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkImportTransactionsRequest.ProtoReflect.Descriptor instead.
func (*BulkImportTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_meridian_position_keeping_v1_position_keeping_proto_rawDescGZIP(), []int{11}
}

func (x *BulkImportTransactionsRequest) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *BulkImportTransactionsRequest) GetEntries() []*TransactionLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *BulkImportTransactionsRequest) GetAuditEntry() *AuditTrailEntry {
	if x != nil {
		return x.AuditEntry
	}
	return nil
}

func (x *BulkImportTransactionsRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// BulkImportTransactionsResponse returns the result of the bulk import.
type BulkImportTransactionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// log is the updated financial position log after import (always present on success).
	Log *FinancialPositionLog `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	// imported_count is the number of transactions successfully imported.
	ImportedCount int32 `protobuf:"varint,2,opt,name=imported_count,json=importedCount,proto3" json:"imported_count,omitempty"`
	// failed_count is the number of transactions that failed to import.
	FailedCount int32 `protobuf:"varint,3,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	// failure_details provides details about any failures.
	FailureDetails []string `protobuf:"bytes,4,rep,name=failure_details,json=failureDetails,proto3" json:"failure_details,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BulkImportTransactionsResponse) Reset() {
	*x = BulkImportTransactionsResponse{}
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkImportTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkImportTransactionsResponse) ProtoMessage() {}

func (x *BulkImportTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkImportTransactionsResponse.ProtoReflect.Descriptor instead.
func (*BulkImportTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_meridian_position_keeping_v1_position_keeping_proto_rawDescGZIP(), []int{12}
}

func (x *BulkImportTransactionsResponse) GetLog() *FinancialPositionLog {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *BulkImportTransactionsResponse) GetImportedCount() int32 {
	if x != nil {
		return x.ImportedCount
	}
	return 0
}

func (x *BulkImportTransactionsResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *BulkImportTransactionsResponse) GetFailureDetails() []string {
	if x != nil {
		return x.FailureDetails
	}
	return nil
}

// ListFinancialPositionLogsRequest lists financial position logs with filtering.
type ListFinancialPositionLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// account_id filters logs by account (optional).
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// status filters logs by current status (optional).
	Status v1.TransactionStatus `protobuf:"varint,2,opt,name=status,proto3,enum=meridian.common.v1.TransactionStatus" json:"status,omitempty"`
	// date_range filters logs by creation date (optional).
	DateRange *v1.DateRange `protobuf:"bytes,3,opt,name=date_range,json=dateRange,proto3" json:"date_range,omitempty"`
	// pagination controls the page size and offset.
	Pagination    *v1.Pagination `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFinancialPositionLogsRequest) Reset() {
	*x = ListFinancialPositionLogsRequest{}
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFinancialPositionLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFinancialPositionLogsRequest) ProtoMessage() {}

func (x *ListFinancialPositionLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFinancialPositionLogsRequest.ProtoReflect.Descriptor instead.
func (*ListFinancialPositionLogsRequest) Descriptor() ([]byte, []int) {
	return file_meridian_position_keeping_v1_position_keeping_proto_rawDescGZIP(), []int{13}
}

func (x *ListFinancialPositionLogsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListFinancialPositionLogsRequest) GetStatus() v1.TransactionStatus {
	if x != nil {
		return x.Status
	}
	return v1.TransactionStatus(0)
}

func (x *ListFinancialPositionLogsRequest) GetDateRange() *v1.DateRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

func (x *ListFinancialPositionLogsRequest) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// ListFinancialPositionLogsResponse returns a list of logs.
type ListFinancialPositionLogsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// logs are the matching financial position logs.
	Logs []*FinancialPositionLog `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	// pagination provides pagination metadata.
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFinancialPositionLogsResponse) Reset() {
	*x = ListFinancialPositionLogsResponse{}
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFinancialPositionLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFinancialPositionLogsResponse) ProtoMessage() {}

func (x *ListFinancialPositionLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_position_keeping_v1_position_keeping_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFinancialPositionLogsResponse.ProtoReflect.Descriptor instead.
func (*ListFinancialPositionLogsResponse) Descriptor() ([]byte, []int) {
	return file_meridian_position_keeping_v1_position_keeping_proto_rawDescGZIP(), []int{14}
}

func (x *ListFinancialPositionLogsResponse) GetLogs() []*FinancialPositionLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ListFinancialPositionLogsResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_meridian_position_keeping_v1_position_keeping_proto protoreflect.FileDescriptor

const file_meridian_position_keeping_v1_position_keeping_proto_rawDesc = "" +
	"\n" +
	"3meridian/position_keeping/v1/position_keeping.proto\x12\x1cmeridian.position_keeping.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1emeridian/common/v1/types.proto\"\xbd\x03\n" +
	"\x13TransactionLogEntry\x12#\n" +
	"\bentry_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aentryId\x12/\n" +
	"\x0etransaction_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\rtransactionId\x12)\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\taccountId\x12?\n" +
	"\x06amount\x18\x04 \x01(\v2\x1f.meridian.common.v1.MoneyAmountB\x06\xbaH\x03\xc8\x01\x01R\x06amount\x12N\n" +
	"\tdirection\x18\x05 \x01(\x0e2$.meridian.common.v1.PostingDirectionB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\tdirection\x12@\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\ttimestamp\x12*\n" +
	"\vdescription\x18\a \x01(\tB\b\xbaH\x05r\x03\x18\xf4\x03R\vdescription\x12&\n" +
	"\treference\x18\b \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\treference\"\x86\x03\n" +
	"\x12TransactionLineage\x12/\n" +
	"\x0etransaction_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\rtransactionId\x12<\n" +
	"\x15parent_transaction_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x13parentTransactionId\x12A\n" +
	"\x15child_transaction_ids\x18\x03 \x03(\tB\r\xbaH\n" +
	"\x92\x01\a\"\x05r\x03\xb0\x01\x01R\x13childTransactionIds\x12E\n" +
	"\x17related_transaction_ids\x18\x04 \x03(\tB\r\xbaH\n" +
	"\x92\x01\a\"\x05r\x03\xb0\x01\x01R\x15relatedTransactionIds\x124\n" +
	"\x10transaction_type\x18\x05 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\x0ftransactionType\x12A\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tcreatedAt\"\xc3\x03\n" +
	"\x0fAuditTrailEntry\x12#\n" +
	"\baudit_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aauditId\x12@\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\ttimestamp\x12#\n" +
	"\auser_id\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x06userId\x12!\n" +
	"\x06action\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\x06action\x12\"\n" +
	"\adetails\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x18\xe8\aR\adetails\x12(\n" +
	"\n" +
	"ip_address\x18\x06 \x01(\tB\t\xbaH\x06r\x04\x18-p\x01R\tipAddress\x12q\n" +
	"\x0esystem_context\x18\a \x03(\v2@.meridian.position_keeping.v1.AuditTrailEntry.SystemContextEntryB\b\xbaH\x05\x9a\x01\x02\x102R\rsystemContext\x1a@\n" +
	"\x12SystemContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xea\x02\n" +
	"\x0eStatusTracking\x12X\n" +
	"\x0ecurrent_status\x18\x01 \x01(\x0e2%.meridian.common.v1.TransactionStatusB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\rcurrentStatus\x12N\n" +
	"\x0fprevious_status\x18\x02 \x01(\x0e2%.meridian.common.v1.TransactionStatusR\x0epreviousStatus\x12N\n" +
	"\x11status_updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\x0fstatusUpdatedAt\x12-\n" +
	"\rstatus_reason\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\xf4\x03R\fstatusReason\x12/\n" +
	"\x0efailure_reason\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x18\xe8\aR\rfailureReason\"\x9e\x05\n" +
	"\x14FinancialPositionLog\x12\x1f\n" +
	"\x06log_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x05logId\x12)\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\taccountId\x12t\n" +
	"\x17transaction_log_entries\x18\x03 \x03(\v21.meridian.position_keeping.v1.TransactionLogEntryB\t\xbaH\x06\x92\x01\x03\x10\x90NR\x15transactionLogEntries\x12a\n" +
	"\x13transaction_lineage\x18\x04 \x01(\v20.meridian.position_keeping.v1.TransactionLineageR\x12transactionLineage\x12Y\n" +
	"\vaudit_trail\x18\x05 \x03(\v2-.meridian.position_keeping.v1.AuditTrailEntryB\t\xbaH\x06\x92\x01\x03\x10\x90NR\n" +
	"auditTrail\x12]\n" +
	"\x0fstatus_tracking\x18\x06 \x01(\v2,.meridian.position_keeping.v1.StatusTrackingB\x06\xbaH\x03\xc8\x01\x01R\x0estatusTracking\x12A\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tcreatedAt\x12A\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tupdatedAt\x12!\n" +
	"\aversion\x18\t \x01(\x03B\a\xbaH\x04\"\x02(\x00R\aversion\"\xdb\x02\n" +
	"#InitiateFinancialPositionLogRequest\x12,\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tB\r\xbaH\n" +
	"\xc8\x01\x01r\x05\x10\x01\x18\xff\x01R\taccountId\x12V\n" +
	"\rinitial_entry\x18\x02 \x01(\v21.meridian.position_keeping.v1.TransactionLogEntryR\finitialEntry\x12a\n" +
	"\x13transaction_lineage\x18\x03 \x01(\v20.meridian.position_keeping.v1.TransactionLineageR\x12transactionLineage\x12K\n" +
	"\x0fidempotency_key\x18\x04 \x01(\v2\".meridian.common.v1.IdempotencyKeyR\x0eidempotencyKey\"t\n" +
	"$InitiateFinancialPositionLogResponse\x12L\n" +
	"\x03log\x18\x01 \x01(\v22.meridian.position_keeping.v1.FinancialPositionLogB\x06\xbaH\x03\xc8\x01\x01R\x03log\"\xaa\x03\n" +
	"!UpdateFinancialPositionLogRequest\x12\"\n" +
	"\x06log_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x05logId\x12N\n" +
	"\tnew_entry\x18\x02 \x01(\v21.meridian.position_keeping.v1.TransactionLogEntryR\bnewEntry\x12Q\n" +
	"\rstatus_update\x18\x03 \x01(\v2,.meridian.position_keeping.v1.StatusTrackingR\fstatusUpdate\x12N\n" +
	"\vaudit_entry\x18\x04 \x01(\v2-.meridian.position_keeping.v1.AuditTrailEntryR\n" +
	"auditEntry\x12!\n" +
	"\aversion\x18\x05 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\aversion\x12K\n" +
	"\x0fidempotency_key\x18\x06 \x01(\v2\".meridian.common.v1.IdempotencyKeyR\x0eidempotencyKey\"r\n" +
	"\"UpdateFinancialPositionLogResponse\x12L\n" +
	"\x03log\x18\x01 \x01(\v22.meridian.position_keeping.v1.FinancialPositionLogB\x06\xbaH\x03\xc8\x01\x01R\x03log\"I\n" +
	"#RetrieveFinancialPositionLogRequest\x12\"\n" +
	"\x06log_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x05logId\"t\n" +
	"$RetrieveFinancialPositionLogResponse\x12L\n" +
	"\x03log\x18\x01 \x01(\v22.meridian.position_keeping.v1.FinancialPositionLogB\x06\xbaH\x03\xc8\x01\x01R\x03log\"\x98\x02\n" +
	"\x1dBulkImportTransactionsRequest\x12\"\n" +
	"\x06log_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x05logId\x12X\n" +
	"\aentries\x18\x02 \x03(\v21.meridian.position_keeping.v1.TransactionLogEntryB\v\xbaH\b\x92\x01\x05\b\x01\x10\xe8\aR\aentries\x12V\n" +
	"\vaudit_entry\x18\x03 \x01(\v2-.meridian.position_keeping.v1.AuditTrailEntryB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"auditEntry\x12!\n" +
	"\aversion\x18\x04 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\aversion\"\xe1\x01\n" +
	"\x1eBulkImportTransactionsResponse\x12L\n" +
	"\x03log\x18\x01 \x01(\v22.meridian.position_keeping.v1.FinancialPositionLogB\x06\xbaH\x03\xc8\x01\x01R\x03log\x12%\n" +
	"\x0eimported_count\x18\x02 \x01(\x05R\rimportedCount\x12!\n" +
	"\ffailed_count\x18\x03 \x01(\x05R\vfailedCount\x12'\n" +
	"\x0ffailure_details\x18\x04 \x03(\tR\x0efailureDetails\"\x88\x02\n" +
	" ListFinancialPositionLogsRequest\x12'\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\taccountId\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.meridian.common.v1.TransactionStatusR\x06status\x12<\n" +
	"\n" +
	"date_range\x18\x03 \x01(\v2\x1d.meridian.common.v1.DateRangeR\tdateRange\x12>\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x1e.meridian.common.v1.PaginationR\n" +
	"pagination\"\xb3\x01\n" +
	"!ListFinancialPositionLogsResponse\x12F\n" +
	"\x04logs\x18\x01 \x03(\v22.meridian.position_keeping.v1.FinancialPositionLogR\x04logs\x12F\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2&.meridian.common.v1.PaginationResponseR\n" +
	"pagination2\xbf\x06\n" +
	"\x16PositionKeepingService\x12\xa5\x01\n" +
	"\x1cInitiateFinancialPositionLog\x12A.meridian.position_keeping.v1.InitiateFinancialPositionLogRequest\x1aB.meridian.position_keeping.v1.InitiateFinancialPositionLogResponse\x12\x9f\x01\n" +
	"\x1aUpdateFinancialPositionLog\x12?.meridian.position_keeping.v1.UpdateFinancialPositionLogRequest\x1a@.meridian.position_keeping.v1.UpdateFinancialPositionLogResponse\x12\xa5\x01\n" +
	"\x1cRetrieveFinancialPositionLog\x12A.meridian.position_keeping.v1.RetrieveFinancialPositionLogRequest\x1aB.meridian.position_keeping.v1.RetrieveFinancialPositionLogResponse\x12\x93\x01\n" +
	"\x16BulkImportTransactions\x12;.meridian.position_keeping.v1.BulkImportTransactionsRequest\x1a<.meridian.position_keeping.v1.BulkImportTransactionsResponse\x12\x9c\x01\n" +
	"\x19ListFinancialPositionLogs\x12>.meridian.position_keeping.v1.ListFinancialPositionLogsRequest\x1a?.meridian.position_keeping.v1.ListFinancialPositionLogsResponseBWZUgithub.com/meridianhub/meridian/api/proto/meridian/position_keeping/v1;positionkeepingv1b\x06proto3"

var (
	file_meridian_position_keeping_v1_position_keeping_proto_rawDescOnce sync.Once
	file_meridian_position_keeping_v1_position_keeping_proto_rawDescData []byte
)

func file_meridian_position_keeping_v1_position_keeping_proto_rawDescGZIP() []byte {
	file_meridian_position_keeping_v1_position_keeping_proto_rawDescOnce.Do(func() {
		file_meridian_position_keeping_v1_position_keeping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meridian_position_keeping_v1_position_keeping_proto_rawDesc), len(file_meridian_position_keeping_v1_position_keeping_proto_rawDesc)))
	})
	return file_meridian_position_keeping_v1_position_keeping_proto_rawDescData
}

var file_meridian_position_keeping_v1_position_keeping_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_meridian_position_keeping_v1_position_keeping_proto_goTypes = []any{
	(*TransactionLogEntry)(nil),                  // 0: meridian.position_keeping.v1.TransactionLogEntry
	(*TransactionLineage)(nil),                   // 1: meridian.position_keeping.v1.TransactionLineage
	(*AuditTrailEntry)(nil),                      // 2: meridian.position_keeping.v1.AuditTrailEntry
	(*StatusTracking)(nil),                       // 3: meridian.position_keeping.v1.StatusTracking
	(*FinancialPositionLog)(nil),                 // 4: meridian.position_keeping.v1.FinancialPositionLog
	(*InitiateFinancialPositionLogRequest)(nil),  // 5: meridian.position_keeping.v1.InitiateFinancialPositionLogRequest
	(*InitiateFinancialPositionLogResponse)(nil), // 6: meridian.position_keeping.v1.InitiateFinancialPositionLogResponse
	(*UpdateFinancialPositionLogRequest)(nil),    // 7: meridian.position_keeping.v1.UpdateFinancialPositionLogRequest
	(*UpdateFinancialPositionLogResponse)(nil),   // 8: meridian.position_keeping.v1.UpdateFinancialPositionLogResponse
	(*RetrieveFinancialPositionLogRequest)(nil),  // 9: meridian.position_keeping.v1.RetrieveFinancialPositionLogRequest
	(*RetrieveFinancialPositionLogResponse)(nil), // 10: meridian.position_keeping.v1.RetrieveFinancialPositionLogResponse
	(*BulkImportTransactionsRequest)(nil),        // 11: meridian.position_keeping.v1.BulkImportTransactionsRequest
	(*BulkImportTransactionsResponse)(nil),       // 12: meridian.position_keeping.v1.BulkImportTransactionsResponse
	(*ListFinancialPositionLogsRequest)(nil),     // 13: meridian.position_keeping.v1.ListFinancialPositionLogsRequest
	(*ListFinancialPositionLogsResponse)(nil),    // 14: meridian.position_keeping.v1.ListFinancialPositionLogsResponse
	nil,                           // 15: meridian.position_keeping.v1.AuditTrailEntry.SystemContextEntry
	(*v1.MoneyAmount)(nil),        // 16: meridian.common.v1.MoneyAmount
	(v1.PostingDirection)(0),      // 17: meridian.common.v1.PostingDirection
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
	(v1.TransactionStatus)(0),     // 19: meridian.common.v1.TransactionStatus
	(*v1.IdempotencyKey)(nil),     // 20: meridian.common.v1.IdempotencyKey
	(*v1.DateRange)(nil),          // 21: meridian.common.v1.DateRange
	(*v1.Pagination)(nil),         // 22: meridian.common.v1.Pagination
	(*v1.PaginationResponse)(nil), // 23: meridian.common.v1.PaginationResponse
}
var file_meridian_position_keeping_v1_position_keeping_proto_depIdxs = []int32{
	16, // 0: meridian.position_keeping.v1.TransactionLogEntry.amount:type_name -> meridian.common.v1.MoneyAmount
	17, // 1: meridian.position_keeping.v1.TransactionLogEntry.direction:type_name -> meridian.common.v1.PostingDirection
	18, // 2: meridian.position_keeping.v1.TransactionLogEntry.timestamp:type_name -> google.protobuf.Timestamp
	18, // 3: meridian.position_keeping.v1.TransactionLineage.created_at:type_name -> google.protobuf.Timestamp
	18, // 4: meridian.position_keeping.v1.AuditTrailEntry.timestamp:type_name -> google.protobuf.Timestamp
	15, // 5: meridian.position_keeping.v1.AuditTrailEntry.system_context:type_name -> meridian.position_keeping.v1.AuditTrailEntry.SystemContextEntry
	19, // 6: meridian.position_keeping.v1.StatusTracking.current_status:type_name -> meridian.common.v1.TransactionStatus
	19, // 7: meridian.position_keeping.v1.StatusTracking.previous_status:type_name -> meridian.common.v1.TransactionStatus
	18, // 8: meridian.position_keeping.v1.StatusTracking.status_updated_at:type_name -> google.protobuf.Timestamp
	0,  // 9: meridian.position_keeping.v1.FinancialPositionLog.transaction_log_entries:type_name -> meridian.position_keeping.v1.TransactionLogEntry
	1,  // 10: meridian.position_keeping.v1.FinancialPositionLog.transaction_lineage:type_name -> meridian.position_keeping.v1.TransactionLineage
	2,  // 11: meridian.position_keeping.v1.FinancialPositionLog.audit_trail:type_name -> meridian.position_keeping.v1.AuditTrailEntry
	3,  // 12: meridian.position_keeping.v1.FinancialPositionLog.status_tracking:type_name -> meridian.position_keeping.v1.StatusTracking
	18, // 13: meridian.position_keeping.v1.FinancialPositionLog.created_at:type_name -> google.protobuf.Timestamp
	18, // 14: meridian.position_keeping.v1.FinancialPositionLog.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 15: meridian.position_keeping.v1.InitiateFinancialPositionLogRequest.initial_entry:type_name -> meridian.position_keeping.v1.TransactionLogEntry
	1,  // 16: meridian.position_keeping.v1.InitiateFinancialPositionLogRequest.transaction_lineage:type_name -> meridian.position_keeping.v1.TransactionLineage
	20, // 17: meridian.position_keeping.v1.InitiateFinancialPositionLogRequest.idempotency_key:type_name -> meridian.common.v1.IdempotencyKey
	4,  // 18: meridian.position_keeping.v1.InitiateFinancialPositionLogResponse.log:type_name -> meridian.position_keeping.v1.FinancialPositionLog
	0,  // 19: meridian.position_keeping.v1.UpdateFinancialPositionLogRequest.new_entry:type_name -> meridian.position_keeping.v1.TransactionLogEntry
	3,  // 20: meridian.position_keeping.v1.UpdateFinancialPositionLogRequest.status_update:type_name -> meridian.position_keeping.v1.StatusTracking
	2,  // 21: meridian.position_keeping.v1.UpdateFinancialPositionLogRequest.audit_entry:type_name -> meridian.position_keeping.v1.AuditTrailEntry
	20, // 22: meridian.position_keeping.v1.UpdateFinancialPositionLogRequest.idempotency_key:type_name -> meridian.common.v1.IdempotencyKey
	4,  // 23: meridian.position_keeping.v1.UpdateFinancialPositionLogResponse.log:type_name -> meridian.position_keeping.v1.FinancialPositionLog
	4,  // 24: meridian.position_keeping.v1.RetrieveFinancialPositionLogResponse.log:type_name -> meridian.position_keeping.v1.FinancialPositionLog
	0,  // 25: meridian.position_keeping.v1.BulkImportTransactionsRequest.entries:type_name -> meridian.position_keeping.v1.TransactionLogEntry
	2,  // 26: meridian.position_keeping.v1.BulkImportTransactionsRequest.audit_entry:type_name -> meridian.position_keeping.v1.AuditTrailEntry
	4,  // 27: meridian.position_keeping.v1.BulkImportTransactionsResponse.log:type_name -> meridian.position_keeping.v1.FinancialPositionLog
	19, // 28: meridian.position_keeping.v1.ListFinancialPositionLogsRequest.status:type_name -> meridian.common.v1.TransactionStatus
	21, // 29: meridian.position_keeping.v1.ListFinancialPositionLogsRequest.date_range:type_name -> meridian.common.v1.DateRange
	22, // 30: meridian.position_keeping.v1.ListFinancialPositionLogsRequest.pagination:type_name -> meridian.common.v1.Pagination
	4,  // 31: meridian.position_keeping.v1.ListFinancialPositionLogsResponse.logs:type_name -> meridian.position_keeping.v1.FinancialPositionLog
	23, // 32: meridian.position_keeping.v1.ListFinancialPositionLogsResponse.pagination:type_name -> meridian.common.v1.PaginationResponse
	5,  // 33: meridian.position_keeping.v1.PositionKeepingService.InitiateFinancialPositionLog:input_type -> meridian.position_keeping.v1.InitiateFinancialPositionLogRequest
	7,  // 34: meridian.position_keeping.v1.PositionKeepingService.UpdateFinancialPositionLog:input_type -> meridian.position_keeping.v1.UpdateFinancialPositionLogRequest
	9,  // 35: meridian.position_keeping.v1.PositionKeepingService.RetrieveFinancialPositionLog:input_type -> meridian.position_keeping.v1.RetrieveFinancialPositionLogRequest
	11, // 36: meridian.position_keeping.v1.PositionKeepingService.BulkImportTransactions:input_type -> meridian.position_keeping.v1.BulkImportTransactionsRequest
	13, // 37: meridian.position_keeping.v1.PositionKeepingService.ListFinancialPositionLogs:input_type -> meridian.position_keeping.v1.ListFinancialPositionLogsRequest
	6,  // 38: meridian.position_keeping.v1.PositionKeepingService.InitiateFinancialPositionLog:output_type -> meridian.position_keeping.v1.InitiateFinancialPositionLogResponse
	8,  // 39: meridian.position_keeping.v1.PositionKeepingService.UpdateFinancialPositionLog:output_type -> meridian.position_keeping.v1.UpdateFinancialPositionLogResponse
	10, // 40: meridian.position_keeping.v1.PositionKeepingService.RetrieveFinancialPositionLog:output_type -> meridian.position_keeping.v1.RetrieveFinancialPositionLogResponse
	12, // 41: meridian.position_keeping.v1.PositionKeepingService.BulkImportTransactions:output_type -> meridian.position_keeping.v1.BulkImportTransactionsResponse
	14, // 42: meridian.position_keeping.v1.PositionKeepingService.ListFinancialPositionLogs:output_type -> meridian.position_keeping.v1.ListFinancialPositionLogsResponse
	38, // [38:43] is the sub-list for method output_type
	33, // [33:38] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_meridian_position_keeping_v1_position_keeping_proto_init() }
func file_meridian_position_keeping_v1_position_keeping_proto_init() {
	if File_meridian_position_keeping_v1_position_keeping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meridian_position_keeping_v1_position_keeping_proto_rawDesc), len(file_meridian_position_keeping_v1_position_keeping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meridian_position_keeping_v1_position_keeping_proto_goTypes,
		DependencyIndexes: file_meridian_position_keeping_v1_position_keeping_proto_depIdxs,
		MessageInfos:      file_meridian_position_keeping_v1_position_keeping_proto_msgTypes,
	}.Build()
	File_meridian_position_keeping_v1_position_keeping_proto = out.File
	file_meridian_position_keeping_v1_position_keeping_proto_goTypes = nil
	file_meridian_position_keeping_v1_position_keeping_proto_depIdxs = nil
}
