// Package saga provides saga orchestration runtime and persistence for durable execution.
package saga

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"time"

	"github.com/google/uuid"
	"go.starlark.net/starlark"
)

// Runner errors.
var (
	// ErrRuntimeRequired is returned when Runtime is nil.
	ErrRuntimeRequired = errors.New("runtime is required")

	// ErrRegistryRequired is returned when Registry is nil.
	ErrRegistryRequired = errors.New("registry is required")

	// ErrInvokeHandlerMissingName is returned when invoke_handler is called without a handler kwarg.
	ErrInvokeHandlerMissingName = errors.New("invoke_handler: handler keyword argument is required")

	// ErrInvokeHandlerBadType is returned when invoke_handler receives a wrong type for a kwarg.
	ErrInvokeHandlerBadType = errors.New("invoke_handler: unexpected type")
)

// StarlarkSagaRunner executes saga definitions written in Starlark.
// It integrates the Starlark Runtime with the DomainHandlerRegistry to enable
// Starlark scripts to call domain-specific handlers via typed service modules.
type StarlarkSagaRunner struct {
	runtime        *Runtime
	registry       *DomainHandlerRegistry
	serviceModules starlark.StringDict // Pre-built service modules for Starlark injection
	logger         *slog.Logger
}

// StarlarkSagaRunnerConfig contains configuration for creating a StarlarkSagaRunner.
type StarlarkSagaRunnerConfig struct {
	// Runtime is the Starlark execution runtime.
	Runtime *Runtime

	// Registry contains domain-specific handlers that Starlark scripts can call.
	Registry *DomainHandlerRegistry

	// ServiceModules contains pre-built Starlark service modules generated by
	// schema.BuildServiceModules(). When set, these modules are injected into
	// the Starlark global scope, enabling typed handler calls like:
	//   position_keeping.initiate_log(position_id="123", amount="100.00")
	// instead of:
	//   invoke_handler(handler="position_keeping.initiate_log", params={...})
	ServiceModules starlark.StringDict

	// Logger for structured logging.
	Logger *slog.Logger
}

// NewStarlarkSagaRunner creates a new StarlarkSagaRunner.
func NewStarlarkSagaRunner(cfg StarlarkSagaRunnerConfig) (*StarlarkSagaRunner, error) {
	if cfg.Runtime == nil {
		return nil, ErrRuntimeRequired
	}
	if cfg.Registry == nil {
		return nil, ErrRegistryRequired
	}

	logger := cfg.Logger
	if logger == nil {
		logger = slog.Default()
	}

	return &StarlarkSagaRunner{
		runtime:        cfg.Runtime,
		registry:       cfg.Registry,
		serviceModules: cfg.ServiceModules,
		logger:         logger,
	}, nil
}

// RunnerInput contains the input parameters for a saga execution.
type RunnerInput struct {
	// SagaExecutionID is the unique identifier for this saga execution.
	SagaExecutionID uuid.UUID

	// CorrelationID groups all related actions across the entire business operation.
	CorrelationID uuid.UUID

	// PartyScope restricts data access to a specific party (tenant isolation).
	PartyScope *PartyScope

	// KnowledgeAt enables bi-temporal queries - what we knew at a specific point in time.
	KnowledgeAt time.Time

	// Input contains the saga-specific input parameters.
	Input map[string]interface{}
}

// RunnerOutput contains the result of a saga execution.
type RunnerOutput struct {
	// Success indicates whether the saga completed successfully.
	Success bool

	// Output contains the saga's output variables.
	Output map[string]interface{}

	// Error contains the error message if Success is false.
	Error string

	// StepResults contains the results of each step for debugging.
	StepResults []StepResult
}

// StepResult captures the result of a single saga step.
type StepResult struct {
	// StepName is the handler name that was called.
	StepName string

	// Success indicates whether the step succeeded.
	Success bool

	// Output contains the step's output.
	Output interface{}

	// Error contains the error message if Success is false.
	Error string

	// Duration is how long the step took to execute.
	Duration time.Duration
}

// ExecuteSaga executes a Starlark saga script with the given input.
// The script can call domain handlers via the domain_call builtin function.
func (r *StarlarkSagaRunner) ExecuteSaga(ctx context.Context, sagaName string, script string, input RunnerInput) (*RunnerOutput, error) {
	logger := r.logger.With(
		"saga_name", sagaName,
		"saga_execution_id", input.SagaExecutionID.String(),
		"correlation_id", input.CorrelationID.String(),
	)

	logger.Info("starting Starlark saga execution")

	// Create StarlarkContext for domain handlers
	starlarkCtx := &StarlarkContext{
		Context:         ctx,
		PartyScope:      input.PartyScope,
		SagaExecutionID: input.SagaExecutionID,
		CorrelationID:   input.CorrelationID,
		KnowledgeAt:     input.KnowledgeAt,
		Logger:          logger,
		LookupCache:     NewLookupResultCache(),
	}

	// Track step results for both service module calls and invoke_handler shim
	var stepResults []StepResult

	// Build input for Starlark script
	scriptInput := make(map[string]interface{})
	for k, v := range input.Input {
		scriptInput[k] = v
	}

	// Add metadata as special inputs
	scriptInput["_saga_execution_id"] = input.SagaExecutionID.String()
	scriptInput["_correlation_id"] = input.CorrelationID.String()

	// Build additional predeclared globals
	predeclared := make(starlark.StringDict)

	// Inject service modules into Starlark global scope
	for name, module := range r.serviceModules {
		predeclared[name] = module
	}

	// Add invoke_handler backward compatibility shim
	predeclared["invoke_handler"] = r.buildInvokeHandlerShim(starlarkCtx, &stepResults)

	// Execute the Starlark script with service modules and StarlarkContext on the thread
	result, err := r.runtime.ExecuteSagaWithInput(ctx, sagaName, script, ExecutionInput{
		Data:        scriptInput,
		Predeclared: predeclared,
		ThreadSetup: func(thread *starlark.Thread) {
			// Set StarlarkContext on the thread so service module handlers can access it
			thread.SetLocal("saga.StarlarkContext", starlarkCtx)
		},
	})
	if err != nil {
		logger.Error("Starlark saga execution failed", "error", err)
		return &RunnerOutput{
			Success:     false,
			Error:       err.Error(),
			StepResults: stepResults,
		}, nil
	}

	// Check if the saga was suspended
	if starlarkCtx.IsSuspended() {
		logger.Info("saga suspended",
			"reason", starlarkCtx.SuspendReason,
			"resume_after", starlarkCtx.ResumeAfter)
		return &RunnerOutput{
			Success:     false,
			Output:      result.Globals,
			Error:       fmt.Sprintf("saga suspended: %s", starlarkCtx.SuspendReason),
			StepResults: stepResults,
		}, nil
	}

	logger.Info("Starlark saga execution completed",
		"step_count", len(stepResults),
		"success", true)

	return &RunnerOutput{
		Success:     true,
		Output:      result.Globals,
		StepResults: stepResults,
	}, nil
}

// buildInvokeHandlerShim creates a backward-compatible invoke_handler Starlark builtin.
// This allows existing scripts using invoke_handler(handler="name", params={...})
// to continue working while migration to typed service modules proceeds.
//
//nolint:gocognit // Handler shim requires checking multiple kwargs conditions
func (r *StarlarkSagaRunner) buildInvokeHandlerShim(starlarkCtx *StarlarkContext, stepResults *[]StepResult) *starlark.Builtin {
	return starlark.NewBuiltin("invoke_handler", func(_ *starlark.Thread, _ *starlark.Builtin, _ starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
		r.logger.Warn("invoke_handler is deprecated, use typed service modules instead",
			"saga_execution_id", starlarkCtx.SagaExecutionID.String())

		// Extract handler name from kwargs
		var handlerName string
		var paramsDict *starlark.Dict

		for _, kwarg := range kwargs {
			keyVal, ok := kwarg[0].(starlark.String)
			if !ok {
				return nil, fmt.Errorf("%w: kwarg key is %s, want string", ErrInvokeHandlerBadType, kwarg[0].Type())
			}
			switch string(keyVal) {
			case "handler":
				s, ok := kwarg[1].(starlark.String)
				if !ok {
					return nil, fmt.Errorf("%w: handler must be a string, got %s", ErrInvokeHandlerBadType, kwarg[1].Type())
				}
				handlerName = string(s)
			case "params":
				d, ok := kwarg[1].(*starlark.Dict)
				if !ok {
					return nil, fmt.Errorf("%w: params must be a dict, got %s", ErrInvokeHandlerBadType, kwarg[1].Type())
				}
				paramsDict = d
			}
		}

		if handlerName == "" {
			return nil, ErrInvokeHandlerMissingName
		}

		stepStart := time.Now()

		// Look up handler in registry
		handler, err := r.registry.Get(handlerName)
		if err != nil {
			*stepResults = append(*stepResults, StepResult{
				StepName: handlerName,
				Success:  false,
				Error:    err.Error(),
				Duration: time.Since(stepStart),
			})
			return nil, fmt.Errorf("invoke_handler: %w", err)
		}

		// Convert Starlark dict to Go map
		params := make(map[string]any)
		if paramsDict != nil {
			for _, item := range paramsDict.Items() {
				key, ok := item[0].(starlark.String)
				if !ok {
					return nil, fmt.Errorf("%w: param key must be string, got %s", ErrInvokeHandlerBadType, item[0].Type())
				}
				params[string(key)] = starlarkToGo(item[1])
			}
		}

		// Call handler
		result, err := handler(starlarkCtx, params)
		duration := time.Since(stepStart)

		if err != nil {
			*stepResults = append(*stepResults, StepResult{
				StepName: handlerName,
				Success:  false,
				Error:    err.Error(),
				Duration: duration,
			})
			return nil, err
		}

		*stepResults = append(*stepResults, StepResult{
			StepName: handlerName,
			Success:  true,
			Output:   result,
			Duration: duration,
		})

		// Convert result to Starlark value
		return goToStarlark(result), nil
	})
}

// WithLogger returns a new runner with the given logger.
func (r *StarlarkSagaRunner) WithLogger(logger *slog.Logger) *StarlarkSagaRunner {
	if logger == nil {
		logger = slog.Default()
	}
	return &StarlarkSagaRunner{
		runtime:        r.runtime,
		registry:       r.registry,
		serviceModules: r.serviceModules,
		logger:         logger,
	}
}
