// Package saga provides saga orchestration runtime and persistence for durable execution.
package saga

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"time"

	"github.com/google/uuid"
	"go.starlark.net/starlark"
)

// Runner errors.
var (
	// ErrRuntimeRequired is returned when Runtime is nil.
	ErrRuntimeRequired = errors.New("runtime is required")

	// ErrRegistryRequired is returned when Registry is nil.
	ErrRegistryRequired = errors.New("registry is required")
)

// StarlarkSagaRunner executes saga definitions written in Starlark.
// It integrates the Starlark Runtime with the HandlerRegistry to enable
// Starlark scripts to call domain-specific handlers via typed service modules.
type StarlarkSagaRunner struct {
	runtime        *Runtime
	registry       *HandlerRegistry
	serviceModules starlark.StringDict // Pre-built service modules for Starlark injection
	logger         *slog.Logger
}

// StarlarkSagaRunnerConfig contains configuration for creating a StarlarkSagaRunner.
type StarlarkSagaRunnerConfig struct {
	// Runtime is the Starlark execution runtime.
	Runtime *Runtime

	// Registry contains domain-specific handlers that Starlark scripts can call.
	Registry *HandlerRegistry

	// ServiceModules contains pre-built Starlark service modules generated by
	// schema.BuildServiceModules(). When set, these modules are injected into
	// the Starlark global scope, enabling typed handler calls like:
	//   position_keeping.initiate_log(position_id="123", amount="100.00")
	ServiceModules starlark.StringDict

	// Logger for structured logging.
	Logger *slog.Logger
}

// NewStarlarkSagaRunner creates a new StarlarkSagaRunner.
func NewStarlarkSagaRunner(cfg StarlarkSagaRunnerConfig) (*StarlarkSagaRunner, error) {
	if cfg.Runtime == nil {
		return nil, ErrRuntimeRequired
	}
	if cfg.Registry == nil {
		return nil, ErrRegistryRequired
	}

	logger := cfg.Logger
	if logger == nil {
		logger = slog.Default()
	}

	return &StarlarkSagaRunner{
		runtime:        cfg.Runtime,
		registry:       cfg.Registry,
		serviceModules: cfg.ServiceModules,
		logger:         logger,
	}, nil
}

// RunnerInput contains the input parameters for a saga execution.
type RunnerInput struct {
	// SagaExecutionID is the unique identifier for this saga execution.
	SagaExecutionID uuid.UUID

	// CorrelationID groups all related actions across the entire business operation.
	CorrelationID uuid.UUID

	// PartyScope restricts data access to a specific party (tenant isolation).
	PartyScope *PartyScope

	// KnowledgeAt enables bi-temporal queries - what we knew at a specific point in time.
	KnowledgeAt time.Time

	// Input contains the saga-specific input parameters.
	Input map[string]interface{}
}

// RunnerOutput contains the result of a saga execution.
type RunnerOutput struct {
	// Success indicates whether the saga completed successfully.
	Success bool

	// Output contains the saga's output variables.
	Output map[string]interface{}

	// Error contains the error message if Success is false.
	Error string

	// StepResults contains the results of each step for debugging.
	StepResults []StepResult
}

// StepResult captures the result of a single saga step.
type StepResult struct {
	// StepName is the handler name that was called.
	StepName string

	// Success indicates whether the step succeeded.
	Success bool

	// Output contains the step's output.
	Output interface{}

	// Error contains the error message if Success is false.
	Error string

	// Duration is how long the step took to execute.
	Duration time.Duration

	// CompensateHandler is the qualified name of the compensation handler to call
	// if the saga fails (e.g., "position_keeping.cancel_log").
	CompensateHandler string

	// CompensateParams contains parameters derived from the forward step output
	// to be passed to the compensation handler.
	CompensateParams map[string]any
}

// ExecuteSaga executes a Starlark saga script with the given input.
// The script can call domain handlers via the domain_call builtin function.
func (r *StarlarkSagaRunner) ExecuteSaga(ctx context.Context, sagaName string, script string, input RunnerInput) (*RunnerOutput, error) {
	logger := r.logger.With(
		"saga_name", sagaName,
		"saga_execution_id", input.SagaExecutionID.String(),
		"correlation_id", input.CorrelationID.String(),
	)

	logger.Info("starting Starlark saga execution")

	starlarkCtx := r.buildStarlarkContext(ctx, input, logger)

	var stepResults []StepResult

	scriptInput := r.buildScriptInput(input)
	predeclared := r.buildPredeclaredModules()

	// Execute the Starlark script with service modules and StarlarkContext on the thread
	result, err := r.runtime.ExecuteSagaWithInput(ctx, sagaName, script, ExecutionInput{
		Data:        scriptInput,
		Predeclared: predeclared,
		ThreadSetup: func(thread *starlark.Thread) {
			thread.SetLocal("saga.StarlarkContext", starlarkCtx)
			thread.SetLocal("saga.StepResults", &stepResults)
		},
	})
	if err != nil {
		return r.handleExecutionFailure(starlarkCtx, stepResults, err, logger), nil
	}

	// Check if the saga was suspended
	if starlarkCtx.IsSuspended() {
		logger.Info("saga suspended",
			"reason", starlarkCtx.SuspendReason,
			"resume_after", starlarkCtx.ResumeAfter)
		return &RunnerOutput{
			Success:     false,
			Output:      result.Globals,
			Error:       fmt.Sprintf("saga suspended: %s", starlarkCtx.SuspendReason),
			StepResults: stepResults,
		}, nil
	}

	logger.Info("Starlark saga execution completed",
		"step_count", len(stepResults),
		"success", true)

	return &RunnerOutput{
		Success:     true,
		Output:      extractOutputMap(result.Globals),
		StepResults: stepResults,
	}, nil
}

// buildStarlarkContext creates a StarlarkContext for domain handler execution.
func (r *StarlarkSagaRunner) buildStarlarkContext(ctx context.Context, input RunnerInput, logger *slog.Logger) *StarlarkContext {
	return &StarlarkContext{
		Context:         ctx,
		PartyScope:      input.PartyScope,
		SagaExecutionID: input.SagaExecutionID,
		CorrelationID:   input.CorrelationID,
		KnowledgeAt:     input.KnowledgeAt,
		Logger:          logger,
		LookupCache:     NewLookupResultCache(),
	}
}

// buildScriptInput creates the input map for the Starlark script, including metadata.
func (r *StarlarkSagaRunner) buildScriptInput(input RunnerInput) map[string]interface{} {
	scriptInput := make(map[string]interface{})
	for k, v := range input.Input {
		scriptInput[k] = v
	}
	scriptInput["_saga_execution_id"] = input.SagaExecutionID.String()
	scriptInput["_correlation_id"] = input.CorrelationID.String()
	return scriptInput
}

// buildPredeclaredModules injects service modules into a Starlark StringDict for global scope.
func (r *StarlarkSagaRunner) buildPredeclaredModules() starlark.StringDict {
	predeclared := make(starlark.StringDict)
	for name, module := range r.serviceModules {
		predeclared[name] = module
	}
	return predeclared
}

// handleExecutionFailure runs compensation and returns a failure RunnerOutput.
func (r *StarlarkSagaRunner) handleExecutionFailure(starlarkCtx *StarlarkContext, stepResults []StepResult, err error, logger *slog.Logger) *RunnerOutput {
	logger.Error("Starlark saga execution failed", "error", err)

	if compErr := r.executeCompensation(starlarkCtx, stepResults); compErr != nil {
		logger.Error("compensation execution failed", "error", compErr)
		err = fmt.Errorf("saga failed: %w; compensation also failed: %w", err, compErr)
	}

	return &RunnerOutput{
		Success:     false,
		Error:       err.Error(),
		StepResults: stepResults,
	}
}

// extractOutputMap extracts the "output" global variable if present, falling back to all globals.
func extractOutputMap(globals map[string]interface{}) map[string]interface{} {
	if outputValue, ok := globals["output"]; ok {
		if outputAsMap, ok := outputValue.(map[string]interface{}); ok {
			return outputAsMap
		}
	}
	return globals
}

// WithLogger returns a new runner with the given logger.
func (r *StarlarkSagaRunner) WithLogger(logger *slog.Logger) *StarlarkSagaRunner {
	if logger == nil {
		logger = slog.Default()
	}
	return &StarlarkSagaRunner{
		runtime:        r.runtime,
		registry:       r.registry,
		serviceModules: r.serviceModules,
		logger:         logger,
	}
}

// executeCompensation executes compensation handlers in LIFO (Last In, First Out) order
// for all completed saga steps. This implements the standard saga compensation pattern
// where the most recently completed step is compensated first, working backwards to
// the first step.
//
// Compensation is best-effort: if a compensation handler fails, the error is logged
// and returned, but execution continues to compensate remaining steps. This ensures
// maximum rollback coverage even in the presence of failures.
func (r *StarlarkSagaRunner) executeCompensation(ctx *StarlarkContext, completedSteps []StepResult) error {
	if len(completedSteps) == 0 {
		return nil
	}

	logger := r.logger.With(
		"saga_execution_id", ctx.SagaExecutionID.String(),
		"compensation_step_count", len(completedSteps),
	)

	logger.Info("starting compensation execution")

	var compensationErrors []error

	// Iterate in reverse order (LIFO)
	for i := len(completedSteps) - 1; i >= 0; i-- {
		if err := r.compensateStep(ctx, completedSteps[i], i, logger); err != nil {
			compensationErrors = append(compensationErrors, err)
		}
	}

	if len(compensationErrors) > 0 {
		logger.Error("compensation completed with errors",
			"error_count", len(compensationErrors),
		)
		return compensationErrors[0]
	}

	logger.Info("compensation execution completed successfully")
	return nil
}

// compensateStep executes compensation for a single step, returning an error if it fails.
func (r *StarlarkSagaRunner) compensateStep(ctx *StarlarkContext, step StepResult, index int, logger *slog.Logger) error {
	if step.CompensateHandler == "" {
		logger.Debug("skipping step without compensation handler", "step_name", step.StepName)
		return nil
	}

	logger.Info("executing compensation",
		"step_name", step.StepName,
		"compensate_handler", step.CompensateHandler,
		"step_index", index,
	)

	handler, err := r.registry.Get(step.CompensateHandler)
	if err != nil {
		logger.Error("compensation handler not found",
			"compensate_handler", step.CompensateHandler,
			"error", err,
		)
		return fmt.Errorf("compensation handler %s not found for step %s: %w",
			step.CompensateHandler, step.StepName, err)
	}

	_, err = handler(ctx, step.CompensateParams)
	if err != nil {
		logger.Error("compensation failed",
			"compensate_handler", step.CompensateHandler,
			"step_name", step.StepName,
			"error", err,
		)
		return fmt.Errorf("compensation failed for %s (step %s): %w",
			step.CompensateHandler, step.StepName, err)
	}

	logger.Info("compensation succeeded",
		"compensate_handler", step.CompensateHandler,
		"step_name", step.StepName,
	)
	return nil
}
