// Package saga provides saga orchestration runtime and persistence for durable execution.
package saga

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"time"

	"github.com/google/uuid"
	"go.starlark.net/starlark"
)

// Runner errors.
var (
	// ErrRuntimeRequired is returned when Runtime is nil.
	ErrRuntimeRequired = errors.New("runtime is required")

	// ErrRegistryRequired is returned when Registry is nil.
	ErrRegistryRequired = errors.New("registry is required")

	// ErrInvokeHandlerMissingName is returned when invoke_handler is called without a handler kwarg.
	ErrInvokeHandlerMissingName = errors.New("invoke_handler: handler keyword argument is required")

	// ErrInvokeHandlerBadType is returned when invoke_handler receives a wrong type for a kwarg.
	ErrInvokeHandlerBadType = errors.New("invoke_handler: unexpected type")
)

// StarlarkSagaRunner executes saga definitions written in Starlark.
// It integrates the Starlark Runtime with the HandlerRegistry to enable
// Starlark scripts to call domain-specific handlers via typed service modules.
type StarlarkSagaRunner struct {
	runtime        *Runtime
	registry       *HandlerRegistry
	serviceModules starlark.StringDict // Pre-built service modules for Starlark injection
	logger         *slog.Logger
}

// StarlarkSagaRunnerConfig contains configuration for creating a StarlarkSagaRunner.
type StarlarkSagaRunnerConfig struct {
	// Runtime is the Starlark execution runtime.
	Runtime *Runtime

	// Registry contains domain-specific handlers that Starlark scripts can call.
	Registry *HandlerRegistry

	// ServiceModules contains pre-built Starlark service modules generated by
	// schema.BuildServiceModules(). When set, these modules are injected into
	// the Starlark global scope, enabling typed handler calls like:
	//   position_keeping.initiate_log(position_id="123", amount="100.00")
	// instead of:
	//   invoke_handler(handler="position_keeping.initiate_log", params={...})
	ServiceModules starlark.StringDict

	// Logger for structured logging.
	Logger *slog.Logger
}

// NewStarlarkSagaRunner creates a new StarlarkSagaRunner.
func NewStarlarkSagaRunner(cfg StarlarkSagaRunnerConfig) (*StarlarkSagaRunner, error) {
	if cfg.Runtime == nil {
		return nil, ErrRuntimeRequired
	}
	if cfg.Registry == nil {
		return nil, ErrRegistryRequired
	}

	logger := cfg.Logger
	if logger == nil {
		logger = slog.Default()
	}

	return &StarlarkSagaRunner{
		runtime:        cfg.Runtime,
		registry:       cfg.Registry,
		serviceModules: cfg.ServiceModules,
		logger:         logger,
	}, nil
}

// RunnerInput contains the input parameters for a saga execution.
type RunnerInput struct {
	// SagaExecutionID is the unique identifier for this saga execution.
	SagaExecutionID uuid.UUID

	// CorrelationID groups all related actions across the entire business operation.
	CorrelationID uuid.UUID

	// PartyScope restricts data access to a specific party (tenant isolation).
	PartyScope *PartyScope

	// KnowledgeAt enables bi-temporal queries - what we knew at a specific point in time.
	KnowledgeAt time.Time

	// Input contains the saga-specific input parameters.
	Input map[string]interface{}
}

// RunnerOutput contains the result of a saga execution.
type RunnerOutput struct {
	// Success indicates whether the saga completed successfully.
	Success bool

	// Output contains the saga's output variables.
	Output map[string]interface{}

	// Error contains the error message if Success is false.
	Error string

	// StepResults contains the results of each step for debugging.
	StepResults []StepResult
}

// StepResult captures the result of a single saga step.
type StepResult struct {
	// StepName is the handler name that was called.
	StepName string

	// Success indicates whether the step succeeded.
	Success bool

	// Output contains the step's output.
	Output interface{}

	// Error contains the error message if Success is false.
	Error string

	// Duration is how long the step took to execute.
	Duration time.Duration

	// CompensateHandler is the qualified name of the compensation handler to call
	// if the saga fails (e.g., "position_keeping.cancel_log").
	CompensateHandler string

	// CompensateParams contains parameters derived from the forward step output
	// to be passed to the compensation handler.
	CompensateParams map[string]any
}

// ExecuteSaga executes a Starlark saga script with the given input.
// The script can call domain handlers via the domain_call builtin function.
func (r *StarlarkSagaRunner) ExecuteSaga(ctx context.Context, sagaName string, script string, input RunnerInput) (*RunnerOutput, error) {
	logger := r.logger.With(
		"saga_name", sagaName,
		"saga_execution_id", input.SagaExecutionID.String(),
		"correlation_id", input.CorrelationID.String(),
	)

	logger.Info("starting Starlark saga execution")

	// Create StarlarkContext for domain handlers
	starlarkCtx := &StarlarkContext{
		Context:         ctx,
		PartyScope:      input.PartyScope,
		SagaExecutionID: input.SagaExecutionID,
		CorrelationID:   input.CorrelationID,
		KnowledgeAt:     input.KnowledgeAt,
		Logger:          logger,
		LookupCache:     NewLookupResultCache(),
	}

	// Track step results for both service module calls and invoke_handler shim
	var stepResults []StepResult

	// Build input for Starlark script
	scriptInput := make(map[string]interface{})
	for k, v := range input.Input {
		scriptInput[k] = v
	}

	// Add metadata as special inputs
	scriptInput["_saga_execution_id"] = input.SagaExecutionID.String()
	scriptInput["_correlation_id"] = input.CorrelationID.String()

	// Build additional predeclared globals
	predeclared := make(starlark.StringDict)

	// Inject service modules into Starlark global scope
	for name, module := range r.serviceModules {
		predeclared[name] = module
	}

	// Add invoke_handler backward compatibility shim
	predeclared["invoke_handler"] = r.buildInvokeHandlerShim(starlarkCtx, &stepResults)

	// Execute the Starlark script with service modules and StarlarkContext on the thread
	result, err := r.runtime.ExecuteSagaWithInput(ctx, sagaName, script, ExecutionInput{
		Data:        scriptInput,
		Predeclared: predeclared,
		ThreadSetup: func(thread *starlark.Thread) {
			// Set StarlarkContext on the thread so service module handlers can access it
			thread.SetLocal("saga.StarlarkContext", starlarkCtx)
			// Set stepResults pointer so service modules can append compensation metadata
			thread.SetLocal("saga.StepResults", &stepResults)
		},
	})
	if err != nil {
		logger.Error("Starlark saga execution failed", "error", err)

		// Execute compensation handlers in LIFO order
		if compErr := r.executeCompensation(starlarkCtx, stepResults); compErr != nil {
			logger.Error("compensation execution failed", "error", compErr)
			// Append compensation error to saga error
			err = fmt.Errorf("saga failed: %w; compensation also failed: %w", err, compErr)
		}

		return &RunnerOutput{
			Success:     false,
			Error:       err.Error(),
			StepResults: stepResults,
		}, nil
	}

	// Check if the saga was suspended
	if starlarkCtx.IsSuspended() {
		logger.Info("saga suspended",
			"reason", starlarkCtx.SuspendReason,
			"resume_after", starlarkCtx.ResumeAfter)
		return &RunnerOutput{
			Success:     false,
			Output:      result.Globals,
			Error:       fmt.Sprintf("saga suspended: %s", starlarkCtx.SuspendReason),
			StepResults: stepResults,
		}, nil
	}

	logger.Info("Starlark saga execution completed",
		"step_count", len(stepResults),
		"success", true)

	// Extract the "output" global variable if present (common pattern in saga scripts)
	// Otherwise fall back to using all globals as the output
	outputMap := result.Globals
	if outputValue, ok := result.Globals["output"]; ok {
		// result.Globals values are already Go types (converted from Starlark)
		// Try to use it as a map directly
		if outputAsMap, ok := outputValue.(map[string]interface{}); ok {
			outputMap = outputAsMap
		}
	}

	return &RunnerOutput{
		Success:     true,
		Output:      outputMap,
		StepResults: stepResults,
	}, nil
}

// buildInvokeHandlerShim creates a backward-compatible invoke_handler Starlark builtin.
// This allows existing scripts using invoke_handler(handler="name", params={...})
// to continue working while migration to typed service modules proceeds.
//
//nolint:gocognit // Handler shim requires checking multiple kwargs conditions
func (r *StarlarkSagaRunner) buildInvokeHandlerShim(starlarkCtx *StarlarkContext, stepResults *[]StepResult) *starlark.Builtin {
	return starlark.NewBuiltin("invoke_handler", func(_ *starlark.Thread, _ *starlark.Builtin, _ starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
		r.logger.Warn("invoke_handler is deprecated, use typed service modules instead",
			"saga_execution_id", starlarkCtx.SagaExecutionID.String())

		// Extract handler name from kwargs
		var handlerName string
		var paramsDict *starlark.Dict

		for _, kwarg := range kwargs {
			keyVal, ok := kwarg[0].(starlark.String)
			if !ok {
				return nil, fmt.Errorf("%w: kwarg key is %s, want string", ErrInvokeHandlerBadType, kwarg[0].Type())
			}
			switch string(keyVal) {
			case "handler":
				s, ok := kwarg[1].(starlark.String)
				if !ok {
					return nil, fmt.Errorf("%w: handler must be a string, got %s", ErrInvokeHandlerBadType, kwarg[1].Type())
				}
				handlerName = string(s)
			case "params":
				d, ok := kwarg[1].(*starlark.Dict)
				if !ok {
					return nil, fmt.Errorf("%w: params must be a dict, got %s", ErrInvokeHandlerBadType, kwarg[1].Type())
				}
				paramsDict = d
			}
		}

		if handlerName == "" {
			return nil, ErrInvokeHandlerMissingName
		}

		stepStart := time.Now()

		// Look up handler in registry
		handler, err := r.registry.Get(handlerName)
		if err != nil {
			*stepResults = append(*stepResults, StepResult{
				StepName: handlerName,
				Success:  false,
				Error:    err.Error(),
				Duration: time.Since(stepStart),
			})
			return nil, fmt.Errorf("invoke_handler: %w", err)
		}

		// Convert Starlark dict to Go map
		params := make(map[string]any)
		if paramsDict != nil {
			for _, item := range paramsDict.Items() {
				key, ok := item[0].(starlark.String)
				if !ok {
					return nil, fmt.Errorf("%w: param key must be string, got %s", ErrInvokeHandlerBadType, item[0].Type())
				}
				params[string(key)] = starlarkToGo(item[1])
			}
		}

		// Generate idempotency key for this step
		starlarkCtx.IdempotencyKey = starlarkCtx.NextIdempotencyKey()

		// Call handler
		result, err := handler(starlarkCtx, params)
		duration := time.Since(stepStart)

		if err != nil {
			*stepResults = append(*stepResults, StepResult{
				StepName: handlerName,
				Success:  false,
				Error:    err.Error(),
				Duration: duration,
			})
			return nil, err
		}

		// Create step result with compensation metadata
		stepResult := StepResult{
			StepName: handlerName,
			Success:  true,
			Output:   result,
			Duration: duration,
		}

		// Add compensation handler if known
		// This is a backward-compatibility mapping for invoke_handler.
		// Typed service modules should define compensation in handler metadata instead.
		compensateHandler := getCompensationHandler(handlerName)
		if compensateHandler != "" {
			stepResult.CompensateHandler = compensateHandler
			stepResult.CompensateParams = deriveCompensationParams(stepResult)
		}

		*stepResults = append(*stepResults, stepResult)

		// Convert result to Starlark value
		return goToStarlark(result), nil
	})
}

// WithLogger returns a new runner with the given logger.
func (r *StarlarkSagaRunner) WithLogger(logger *slog.Logger) *StarlarkSagaRunner {
	if logger == nil {
		logger = slog.Default()
	}
	return &StarlarkSagaRunner{
		runtime:        r.runtime,
		registry:       r.registry,
		serviceModules: r.serviceModules,
		logger:         logger,
	}
}

// getCompensationHandler returns the compensation handler name for a given forward handler.
// This is a backward-compatibility mapping for invoke_handler API.
// Typed service modules should define compensation in handler metadata instead.
func getCompensationHandler(forwardHandler string) string {
	// Map forward handlers to their compensation handlers
	compensationMap := map[string]string{
		"payment_order.create_lien": "payment_order.terminate_lien",
		// payment_order.send_to_gateway has no compensation (idempotent gateway calls)
		// payment_order.post_ledger_entries has no compensation (immutable ledger)
		// payment_order.execute_lien has no compensation (final settlement)
	}

	return compensationMap[forwardHandler]
}

// deriveCompensationParams extracts relevant fields from a forward step's output
// to be used as input parameters for the compensation handler.
// It follows a simple heuristic: copy any fields ending in "_id" or named "id",
// as these typically identify resources created by the forward step that need
// to be cancelled/reverted by the compensation handler.
func deriveCompensationParams(forwardStep StepResult) map[string]any {
	params := make(map[string]any)

	// Check if output is a map
	output, ok := forwardStep.Output.(map[string]interface{})
	if !ok {
		return params
	}

	// Copy fields that look like IDs
	for key, value := range output {
		if key == "id" || len(key) > 3 && key[len(key)-3:] == "_id" {
			params[key] = value
		}
	}

	return params
}

// executeCompensation executes compensation handlers in LIFO (Last In, First Out) order
// for all completed saga steps. This implements the standard saga compensation pattern
// where the most recently completed step is compensated first, working backwards to
// the first step.
//
// Compensation is best-effort: if a compensation handler fails, the error is logged
// and returned, but execution continues to compensate remaining steps. This ensures
// maximum rollback coverage even in the presence of failures.
func (r *StarlarkSagaRunner) executeCompensation(ctx *StarlarkContext, completedSteps []StepResult) error {
	if len(completedSteps) == 0 {
		return nil
	}

	logger := r.logger.With(
		"saga_execution_id", ctx.SagaExecutionID.String(),
		"compensation_step_count", len(completedSteps),
	)

	logger.Info("starting compensation execution")

	var compensationErrors []error

	// Iterate in reverse order (LIFO)
	for i := len(completedSteps) - 1; i >= 0; i-- {
		step := completedSteps[i]

		// Skip steps without compensation handlers
		if step.CompensateHandler == "" {
			logger.Debug("skipping step without compensation handler", "step_name", step.StepName)
			continue
		}

		logger.Info("executing compensation",
			"step_name", step.StepName,
			"compensate_handler", step.CompensateHandler,
			"step_index", i,
		)

		// Look up compensation handler
		handler, err := r.registry.Get(step.CompensateHandler)
		if err != nil {
			logger.Error("compensation handler not found",
				"compensate_handler", step.CompensateHandler,
				"error", err,
			)
			compensationErrors = append(compensationErrors,
				fmt.Errorf("compensation handler %s not found for step %s: %w",
					step.CompensateHandler, step.StepName, err))
			continue
		}

		// Execute compensation handler
		_, err = handler(ctx, step.CompensateParams)
		if err != nil {
			logger.Error("compensation failed",
				"compensate_handler", step.CompensateHandler,
				"step_name", step.StepName,
				"error", err,
			)
			compensationErrors = append(compensationErrors,
				fmt.Errorf("compensation failed for %s (step %s): %w",
					step.CompensateHandler, step.StepName, err))
			continue
		}

		logger.Info("compensation succeeded",
			"compensate_handler", step.CompensateHandler,
			"step_name", step.StepName,
		)
	}

	if len(compensationErrors) > 0 {
		logger.Error("compensation completed with errors",
			"error_count", len(compensationErrors),
		)
		// Return first error for simplicity, but log all errors above
		return compensationErrors[0]
	}

	logger.Info("compensation execution completed successfully")
	return nil
}
