// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: meridian/mapping/v1/mapping.proto

package mappingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MappingService_CreateMapping_FullMethodName = "/meridian.mapping.v1.MappingService/CreateMapping"
	MappingService_GetMapping_FullMethodName    = "/meridian.mapping.v1.MappingService/GetMapping"
	MappingService_ListMappings_FullMethodName  = "/meridian.mapping.v1.MappingService/ListMappings"
	MappingService_UpdateMapping_FullMethodName = "/meridian.mapping.v1.MappingService/UpdateMapping"
	MappingService_DeleteMapping_FullMethodName = "/meridian.mapping.v1.MappingService/DeleteMapping"
	MappingService_DryRunMapping_FullMethodName = "/meridian.mapping.v1.MappingService/DryRunMapping"
)

// MappingServiceClient is the client API for MappingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MappingService manages mapping definitions - the configuration that describes
// how external JSON payloads are transformed into internal Meridian gRPC calls.
type MappingServiceClient interface {
	// CreateMapping creates a new mapping definition in DRAFT status.
	// Returns ALREADY_EXISTS if a mapping with the same name and version exists.
	CreateMapping(ctx context.Context, in *CreateMappingRequest, opts ...grpc.CallOption) (*CreateMappingResponse, error)
	// GetMapping retrieves a specific mapping definition by ID.
	// Returns NOT_FOUND if the mapping does not exist.
	GetMapping(ctx context.Context, in *GetMappingRequest, opts ...grpc.CallOption) (*GetMappingResponse, error)
	// ListMappings returns mapping definitions for the tenant, with optional filtering.
	ListMappings(ctx context.Context, in *ListMappingsRequest, opts ...grpc.CallOption) (*ListMappingsResponse, error)
	// UpdateMapping modifies an existing mapping definition.
	// Returns NOT_FOUND if the mapping does not exist.
	// Returns FAILED_PRECONDITION if the mapping is not in DRAFT status.
	UpdateMapping(ctx context.Context, in *UpdateMappingRequest, opts ...grpc.CallOption) (*UpdateMappingResponse, error)
	// DeleteMapping removes a mapping definition.
	// Returns NOT_FOUND if the mapping does not exist.
	// Returns FAILED_PRECONDITION if the mapping is in ACTIVE status.
	DeleteMapping(ctx context.Context, in *DeleteMappingRequest, opts ...grpc.CallOption) (*DeleteMappingResponse, error)
	// DryRunMapping executes a mapping against sample JSON without persisting any results.
	// Used for testing and validating a mapping definition before live deployment.
	// Returns NOT_FOUND if the mapping name does not resolve to an ACTIVE definition
	// and no explicit version resolves to an existing definition.
	DryRunMapping(ctx context.Context, in *DryRunMappingRequest, opts ...grpc.CallOption) (*DryRunMappingResponse, error)
}

type mappingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMappingServiceClient(cc grpc.ClientConnInterface) MappingServiceClient {
	return &mappingServiceClient{cc}
}

func (c *mappingServiceClient) CreateMapping(ctx context.Context, in *CreateMappingRequest, opts ...grpc.CallOption) (*CreateMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMappingResponse)
	err := c.cc.Invoke(ctx, MappingService_CreateMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mappingServiceClient) GetMapping(ctx context.Context, in *GetMappingRequest, opts ...grpc.CallOption) (*GetMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMappingResponse)
	err := c.cc.Invoke(ctx, MappingService_GetMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mappingServiceClient) ListMappings(ctx context.Context, in *ListMappingsRequest, opts ...grpc.CallOption) (*ListMappingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMappingsResponse)
	err := c.cc.Invoke(ctx, MappingService_ListMappings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mappingServiceClient) UpdateMapping(ctx context.Context, in *UpdateMappingRequest, opts ...grpc.CallOption) (*UpdateMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMappingResponse)
	err := c.cc.Invoke(ctx, MappingService_UpdateMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mappingServiceClient) DeleteMapping(ctx context.Context, in *DeleteMappingRequest, opts ...grpc.CallOption) (*DeleteMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMappingResponse)
	err := c.cc.Invoke(ctx, MappingService_DeleteMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mappingServiceClient) DryRunMapping(ctx context.Context, in *DryRunMappingRequest, opts ...grpc.CallOption) (*DryRunMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DryRunMappingResponse)
	err := c.cc.Invoke(ctx, MappingService_DryRunMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MappingServiceServer is the server API for MappingService service.
// All implementations must embed UnimplementedMappingServiceServer
// for forward compatibility.
//
// MappingService manages mapping definitions - the configuration that describes
// how external JSON payloads are transformed into internal Meridian gRPC calls.
type MappingServiceServer interface {
	// CreateMapping creates a new mapping definition in DRAFT status.
	// Returns ALREADY_EXISTS if a mapping with the same name and version exists.
	CreateMapping(context.Context, *CreateMappingRequest) (*CreateMappingResponse, error)
	// GetMapping retrieves a specific mapping definition by ID.
	// Returns NOT_FOUND if the mapping does not exist.
	GetMapping(context.Context, *GetMappingRequest) (*GetMappingResponse, error)
	// ListMappings returns mapping definitions for the tenant, with optional filtering.
	ListMappings(context.Context, *ListMappingsRequest) (*ListMappingsResponse, error)
	// UpdateMapping modifies an existing mapping definition.
	// Returns NOT_FOUND if the mapping does not exist.
	// Returns FAILED_PRECONDITION if the mapping is not in DRAFT status.
	UpdateMapping(context.Context, *UpdateMappingRequest) (*UpdateMappingResponse, error)
	// DeleteMapping removes a mapping definition.
	// Returns NOT_FOUND if the mapping does not exist.
	// Returns FAILED_PRECONDITION if the mapping is in ACTIVE status.
	DeleteMapping(context.Context, *DeleteMappingRequest) (*DeleteMappingResponse, error)
	// DryRunMapping executes a mapping against sample JSON without persisting any results.
	// Used for testing and validating a mapping definition before live deployment.
	// Returns NOT_FOUND if the mapping name does not resolve to an ACTIVE definition
	// and no explicit version resolves to an existing definition.
	DryRunMapping(context.Context, *DryRunMappingRequest) (*DryRunMappingResponse, error)
	mustEmbedUnimplementedMappingServiceServer()
}

// UnimplementedMappingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMappingServiceServer struct{}

func (UnimplementedMappingServiceServer) CreateMapping(context.Context, *CreateMappingRequest) (*CreateMappingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMapping not implemented")
}
func (UnimplementedMappingServiceServer) GetMapping(context.Context, *GetMappingRequest) (*GetMappingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMapping not implemented")
}
func (UnimplementedMappingServiceServer) ListMappings(context.Context, *ListMappingsRequest) (*ListMappingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMappings not implemented")
}
func (UnimplementedMappingServiceServer) UpdateMapping(context.Context, *UpdateMappingRequest) (*UpdateMappingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMapping not implemented")
}
func (UnimplementedMappingServiceServer) DeleteMapping(context.Context, *DeleteMappingRequest) (*DeleteMappingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMapping not implemented")
}
func (UnimplementedMappingServiceServer) DryRunMapping(context.Context, *DryRunMappingRequest) (*DryRunMappingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DryRunMapping not implemented")
}
func (UnimplementedMappingServiceServer) mustEmbedUnimplementedMappingServiceServer() {}
func (UnimplementedMappingServiceServer) testEmbeddedByValue()                        {}

// UnsafeMappingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MappingServiceServer will
// result in compilation errors.
type UnsafeMappingServiceServer interface {
	mustEmbedUnimplementedMappingServiceServer()
}

func RegisterMappingServiceServer(s grpc.ServiceRegistrar, srv MappingServiceServer) {
	// If the following call pancis, it indicates UnimplementedMappingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MappingService_ServiceDesc, srv)
}

func _MappingService_CreateMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MappingServiceServer).CreateMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MappingService_CreateMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MappingServiceServer).CreateMapping(ctx, req.(*CreateMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MappingService_GetMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MappingServiceServer).GetMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MappingService_GetMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MappingServiceServer).GetMapping(ctx, req.(*GetMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MappingService_ListMappings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMappingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MappingServiceServer).ListMappings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MappingService_ListMappings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MappingServiceServer).ListMappings(ctx, req.(*ListMappingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MappingService_UpdateMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MappingServiceServer).UpdateMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MappingService_UpdateMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MappingServiceServer).UpdateMapping(ctx, req.(*UpdateMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MappingService_DeleteMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MappingServiceServer).DeleteMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MappingService_DeleteMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MappingServiceServer).DeleteMapping(ctx, req.(*DeleteMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MappingService_DryRunMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DryRunMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MappingServiceServer).DryRunMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MappingService_DryRunMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MappingServiceServer).DryRunMapping(ctx, req.(*DryRunMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MappingService_ServiceDesc is the grpc.ServiceDesc for MappingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MappingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meridian.mapping.v1.MappingService",
	HandlerType: (*MappingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMapping",
			Handler:    _MappingService_CreateMapping_Handler,
		},
		{
			MethodName: "GetMapping",
			Handler:    _MappingService_GetMapping_Handler,
		},
		{
			MethodName: "ListMappings",
			Handler:    _MappingService_ListMappings_Handler,
		},
		{
			MethodName: "UpdateMapping",
			Handler:    _MappingService_UpdateMapping_Handler,
		},
		{
			MethodName: "DeleteMapping",
			Handler:    _MappingService_DeleteMapping_Handler,
		},
		{
			MethodName: "DryRunMapping",
			Handler:    _MappingService_DryRunMapping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meridian/mapping/v1/mapping.proto",
}
