// Package domain contains core domain logic for position keeping.
package domain

import (
	"time"

	"github.com/google/uuid"
	commonv1 "github.com/meridianhub/meridian/api/proto/meridian/common/v1"
	eventsv1 "github.com/meridianhub/meridian/api/proto/meridian/events/v1"
	quantityv1 "github.com/meridianhub/meridian/api/proto/meridian/quantity/v1"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// DomainEvent represents an event that occurred in the position keeping domain.
// This interface allows collection and publishing of events generated by aggregate roots.
//
//nolint:revive // DomainEvent is the standard DDD pattern name for domain events
type DomainEvent interface {
	// EventType returns the type identifier for this event
	EventType() string
	// AggregateID returns the ID of the aggregate that produced this event
	AggregateID() string
	// OccurredAt returns when the event occurred
	OccurredAt() time.Time
	// ToProto converts the domain event to its protobuf representation for publishing
	ToProto() interface{}
}

// TransactionCaptured represents a domain event when a transaction is first captured.
type TransactionCaptured struct {
	LogID         uuid.UUID
	AccountID     string
	TransactionID uuid.UUID
	Amount        Money
	Direction     PostingDirection
	Source        TransactionSource
	Description   string
	Reference     string
	CorrelationID string
	Timestamp     time.Time
	Version       int64
}

// EventType returns the event type identifier.
func (e *TransactionCaptured) EventType() string {
	return "position_keeping.transaction_captured.v1"
}

// AggregateID returns the log ID as the aggregate identifier.
func (e *TransactionCaptured) AggregateID() string {
	return e.LogID.String()
}

// OccurredAt returns when the event occurred.
func (e *TransactionCaptured) OccurredAt() time.Time {
	return e.Timestamp
}

// ToProto converts to protobuf representation.
func (e *TransactionCaptured) ToProto() interface{} {
	// Convert decimal amount to minor units (cents, pence, sen, etc.)
	// This is currency-aware: JPY has 0 decimal places, others have 2
	// Using MoneyToMinorUnitsUnchecked since event amounts should be validated before this point
	amountCents := MoneyToMinorUnitsUnchecked(e.Amount)

	return &eventsv1.TransactionCapturedEvent{
		LogId:          e.LogID.String(),
		AccountId:      e.AccountID,
		TransactionId:  e.TransactionID.String(),
		AmountCents:    amountCents,
		InstrumentCode: string(MoneyCurrency(e.Amount)),
		Direction:      e.Direction.String(),
		Source:         e.Source.String(),
		Description:    e.Description,
		Reference:      e.Reference,
		CorrelationId:  e.CorrelationID,
		Timestamp:      timestamppb.New(e.Timestamp),
		Version:        e.Version,
		// Universal Asset System: InstrumentAmount provides full multi-asset support
		// while legacy fields (amount_cents, currency) are maintained for backward compatibility
		InstrumentAmount: moneyToInstrumentAmountProto(e.Amount),
	}
}

// TransactionAmended represents a domain event when a transaction is amended.
type TransactionAmended struct {
	LogID         uuid.UUID
	AccountID     string
	Reason        string
	AmendedBy     string
	CorrelationID string
	Timestamp     time.Time
	Version       int64
}

// EventType returns the event type identifier.
func (e *TransactionAmended) EventType() string {
	return "position_keeping.transaction_amended.v1"
}

// AggregateID returns the log ID as the aggregate identifier.
func (e *TransactionAmended) AggregateID() string {
	return e.LogID.String()
}

// OccurredAt returns when the event occurred.
func (e *TransactionAmended) OccurredAt() time.Time {
	return e.Timestamp
}

// ToProto converts to protobuf representation.
func (e *TransactionAmended) ToProto() interface{} {
	return &eventsv1.TransactionAmendedEvent{
		LogId:         e.LogID.String(),
		AccountId:     e.AccountID,
		Reason:        e.Reason,
		AmendedBy:     e.AmendedBy,
		CorrelationId: e.CorrelationID,
		Timestamp:     timestamppb.New(e.Timestamp),
		Version:       e.Version,
	}
}

// TransactionReconciled represents a domain event when a transaction is reconciled.
type TransactionReconciled struct {
	LogID                uuid.UUID
	AccountID            string
	ReconciliationStatus ReconciliationStatus
	Reason               string
	ReconciledBy         string
	CorrelationID        string
	Timestamp            time.Time
	Version              int64
}

// EventType returns the event type identifier.
func (e *TransactionReconciled) EventType() string {
	return "position_keeping.transaction_reconciled.v1"
}

// AggregateID returns the log ID as the aggregate identifier.
func (e *TransactionReconciled) AggregateID() string {
	return e.LogID.String()
}

// OccurredAt returns when the event occurred.
func (e *TransactionReconciled) OccurredAt() time.Time {
	return e.Timestamp
}

// ToProto converts to protobuf representation.
func (e *TransactionReconciled) ToProto() interface{} {
	return &eventsv1.TransactionReconciledEvent{
		LogId:                e.LogID.String(),
		AccountId:            e.AccountID,
		ReconciliationStatus: reconciliationStatusToString(e.ReconciliationStatus),
		Reason:               e.Reason,
		ReconciledBy:         e.ReconciledBy,
		CorrelationId:        e.CorrelationID,
		Timestamp:            timestamppb.New(e.Timestamp),
		Version:              e.Version,
	}
}

// TransactionPosted represents a domain event when a transaction is posted to the ledger.
type TransactionPosted struct {
	LogID            uuid.UUID
	AccountID        string
	PostingReference string
	Reason           string
	PostedBy         string
	CorrelationID    string
	Timestamp        time.Time
	Version          int64
}

// EventType returns the event type identifier.
func (e *TransactionPosted) EventType() string {
	return "position_keeping.transaction_posted.v1"
}

// AggregateID returns the log ID as the aggregate identifier.
func (e *TransactionPosted) AggregateID() string {
	return e.LogID.String()
}

// OccurredAt returns when the event occurred.
func (e *TransactionPosted) OccurredAt() time.Time {
	return e.Timestamp
}

// ToProto converts to protobuf representation.
func (e *TransactionPosted) ToProto() interface{} {
	return &eventsv1.TransactionPostedEvent{
		LogId:            e.LogID.String(),
		AccountId:        e.AccountID,
		PostingReference: e.PostingReference,
		Reason:           e.Reason,
		PostedBy:         e.PostedBy,
		CorrelationId:    e.CorrelationID,
		Timestamp:        timestamppb.New(e.Timestamp),
		Version:          e.Version,
	}
}

// TransactionRejected represents a domain event when a transaction is rejected.
type TransactionRejected struct {
	LogID         uuid.UUID
	AccountID     string
	Reason        string
	RejectedBy    string
	CorrelationID string
	Timestamp     time.Time
	Version       int64
}

// EventType returns the event type identifier.
func (e *TransactionRejected) EventType() string {
	return "position_keeping.transaction_rejected.v1"
}

// AggregateID returns the log ID as the aggregate identifier.
func (e *TransactionRejected) AggregateID() string {
	return e.LogID.String()
}

// OccurredAt returns when the event occurred.
func (e *TransactionRejected) OccurredAt() time.Time {
	return e.Timestamp
}

// ToProto converts to protobuf representation.
func (e *TransactionRejected) ToProto() interface{} {
	return &eventsv1.TransactionRejectedEvent{
		LogId:         e.LogID.String(),
		AccountId:     e.AccountID,
		Reason:        e.Reason,
		RejectedBy:    e.RejectedBy,
		CorrelationId: e.CorrelationID,
		Timestamp:     timestamppb.New(e.Timestamp),
		Version:       e.Version,
	}
}

// TransactionFailed represents a domain event when a transaction fails.
type TransactionFailed struct {
	LogID         uuid.UUID
	AccountID     string
	FailureReason string
	ErrorCode     commonv1.ErrorCode
	CorrelationID string
	Timestamp     time.Time
	Version       int64
}

// EventType returns the event type identifier.
func (e *TransactionFailed) EventType() string {
	return "position_keeping.transaction_failed.v1"
}

// AggregateID returns the log ID as the aggregate identifier.
func (e *TransactionFailed) AggregateID() string {
	return e.LogID.String()
}

// OccurredAt returns when the event occurred.
func (e *TransactionFailed) OccurredAt() time.Time {
	return e.Timestamp
}

// ToProto converts to protobuf representation.
func (e *TransactionFailed) ToProto() interface{} {
	return &eventsv1.TransactionFailedEvent{
		LogId:         e.LogID.String(),
		AccountId:     e.AccountID,
		FailureReason: e.FailureReason,
		ErrorCodeEnum: e.ErrorCode,
		CorrelationId: e.CorrelationID,
		Timestamp:     timestamppb.New(e.Timestamp),
		Version:       e.Version,
	}
}

// TransactionCancelled represents a domain event when a transaction is cancelled.
type TransactionCancelled struct {
	LogID         uuid.UUID
	AccountID     string
	Reason        string
	CancelledBy   string
	CorrelationID string
	Timestamp     time.Time
	Version       int64
}

// EventType returns the event type identifier.
func (e *TransactionCancelled) EventType() string {
	return "position_keeping.transaction_cancelled.v1"
}

// AggregateID returns the log ID as the aggregate identifier.
func (e *TransactionCancelled) AggregateID() string {
	return e.LogID.String()
}

// OccurredAt returns when the event occurred.
func (e *TransactionCancelled) OccurredAt() time.Time {
	return e.Timestamp
}

// ToProto converts to protobuf representation.
func (e *TransactionCancelled) ToProto() interface{} {
	return &eventsv1.TransactionCancelledEvent{
		LogId:         e.LogID.String(),
		AccountId:     e.AccountID,
		Reason:        e.Reason,
		CancelledBy:   e.CancelledBy,
		CorrelationId: e.CorrelationID,
		Timestamp:     timestamppb.New(e.Timestamp),
		Version:       e.Version,
	}
}

// OpeningBalanceRecorded represents a domain event when an opening balance is recorded
// during account migration from a legacy system.
type OpeningBalanceRecorded struct {
	LogID              uuid.UUID
	AccountID          string
	OpeningBalance     Money
	EffectiveDate      time.Time
	MigrationReference string
	CorrelationID      string
	Timestamp          time.Time
	Version            int64
}

// EventType returns the event type identifier.
func (e *OpeningBalanceRecorded) EventType() string {
	return "position_keeping.opening_balance_recorded.v1"
}

// AggregateID returns the log ID as the aggregate identifier.
func (e *OpeningBalanceRecorded) AggregateID() string {
	return e.LogID.String()
}

// OccurredAt returns when the event occurred.
func (e *OpeningBalanceRecorded) OccurredAt() time.Time {
	return e.Timestamp
}

// ToProto converts to protobuf representation.
func (e *OpeningBalanceRecorded) ToProto() interface{} {
	// Convert decimal amount to minor units (cents, pence, sen, etc.)
	// This supports negative amounts for overdrawn accounts
	amountCents := MoneyToMinorUnitsUnchecked(e.OpeningBalance)

	return &eventsv1.OpeningBalanceRecordedEvent{
		LogId:              e.LogID.String(),
		AccountId:          e.AccountID,
		AmountCents:        amountCents,
		InstrumentCode:     string(MoneyCurrency(e.OpeningBalance)),
		EffectiveDate:      timestamppb.New(e.EffectiveDate),
		MigrationReference: e.MigrationReference,
		CorrelationId:      e.CorrelationID,
		Timestamp:          timestamppb.New(e.Timestamp),
		Version:            e.Version,
		InstrumentAmount:   moneyToInstrumentAmountProto(e.OpeningBalance),
	}
}

// BulkTransactionCaptured represents a domain event for bulk transaction captures.
// Used when multiple transactions are captured in a single batch operation (e.g., file import).
//
// Batch Size Limits:
//   - Minimum: 1 transaction (validated by protobuf: min_items=1)
//   - Maximum: 10,000 transactions (validated by protobuf: max_items=10000)
//   - Recommended: 100-1000 transactions per batch for optimal performance
//
// For batches exceeding 10,000 transactions, split into multiple BulkTransactionCaptured
// events. Use the same CorrelationID across split batches to link them together.
//
// Memory Considerations:
//   - Each UUID in LogIDs is 16 bytes
//   - Max batch (10,000 UUIDs) ≈ 156KB of UUIDs alone
//   - Keep batch sizes reasonable to avoid memory pressure
type BulkTransactionCaptured struct {
	BatchID          uuid.UUID         // Unique identifier for this bulk operation
	TransactionCount int32             // Number of transactions in this batch
	LogIDs           []uuid.UUID       // Position log IDs created (1-10,000 items)
	Source           TransactionSource // Origin of bulk operation (e.g., IMPORTED)
	CorrelationID    string            // Links related batches across services
	Timestamp        time.Time         // When the bulk capture occurred
	Version          int64             // Aggregate version for optimistic locking
}

// EventType returns the event type identifier.
func (e *BulkTransactionCaptured) EventType() string {
	return "position_keeping.bulk_transaction_captured.v1"
}

// AggregateID returns the batch ID as the aggregate identifier.
func (e *BulkTransactionCaptured) AggregateID() string {
	return e.BatchID.String()
}

// OccurredAt returns when the event occurred.
func (e *BulkTransactionCaptured) OccurredAt() time.Time {
	return e.Timestamp
}

// ToProto converts to protobuf representation.
func (e *BulkTransactionCaptured) ToProto() interface{} {
	logIDs := make([]string, len(e.LogIDs))
	for i, id := range e.LogIDs {
		logIDs[i] = id.String()
	}

	return &eventsv1.BulkTransactionCapturedEvent{
		BatchId:          e.BatchID.String(),
		TransactionCount: e.TransactionCount,
		LogIds:           logIDs,
		Source:           e.Source.String(),
		CorrelationId:    e.CorrelationID,
		Timestamp:        timestamppb.New(e.Timestamp),
		Version:          e.Version,
	}
}

// Helper functions for conversions

func reconciliationStatusToString(status ReconciliationStatus) string {
	switch status {
	case ReconciliationStatusMatched:
		return "auto_reconciled"
	case ReconciliationStatusResolved:
		return "manually_reconciled"
	case ReconciliationStatusMismatched:
		return "reconciled_with_discrepancy"
	case ReconciliationStatusUnreconciled:
		return "unreconciled"
	default:
		return "unreconciled"
	}
}

// moneyToInstrumentAmountProto converts a domain Money quantity to a protobuf InstrumentAmount.
// This supports the Universal Asset System by providing full instrument metadata in events.
func moneyToInstrumentAmountProto(m Money) *quantityv1.InstrumentAmount {
	return &quantityv1.InstrumentAmount{
		Amount:         m.Amount.String(),
		InstrumentCode: m.Instrument.Code,
		Version:        int32(m.Instrument.Version),
		// Note: Attributes, ValidFrom, ValidTo, and Source are optional and not set for simple Money
		// These can be populated when the domain model supports them (e.g., for time-bound assets)
	}
}
