// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: meridian/reference_data/v1/instrument.proto

package referencedatav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReferenceDataService_RegisterInstrument_FullMethodName  = "/meridian.reference_data.v1.ReferenceDataService/RegisterInstrument"
	ReferenceDataService_UpdateInstrument_FullMethodName    = "/meridian.reference_data.v1.ReferenceDataService/UpdateInstrument"
	ReferenceDataService_RetrieveInstrument_FullMethodName  = "/meridian.reference_data.v1.ReferenceDataService/RetrieveInstrument"
	ReferenceDataService_ListInstruments_FullMethodName     = "/meridian.reference_data.v1.ReferenceDataService/ListInstruments"
	ReferenceDataService_ActivateInstrument_FullMethodName  = "/meridian.reference_data.v1.ReferenceDataService/ActivateInstrument"
	ReferenceDataService_DeprecateInstrument_FullMethodName = "/meridian.reference_data.v1.ReferenceDataService/DeprecateInstrument"
	ReferenceDataService_EvaluateInstrument_FullMethodName  = "/meridian.reference_data.v1.ReferenceDataService/EvaluateInstrument"
	ReferenceDataService_GetAttributeSchema_FullMethodName  = "/meridian.reference_data.v1.ReferenceDataService/GetAttributeSchema"
)

// ReferenceDataServiceClient is the client API for ReferenceDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ReferenceDataService manages instrument definitions - the reference data
// that describes how different asset types (currencies, energy, compute, etc.)
// are validated and pooled.
type ReferenceDataServiceClient interface {
	// RegisterInstrument creates a new instrument definition in DRAFT status.
	// Returns ALREADY_EXISTS if code+version exists.
	// Returns INVALID_ARGUMENT if CEL expressions fail compilation.
	RegisterInstrument(ctx context.Context, in *RegisterInstrumentRequest, opts ...grpc.CallOption) (*RegisterInstrumentResponse, error)
	// UpdateInstrument modifies a DRAFT instrument definition.
	// Returns NOT_FOUND if instrument doesn't exist.
	// Returns PERMISSION_DENIED if instrument is a system instrument.
	// Returns FAILED_PRECONDITION if not in DRAFT status.
	UpdateInstrument(ctx context.Context, in *UpdateInstrumentRequest, opts ...grpc.CallOption) (*UpdateInstrumentResponse, error)
	// RetrieveInstrument fetches a specific instrument by code and version.
	// Returns NOT_FOUND if instrument doesn't exist.
	RetrieveInstrument(ctx context.Context, in *RetrieveInstrumentRequest, opts ...grpc.CallOption) (*RetrieveInstrumentResponse, error)
	// ListInstruments returns instruments matching the filter criteria.
	// Supports filtering by status and pagination.
	ListInstruments(ctx context.Context, in *ListInstrumentsRequest, opts ...grpc.CallOption) (*ListInstrumentsResponse, error)
	// ActivateInstrument transitions an instrument from DRAFT to ACTIVE.
	// Returns PERMISSION_DENIED if instrument is a system instrument.
	// Returns FAILED_PRECONDITION if not in DRAFT status.
	ActivateInstrument(ctx context.Context, in *ActivateInstrumentRequest, opts ...grpc.CallOption) (*ActivateInstrumentResponse, error)
	// DeprecateInstrument transitions an instrument from ACTIVE to DEPRECATED.
	// Returns PERMISSION_DENIED if instrument is a system instrument.
	// Returns FAILED_PRECONDITION if not in ACTIVE status.
	DeprecateInstrument(ctx context.Context, in *DeprecateInstrumentRequest, opts ...grpc.CallOption) (*DeprecateInstrumentResponse, error)
	// EvaluateInstrument is a CEL playground endpoint for testing expressions.
	// Compiles and evaluates CEL expressions without persisting anything.
	// Returns compilation errors or evaluation results.
	EvaluateInstrument(ctx context.Context, in *EvaluateInstrumentRequest, opts ...grpc.CallOption) (*EvaluateInstrumentResponse, error)
	// GetAttributeSchema returns the JSON Schema describing valid attributes
	// for client discovery and form generation.
	GetAttributeSchema(ctx context.Context, in *GetAttributeSchemaRequest, opts ...grpc.CallOption) (*GetAttributeSchemaResponse, error)
}

type referenceDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReferenceDataServiceClient(cc grpc.ClientConnInterface) ReferenceDataServiceClient {
	return &referenceDataServiceClient{cc}
}

func (c *referenceDataServiceClient) RegisterInstrument(ctx context.Context, in *RegisterInstrumentRequest, opts ...grpc.CallOption) (*RegisterInstrumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterInstrumentResponse)
	err := c.cc.Invoke(ctx, ReferenceDataService_RegisterInstrument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referenceDataServiceClient) UpdateInstrument(ctx context.Context, in *UpdateInstrumentRequest, opts ...grpc.CallOption) (*UpdateInstrumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInstrumentResponse)
	err := c.cc.Invoke(ctx, ReferenceDataService_UpdateInstrument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referenceDataServiceClient) RetrieveInstrument(ctx context.Context, in *RetrieveInstrumentRequest, opts ...grpc.CallOption) (*RetrieveInstrumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveInstrumentResponse)
	err := c.cc.Invoke(ctx, ReferenceDataService_RetrieveInstrument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referenceDataServiceClient) ListInstruments(ctx context.Context, in *ListInstrumentsRequest, opts ...grpc.CallOption) (*ListInstrumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstrumentsResponse)
	err := c.cc.Invoke(ctx, ReferenceDataService_ListInstruments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referenceDataServiceClient) ActivateInstrument(ctx context.Context, in *ActivateInstrumentRequest, opts ...grpc.CallOption) (*ActivateInstrumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateInstrumentResponse)
	err := c.cc.Invoke(ctx, ReferenceDataService_ActivateInstrument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referenceDataServiceClient) DeprecateInstrument(ctx context.Context, in *DeprecateInstrumentRequest, opts ...grpc.CallOption) (*DeprecateInstrumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeprecateInstrumentResponse)
	err := c.cc.Invoke(ctx, ReferenceDataService_DeprecateInstrument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referenceDataServiceClient) EvaluateInstrument(ctx context.Context, in *EvaluateInstrumentRequest, opts ...grpc.CallOption) (*EvaluateInstrumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateInstrumentResponse)
	err := c.cc.Invoke(ctx, ReferenceDataService_EvaluateInstrument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referenceDataServiceClient) GetAttributeSchema(ctx context.Context, in *GetAttributeSchemaRequest, opts ...grpc.CallOption) (*GetAttributeSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttributeSchemaResponse)
	err := c.cc.Invoke(ctx, ReferenceDataService_GetAttributeSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReferenceDataServiceServer is the server API for ReferenceDataService service.
// All implementations must embed UnimplementedReferenceDataServiceServer
// for forward compatibility.
//
// ReferenceDataService manages instrument definitions - the reference data
// that describes how different asset types (currencies, energy, compute, etc.)
// are validated and pooled.
type ReferenceDataServiceServer interface {
	// RegisterInstrument creates a new instrument definition in DRAFT status.
	// Returns ALREADY_EXISTS if code+version exists.
	// Returns INVALID_ARGUMENT if CEL expressions fail compilation.
	RegisterInstrument(context.Context, *RegisterInstrumentRequest) (*RegisterInstrumentResponse, error)
	// UpdateInstrument modifies a DRAFT instrument definition.
	// Returns NOT_FOUND if instrument doesn't exist.
	// Returns PERMISSION_DENIED if instrument is a system instrument.
	// Returns FAILED_PRECONDITION if not in DRAFT status.
	UpdateInstrument(context.Context, *UpdateInstrumentRequest) (*UpdateInstrumentResponse, error)
	// RetrieveInstrument fetches a specific instrument by code and version.
	// Returns NOT_FOUND if instrument doesn't exist.
	RetrieveInstrument(context.Context, *RetrieveInstrumentRequest) (*RetrieveInstrumentResponse, error)
	// ListInstruments returns instruments matching the filter criteria.
	// Supports filtering by status and pagination.
	ListInstruments(context.Context, *ListInstrumentsRequest) (*ListInstrumentsResponse, error)
	// ActivateInstrument transitions an instrument from DRAFT to ACTIVE.
	// Returns PERMISSION_DENIED if instrument is a system instrument.
	// Returns FAILED_PRECONDITION if not in DRAFT status.
	ActivateInstrument(context.Context, *ActivateInstrumentRequest) (*ActivateInstrumentResponse, error)
	// DeprecateInstrument transitions an instrument from ACTIVE to DEPRECATED.
	// Returns PERMISSION_DENIED if instrument is a system instrument.
	// Returns FAILED_PRECONDITION if not in ACTIVE status.
	DeprecateInstrument(context.Context, *DeprecateInstrumentRequest) (*DeprecateInstrumentResponse, error)
	// EvaluateInstrument is a CEL playground endpoint for testing expressions.
	// Compiles and evaluates CEL expressions without persisting anything.
	// Returns compilation errors or evaluation results.
	EvaluateInstrument(context.Context, *EvaluateInstrumentRequest) (*EvaluateInstrumentResponse, error)
	// GetAttributeSchema returns the JSON Schema describing valid attributes
	// for client discovery and form generation.
	GetAttributeSchema(context.Context, *GetAttributeSchemaRequest) (*GetAttributeSchemaResponse, error)
	mustEmbedUnimplementedReferenceDataServiceServer()
}

// UnimplementedReferenceDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReferenceDataServiceServer struct{}

func (UnimplementedReferenceDataServiceServer) RegisterInstrument(context.Context, *RegisterInstrumentRequest) (*RegisterInstrumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterInstrument not implemented")
}
func (UnimplementedReferenceDataServiceServer) UpdateInstrument(context.Context, *UpdateInstrumentRequest) (*UpdateInstrumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInstrument not implemented")
}
func (UnimplementedReferenceDataServiceServer) RetrieveInstrument(context.Context, *RetrieveInstrumentRequest) (*RetrieveInstrumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveInstrument not implemented")
}
func (UnimplementedReferenceDataServiceServer) ListInstruments(context.Context, *ListInstrumentsRequest) (*ListInstrumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInstruments not implemented")
}
func (UnimplementedReferenceDataServiceServer) ActivateInstrument(context.Context, *ActivateInstrumentRequest) (*ActivateInstrumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateInstrument not implemented")
}
func (UnimplementedReferenceDataServiceServer) DeprecateInstrument(context.Context, *DeprecateInstrumentRequest) (*DeprecateInstrumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeprecateInstrument not implemented")
}
func (UnimplementedReferenceDataServiceServer) EvaluateInstrument(context.Context, *EvaluateInstrumentRequest) (*EvaluateInstrumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateInstrument not implemented")
}
func (UnimplementedReferenceDataServiceServer) GetAttributeSchema(context.Context, *GetAttributeSchemaRequest) (*GetAttributeSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttributeSchema not implemented")
}
func (UnimplementedReferenceDataServiceServer) mustEmbedUnimplementedReferenceDataServiceServer() {}
func (UnimplementedReferenceDataServiceServer) testEmbeddedByValue()                              {}

// UnsafeReferenceDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReferenceDataServiceServer will
// result in compilation errors.
type UnsafeReferenceDataServiceServer interface {
	mustEmbedUnimplementedReferenceDataServiceServer()
}

func RegisterReferenceDataServiceServer(s grpc.ServiceRegistrar, srv ReferenceDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedReferenceDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReferenceDataService_ServiceDesc, srv)
}

func _ReferenceDataService_RegisterInstrument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterInstrumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferenceDataServiceServer).RegisterInstrument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReferenceDataService_RegisterInstrument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferenceDataServiceServer).RegisterInstrument(ctx, req.(*RegisterInstrumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReferenceDataService_UpdateInstrument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInstrumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferenceDataServiceServer).UpdateInstrument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReferenceDataService_UpdateInstrument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferenceDataServiceServer).UpdateInstrument(ctx, req.(*UpdateInstrumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReferenceDataService_RetrieveInstrument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveInstrumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferenceDataServiceServer).RetrieveInstrument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReferenceDataService_RetrieveInstrument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferenceDataServiceServer).RetrieveInstrument(ctx, req.(*RetrieveInstrumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReferenceDataService_ListInstruments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstrumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferenceDataServiceServer).ListInstruments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReferenceDataService_ListInstruments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferenceDataServiceServer).ListInstruments(ctx, req.(*ListInstrumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReferenceDataService_ActivateInstrument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateInstrumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferenceDataServiceServer).ActivateInstrument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReferenceDataService_ActivateInstrument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferenceDataServiceServer).ActivateInstrument(ctx, req.(*ActivateInstrumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReferenceDataService_DeprecateInstrument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeprecateInstrumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferenceDataServiceServer).DeprecateInstrument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReferenceDataService_DeprecateInstrument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferenceDataServiceServer).DeprecateInstrument(ctx, req.(*DeprecateInstrumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReferenceDataService_EvaluateInstrument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateInstrumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferenceDataServiceServer).EvaluateInstrument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReferenceDataService_EvaluateInstrument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferenceDataServiceServer).EvaluateInstrument(ctx, req.(*EvaluateInstrumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReferenceDataService_GetAttributeSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttributeSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferenceDataServiceServer).GetAttributeSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReferenceDataService_GetAttributeSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferenceDataServiceServer).GetAttributeSchema(ctx, req.(*GetAttributeSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReferenceDataService_ServiceDesc is the grpc.ServiceDesc for ReferenceDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReferenceDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meridian.reference_data.v1.ReferenceDataService",
	HandlerType: (*ReferenceDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterInstrument",
			Handler:    _ReferenceDataService_RegisterInstrument_Handler,
		},
		{
			MethodName: "UpdateInstrument",
			Handler:    _ReferenceDataService_UpdateInstrument_Handler,
		},
		{
			MethodName: "RetrieveInstrument",
			Handler:    _ReferenceDataService_RetrieveInstrument_Handler,
		},
		{
			MethodName: "ListInstruments",
			Handler:    _ReferenceDataService_ListInstruments_Handler,
		},
		{
			MethodName: "ActivateInstrument",
			Handler:    _ReferenceDataService_ActivateInstrument_Handler,
		},
		{
			MethodName: "DeprecateInstrument",
			Handler:    _ReferenceDataService_DeprecateInstrument_Handler,
		},
		{
			MethodName: "EvaluateInstrument",
			Handler:    _ReferenceDataService_EvaluateInstrument_Handler,
		},
		{
			MethodName: "GetAttributeSchema",
			Handler:    _ReferenceDataService_GetAttributeSchema_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meridian/reference_data/v1/instrument.proto",
}
