// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: meridian/reference_data/v1/node.proto

package referencedatav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_CreateNode_FullMethodName     = "/meridian.reference_data.v1.NodeService/CreateNode"
	NodeService_UpdateNode_FullMethodName     = "/meridian.reference_data.v1.NodeService/UpdateNode"
	NodeService_GetNode_FullMethodName        = "/meridian.reference_data.v1.NodeService/GetNode"
	NodeService_GetChildren_FullMethodName    = "/meridian.reference_data.v1.NodeService/GetChildren"
	NodeService_GetAncestors_FullMethodName   = "/meridian.reference_data.v1.NodeService/GetAncestors"
	NodeService_GetSubtree_FullMethodName     = "/meridian.reference_data.v1.NodeService/GetSubtree"
	NodeService_GetNodeAsAt_FullMethodName    = "/meridian.reference_data.v1.NodeService/GetNodeAsAt"
	NodeService_GetNodeHistory_FullMethodName = "/meridian.reference_data.v1.NodeService/GetNodeHistory"
	NodeService_ImportNodes_FullMethodName    = "/meridian.reference_data.v1.NodeService/ImportNodes"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeService manages hierarchical reference data nodes with bi-temporal support.
// All operations are tenant-scoped via JWT claims in request metadata.
type NodeServiceClient interface {
	// CreateNode creates a new reference data node.
	// The resolution key is computed automatically from the node's ancestors.
	// Returns ALREADY_EXISTS if an active node with the same resolution key exists.
	// Returns NOT_FOUND if parent_id references a non-existent node.
	// Returns FAILED_PRECONDITION if the parent node is not active.
	CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error)
	// UpdateNode modifies non-identity attributes of a node (attributes, valid_to).
	// Identity fields (tenant_id, node_type, parent_id, resolution_key) are immutable.
	// Uses optimistic locking via version field.
	// Returns NOT_FOUND if the node does not exist.
	// Returns ABORTED if the version has changed (optimistic lock failure).
	UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeResponse, error)
	// GetNode retrieves a node by its UUID.
	// Returns NOT_FOUND if the node does not exist.
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	// GetChildren returns child nodes of a given parent.
	// Supports filtering to active-only nodes.
	GetChildren(ctx context.Context, in *GetChildrenRequest, opts ...grpc.CallOption) (*GetChildrenResponse, error)
	// GetAncestors returns the chain of ancestors from the immediate parent to root.
	// Returns empty list for root nodes.
	GetAncestors(ctx context.Context, in *GetAncestorsRequest, opts ...grpc.CallOption) (*GetAncestorsResponse, error)
	// GetSubtree returns all descendants of a node up to a specified depth.
	// The root node itself is included at depth 0.
	GetSubtree(ctx context.Context, in *GetSubtreeRequest, opts ...grpc.CallOption) (*GetSubtreeResponse, error)
	// GetNodeAsAt retrieves the version of a node that was valid at a given time.
	// Uses bi-temporal query: valid_from <= as_at < valid_to.
	// Returns NOT_FOUND if no version was valid at the given time.
	GetNodeAsAt(ctx context.Context, in *GetNodeAsAtRequest, opts ...grpc.CallOption) (*GetNodeAsAtResponse, error)
	// GetNodeHistory returns all temporal versions of a node (active and superseded),
	// ordered by valid_from descending (newest first).
	GetNodeHistory(ctx context.Context, in *GetNodeHistoryRequest, opts ...grpc.CallOption) (*GetNodeHistoryResponse, error)
	// ImportNodes creates multiple nodes in a single batch transaction.
	// Nodes must be ordered so that parents appear before children.
	// Returns the count of successfully imported nodes.
	ImportNodes(ctx context.Context, in *ImportNodesRequest, opts ...grpc.CallOption) (*ImportNodesResponse, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNodeResponse)
	err := c.cc.Invoke(ctx, NodeService_CreateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNodeResponse)
	err := c.cc.Invoke(ctx, NodeService_UpdateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, NodeService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetChildren(ctx context.Context, in *GetChildrenRequest, opts ...grpc.CallOption) (*GetChildrenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChildrenResponse)
	err := c.cc.Invoke(ctx, NodeService_GetChildren_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetAncestors(ctx context.Context, in *GetAncestorsRequest, opts ...grpc.CallOption) (*GetAncestorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAncestorsResponse)
	err := c.cc.Invoke(ctx, NodeService_GetAncestors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetSubtree(ctx context.Context, in *GetSubtreeRequest, opts ...grpc.CallOption) (*GetSubtreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubtreeResponse)
	err := c.cc.Invoke(ctx, NodeService_GetSubtree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetNodeAsAt(ctx context.Context, in *GetNodeAsAtRequest, opts ...grpc.CallOption) (*GetNodeAsAtResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeAsAtResponse)
	err := c.cc.Invoke(ctx, NodeService_GetNodeAsAt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetNodeHistory(ctx context.Context, in *GetNodeHistoryRequest, opts ...grpc.CallOption) (*GetNodeHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeHistoryResponse)
	err := c.cc.Invoke(ctx, NodeService_GetNodeHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ImportNodes(ctx context.Context, in *ImportNodesRequest, opts ...grpc.CallOption) (*ImportNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportNodesResponse)
	err := c.cc.Invoke(ctx, NodeService_ImportNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
//
// NodeService manages hierarchical reference data nodes with bi-temporal support.
// All operations are tenant-scoped via JWT claims in request metadata.
type NodeServiceServer interface {
	// CreateNode creates a new reference data node.
	// The resolution key is computed automatically from the node's ancestors.
	// Returns ALREADY_EXISTS if an active node with the same resolution key exists.
	// Returns NOT_FOUND if parent_id references a non-existent node.
	// Returns FAILED_PRECONDITION if the parent node is not active.
	CreateNode(context.Context, *CreateNodeRequest) (*CreateNodeResponse, error)
	// UpdateNode modifies non-identity attributes of a node (attributes, valid_to).
	// Identity fields (tenant_id, node_type, parent_id, resolution_key) are immutable.
	// Uses optimistic locking via version field.
	// Returns NOT_FOUND if the node does not exist.
	// Returns ABORTED if the version has changed (optimistic lock failure).
	UpdateNode(context.Context, *UpdateNodeRequest) (*UpdateNodeResponse, error)
	// GetNode retrieves a node by its UUID.
	// Returns NOT_FOUND if the node does not exist.
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	// GetChildren returns child nodes of a given parent.
	// Supports filtering to active-only nodes.
	GetChildren(context.Context, *GetChildrenRequest) (*GetChildrenResponse, error)
	// GetAncestors returns the chain of ancestors from the immediate parent to root.
	// Returns empty list for root nodes.
	GetAncestors(context.Context, *GetAncestorsRequest) (*GetAncestorsResponse, error)
	// GetSubtree returns all descendants of a node up to a specified depth.
	// The root node itself is included at depth 0.
	GetSubtree(context.Context, *GetSubtreeRequest) (*GetSubtreeResponse, error)
	// GetNodeAsAt retrieves the version of a node that was valid at a given time.
	// Uses bi-temporal query: valid_from <= as_at < valid_to.
	// Returns NOT_FOUND if no version was valid at the given time.
	GetNodeAsAt(context.Context, *GetNodeAsAtRequest) (*GetNodeAsAtResponse, error)
	// GetNodeHistory returns all temporal versions of a node (active and superseded),
	// ordered by valid_from descending (newest first).
	GetNodeHistory(context.Context, *GetNodeHistoryRequest) (*GetNodeHistoryResponse, error)
	// ImportNodes creates multiple nodes in a single batch transaction.
	// Nodes must be ordered so that parents appear before children.
	// Returns the count of successfully imported nodes.
	ImportNodes(context.Context, *ImportNodesRequest) (*ImportNodesResponse, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) CreateNode(context.Context, *CreateNodeRequest) (*CreateNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNode not implemented")
}
func (UnimplementedNodeServiceServer) UpdateNode(context.Context, *UpdateNodeRequest) (*UpdateNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNode not implemented")
}
func (UnimplementedNodeServiceServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedNodeServiceServer) GetChildren(context.Context, *GetChildrenRequest) (*GetChildrenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChildren not implemented")
}
func (UnimplementedNodeServiceServer) GetAncestors(context.Context, *GetAncestorsRequest) (*GetAncestorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAncestors not implemented")
}
func (UnimplementedNodeServiceServer) GetSubtree(context.Context, *GetSubtreeRequest) (*GetSubtreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubtree not implemented")
}
func (UnimplementedNodeServiceServer) GetNodeAsAt(context.Context, *GetNodeAsAtRequest) (*GetNodeAsAtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeAsAt not implemented")
}
func (UnimplementedNodeServiceServer) GetNodeHistory(context.Context, *GetNodeHistoryRequest) (*GetNodeHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeHistory not implemented")
}
func (UnimplementedNodeServiceServer) ImportNodes(context.Context, *ImportNodesRequest) (*ImportNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportNodes not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_CreateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).CreateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_CreateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).CreateNode(ctx, req.(*CreateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_UpdateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).UpdateNode(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetChildren_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChildrenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetChildren(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetChildren_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetChildren(ctx, req.(*GetChildrenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetAncestors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAncestorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetAncestors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetAncestors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetAncestors(ctx, req.(*GetAncestorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetSubtree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubtreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetSubtree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetSubtree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetSubtree(ctx, req.(*GetSubtreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetNodeAsAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeAsAtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetNodeAsAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetNodeAsAt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetNodeAsAt(ctx, req.(*GetNodeAsAtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetNodeHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetNodeHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetNodeHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetNodeHistory(ctx, req.(*GetNodeHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ImportNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ImportNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ImportNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ImportNodes(ctx, req.(*ImportNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meridian.reference_data.v1.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNode",
			Handler:    _NodeService_CreateNode_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _NodeService_UpdateNode_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _NodeService_GetNode_Handler,
		},
		{
			MethodName: "GetChildren",
			Handler:    _NodeService_GetChildren_Handler,
		},
		{
			MethodName: "GetAncestors",
			Handler:    _NodeService_GetAncestors_Handler,
		},
		{
			MethodName: "GetSubtree",
			Handler:    _NodeService_GetSubtree_Handler,
		},
		{
			MethodName: "GetNodeAsAt",
			Handler:    _NodeService_GetNodeAsAt_Handler,
		},
		{
			MethodName: "GetNodeHistory",
			Handler:    _NodeService_GetNodeHistory_Handler,
		},
		{
			MethodName: "ImportNodes",
			Handler:    _NodeService_ImportNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meridian/reference_data/v1/node.proto",
}
