apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: meridian-base

namespace: default

labels:
- pairs:
    app: meridian
    managed-by: kustomize

resources:
- serviceaccount.yaml
- configmap.yaml
- deployment.yaml
- service.yaml

images:
- name: meridian
  newTag: latest

configMapGenerator:
- name: meridian-version
  literals:
  - version=dev
  - commit=unknown
  - build_date=unknown

generatorOptions:
  disableNameSuffixHash: false
  labels:
    app: meridian
