// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: meridian/control_plane/v1/admin.proto

package controlplanev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CausationVisualizerService_GetCausationTreeForPosition_FullMethodName    = "/meridian.control_plane.v1.CausationVisualizerService/GetCausationTreeForPosition"
	CausationVisualizerService_GetCausationTreeForTransaction_FullMethodName = "/meridian.control_plane.v1.CausationVisualizerService/GetCausationTreeForTransaction"
	CausationVisualizerService_GetCausationTreeForEvent_FullMethodName       = "/meridian.control_plane.v1.CausationVisualizerService/GetCausationTreeForEvent"
)

// CausationVisualizerServiceClient is the client API for CausationVisualizerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CausationVisualizerService provides CFO Glass Box causation tree visualization.
// It enables drill-down from balance sheet positions and transactions to the
// root saga that originated them, providing a complete audit trail for CFOs
// and compliance officers.
//
// The service traces the causation chain:
//
//	Position/Transaction -> saga_instance -> CausationTree (via existing SagaAdminService)
//
// This enables the "Glass Box" pattern: click a balance sheet line item,
// see every saga step that produced it.
type CausationVisualizerServiceClient interface {
	// GetCausationTreeForPosition traces a financial position log back to its
	// originating saga and returns the full causation tree.
	// The position's transaction lineage is used to find the saga that created it.
	GetCausationTreeForPosition(ctx context.Context, in *GetCausationTreeForPositionRequest, opts ...grpc.CallOption) (*GetCausationTreeForPositionResponse, error)
	// GetCausationTreeForTransaction traces a transaction back to its originating
	// saga and returns the full causation tree.
	GetCausationTreeForTransaction(ctx context.Context, in *GetCausationTreeForTransactionRequest, opts ...grpc.CallOption) (*GetCausationTreeForTransactionResponse, error)
	// GetCausationTreeForEvent traces an event back through the saga execution
	// chain using its causation_id.
	GetCausationTreeForEvent(ctx context.Context, in *GetCausationTreeForEventRequest, opts ...grpc.CallOption) (*GetCausationTreeForEventResponse, error)
}

type causationVisualizerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCausationVisualizerServiceClient(cc grpc.ClientConnInterface) CausationVisualizerServiceClient {
	return &causationVisualizerServiceClient{cc}
}

func (c *causationVisualizerServiceClient) GetCausationTreeForPosition(ctx context.Context, in *GetCausationTreeForPositionRequest, opts ...grpc.CallOption) (*GetCausationTreeForPositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCausationTreeForPositionResponse)
	err := c.cc.Invoke(ctx, CausationVisualizerService_GetCausationTreeForPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *causationVisualizerServiceClient) GetCausationTreeForTransaction(ctx context.Context, in *GetCausationTreeForTransactionRequest, opts ...grpc.CallOption) (*GetCausationTreeForTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCausationTreeForTransactionResponse)
	err := c.cc.Invoke(ctx, CausationVisualizerService_GetCausationTreeForTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *causationVisualizerServiceClient) GetCausationTreeForEvent(ctx context.Context, in *GetCausationTreeForEventRequest, opts ...grpc.CallOption) (*GetCausationTreeForEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCausationTreeForEventResponse)
	err := c.cc.Invoke(ctx, CausationVisualizerService_GetCausationTreeForEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CausationVisualizerServiceServer is the server API for CausationVisualizerService service.
// All implementations must embed UnimplementedCausationVisualizerServiceServer
// for forward compatibility.
//
// CausationVisualizerService provides CFO Glass Box causation tree visualization.
// It enables drill-down from balance sheet positions and transactions to the
// root saga that originated them, providing a complete audit trail for CFOs
// and compliance officers.
//
// The service traces the causation chain:
//
//	Position/Transaction -> saga_instance -> CausationTree (via existing SagaAdminService)
//
// This enables the "Glass Box" pattern: click a balance sheet line item,
// see every saga step that produced it.
type CausationVisualizerServiceServer interface {
	// GetCausationTreeForPosition traces a financial position log back to its
	// originating saga and returns the full causation tree.
	// The position's transaction lineage is used to find the saga that created it.
	GetCausationTreeForPosition(context.Context, *GetCausationTreeForPositionRequest) (*GetCausationTreeForPositionResponse, error)
	// GetCausationTreeForTransaction traces a transaction back to its originating
	// saga and returns the full causation tree.
	GetCausationTreeForTransaction(context.Context, *GetCausationTreeForTransactionRequest) (*GetCausationTreeForTransactionResponse, error)
	// GetCausationTreeForEvent traces an event back through the saga execution
	// chain using its causation_id.
	GetCausationTreeForEvent(context.Context, *GetCausationTreeForEventRequest) (*GetCausationTreeForEventResponse, error)
	mustEmbedUnimplementedCausationVisualizerServiceServer()
}

// UnimplementedCausationVisualizerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCausationVisualizerServiceServer struct{}

func (UnimplementedCausationVisualizerServiceServer) GetCausationTreeForPosition(context.Context, *GetCausationTreeForPositionRequest) (*GetCausationTreeForPositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCausationTreeForPosition not implemented")
}
func (UnimplementedCausationVisualizerServiceServer) GetCausationTreeForTransaction(context.Context, *GetCausationTreeForTransactionRequest) (*GetCausationTreeForTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCausationTreeForTransaction not implemented")
}
func (UnimplementedCausationVisualizerServiceServer) GetCausationTreeForEvent(context.Context, *GetCausationTreeForEventRequest) (*GetCausationTreeForEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCausationTreeForEvent not implemented")
}
func (UnimplementedCausationVisualizerServiceServer) mustEmbedUnimplementedCausationVisualizerServiceServer() {
}
func (UnimplementedCausationVisualizerServiceServer) testEmbeddedByValue() {}

// UnsafeCausationVisualizerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CausationVisualizerServiceServer will
// result in compilation errors.
type UnsafeCausationVisualizerServiceServer interface {
	mustEmbedUnimplementedCausationVisualizerServiceServer()
}

func RegisterCausationVisualizerServiceServer(s grpc.ServiceRegistrar, srv CausationVisualizerServiceServer) {
	// If the following call pancis, it indicates UnimplementedCausationVisualizerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CausationVisualizerService_ServiceDesc, srv)
}

func _CausationVisualizerService_GetCausationTreeForPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCausationTreeForPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CausationVisualizerServiceServer).GetCausationTreeForPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CausationVisualizerService_GetCausationTreeForPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CausationVisualizerServiceServer).GetCausationTreeForPosition(ctx, req.(*GetCausationTreeForPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CausationVisualizerService_GetCausationTreeForTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCausationTreeForTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CausationVisualizerServiceServer).GetCausationTreeForTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CausationVisualizerService_GetCausationTreeForTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CausationVisualizerServiceServer).GetCausationTreeForTransaction(ctx, req.(*GetCausationTreeForTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CausationVisualizerService_GetCausationTreeForEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCausationTreeForEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CausationVisualizerServiceServer).GetCausationTreeForEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CausationVisualizerService_GetCausationTreeForEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CausationVisualizerServiceServer).GetCausationTreeForEvent(ctx, req.(*GetCausationTreeForEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CausationVisualizerService_ServiceDesc is the grpc.ServiceDesc for CausationVisualizerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CausationVisualizerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meridian.control_plane.v1.CausationVisualizerService",
	HandlerType: (*CausationVisualizerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCausationTreeForPosition",
			Handler:    _CausationVisualizerService_GetCausationTreeForPosition_Handler,
		},
		{
			MethodName: "GetCausationTreeForTransaction",
			Handler:    _CausationVisualizerService_GetCausationTreeForTransaction_Handler,
		},
		{
			MethodName: "GetCausationTreeForEvent",
			Handler:    _CausationVisualizerService_GetCausationTreeForEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meridian/control_plane/v1/admin.proto",
}

const (
	BalanceSheetService_GetBalanceSheet_FullMethodName       = "/meridian.control_plane.v1.BalanceSheetService/GetBalanceSheet"
	BalanceSheetService_GetPositionDetails_FullMethodName    = "/meridian.control_plane.v1.BalanceSheetService/GetPositionDetails"
	BalanceSheetService_ExportBalanceSheetCSV_FullMethodName = "/meridian.control_plane.v1.BalanceSheetService/ExportBalanceSheetCSV"
)

// BalanceSheetServiceClient is the client API for BalanceSheetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BalanceSheetService provides CFO Glass Box balance sheet views.
// It aggregates positions across multiple instruments with classification
// into ASSETS, LIABILITIES, and EQUITY sections, enabling drill-down
// to causation trees for full auditability.
type BalanceSheetServiceClient interface {
	// GetBalanceSheet returns a multi-asset balance sheet for a tenant,
	// grouped by classification with totals per instrument.
	GetBalanceSheet(ctx context.Context, in *GetBalanceSheetRequest, opts ...grpc.CallOption) (*GetBalanceSheetResponse, error)
	// GetPositionDetails returns drill-down details for a specific account type
	// and instrument, including individual positions with causation IDs.
	GetPositionDetails(ctx context.Context, in *GetPositionDetailsRequest, opts ...grpc.CallOption) (*GetPositionDetailsResponse, error)
	// ExportBalanceSheetCSV exports the balance sheet as CSV with metadata.
	ExportBalanceSheetCSV(ctx context.Context, in *ExportBalanceSheetCSVRequest, opts ...grpc.CallOption) (*ExportBalanceSheetCSVResponse, error)
}

type balanceSheetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBalanceSheetServiceClient(cc grpc.ClientConnInterface) BalanceSheetServiceClient {
	return &balanceSheetServiceClient{cc}
}

func (c *balanceSheetServiceClient) GetBalanceSheet(ctx context.Context, in *GetBalanceSheetRequest, opts ...grpc.CallOption) (*GetBalanceSheetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceSheetResponse)
	err := c.cc.Invoke(ctx, BalanceSheetService_GetBalanceSheet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceSheetServiceClient) GetPositionDetails(ctx context.Context, in *GetPositionDetailsRequest, opts ...grpc.CallOption) (*GetPositionDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPositionDetailsResponse)
	err := c.cc.Invoke(ctx, BalanceSheetService_GetPositionDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceSheetServiceClient) ExportBalanceSheetCSV(ctx context.Context, in *ExportBalanceSheetCSVRequest, opts ...grpc.CallOption) (*ExportBalanceSheetCSVResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportBalanceSheetCSVResponse)
	err := c.cc.Invoke(ctx, BalanceSheetService_ExportBalanceSheetCSV_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceSheetServiceServer is the server API for BalanceSheetService service.
// All implementations must embed UnimplementedBalanceSheetServiceServer
// for forward compatibility.
//
// BalanceSheetService provides CFO Glass Box balance sheet views.
// It aggregates positions across multiple instruments with classification
// into ASSETS, LIABILITIES, and EQUITY sections, enabling drill-down
// to causation trees for full auditability.
type BalanceSheetServiceServer interface {
	// GetBalanceSheet returns a multi-asset balance sheet for a tenant,
	// grouped by classification with totals per instrument.
	GetBalanceSheet(context.Context, *GetBalanceSheetRequest) (*GetBalanceSheetResponse, error)
	// GetPositionDetails returns drill-down details for a specific account type
	// and instrument, including individual positions with causation IDs.
	GetPositionDetails(context.Context, *GetPositionDetailsRequest) (*GetPositionDetailsResponse, error)
	// ExportBalanceSheetCSV exports the balance sheet as CSV with metadata.
	ExportBalanceSheetCSV(context.Context, *ExportBalanceSheetCSVRequest) (*ExportBalanceSheetCSVResponse, error)
	mustEmbedUnimplementedBalanceSheetServiceServer()
}

// UnimplementedBalanceSheetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBalanceSheetServiceServer struct{}

func (UnimplementedBalanceSheetServiceServer) GetBalanceSheet(context.Context, *GetBalanceSheetRequest) (*GetBalanceSheetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalanceSheet not implemented")
}
func (UnimplementedBalanceSheetServiceServer) GetPositionDetails(context.Context, *GetPositionDetailsRequest) (*GetPositionDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPositionDetails not implemented")
}
func (UnimplementedBalanceSheetServiceServer) ExportBalanceSheetCSV(context.Context, *ExportBalanceSheetCSVRequest) (*ExportBalanceSheetCSVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportBalanceSheetCSV not implemented")
}
func (UnimplementedBalanceSheetServiceServer) mustEmbedUnimplementedBalanceSheetServiceServer() {}
func (UnimplementedBalanceSheetServiceServer) testEmbeddedByValue()                             {}

// UnsafeBalanceSheetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BalanceSheetServiceServer will
// result in compilation errors.
type UnsafeBalanceSheetServiceServer interface {
	mustEmbedUnimplementedBalanceSheetServiceServer()
}

func RegisterBalanceSheetServiceServer(s grpc.ServiceRegistrar, srv BalanceSheetServiceServer) {
	// If the following call pancis, it indicates UnimplementedBalanceSheetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BalanceSheetService_ServiceDesc, srv)
}

func _BalanceSheetService_GetBalanceSheet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceSheetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceSheetServiceServer).GetBalanceSheet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceSheetService_GetBalanceSheet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceSheetServiceServer).GetBalanceSheet(ctx, req.(*GetBalanceSheetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceSheetService_GetPositionDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPositionDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceSheetServiceServer).GetPositionDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceSheetService_GetPositionDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceSheetServiceServer).GetPositionDetails(ctx, req.(*GetPositionDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceSheetService_ExportBalanceSheetCSV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportBalanceSheetCSVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceSheetServiceServer).ExportBalanceSheetCSV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceSheetService_ExportBalanceSheetCSV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceSheetServiceServer).ExportBalanceSheetCSV(ctx, req.(*ExportBalanceSheetCSVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BalanceSheetService_ServiceDesc is the grpc.ServiceDesc for BalanceSheetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BalanceSheetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meridian.control_plane.v1.BalanceSheetService",
	HandlerType: (*BalanceSheetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalanceSheet",
			Handler:    _BalanceSheetService_GetBalanceSheet_Handler,
		},
		{
			MethodName: "GetPositionDetails",
			Handler:    _BalanceSheetService_GetPositionDetails_Handler,
		},
		{
			MethodName: "ExportBalanceSheetCSV",
			Handler:    _BalanceSheetService_ExportBalanceSheetCSV_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meridian/control_plane/v1/admin.proto",
}
