// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: meridian/control_plane/v1/apply_manifest_service.proto

package controlplanev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApplyManifestService_ApplyManifest_FullMethodName = "/meridian.control_plane.v1.ApplyManifestService/ApplyManifest"
	ApplyManifestService_ApplyResource_FullMethodName = "/meridian.control_plane.v1.ApplyManifestService/ApplyResource"
)

// ApplyManifestServiceClient is the client API for ApplyManifestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ApplyManifestService is the public entry point for applying tenant manifests.
// It orchestrates validation, diffing, planning, and execution of manifest changes.
type ApplyManifestServiceClient interface {
	// ApplyManifest validates and applies a manifest, returning the execution result.
	// In dry_run mode, validation and planning are performed but no changes are committed.
	ApplyManifest(ctx context.Context, in *ApplyManifestRequest, opts ...grpc.CallOption) (*ApplyManifestResponse, error)
	// ApplyResource applies a granular mutation to a single resource within the manifest.
	// It reads the current manifest from the database, patches the specified resource into
	// the composite manifest, validates the full dependency graph, computes a diff, and
	// executes only the affected phases. A new manifest version is created on success.
	// In dry_run mode, returns the diff without applying changes.
	ApplyResource(ctx context.Context, in *ApplyResourceRequest, opts ...grpc.CallOption) (*ApplyResourceResponse, error)
}

type applyManifestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApplyManifestServiceClient(cc grpc.ClientConnInterface) ApplyManifestServiceClient {
	return &applyManifestServiceClient{cc}
}

func (c *applyManifestServiceClient) ApplyManifest(ctx context.Context, in *ApplyManifestRequest, opts ...grpc.CallOption) (*ApplyManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyManifestResponse)
	err := c.cc.Invoke(ctx, ApplyManifestService_ApplyManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyManifestServiceClient) ApplyResource(ctx context.Context, in *ApplyResourceRequest, opts ...grpc.CallOption) (*ApplyResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResourceResponse)
	err := c.cc.Invoke(ctx, ApplyManifestService_ApplyResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplyManifestServiceServer is the server API for ApplyManifestService service.
// All implementations must embed UnimplementedApplyManifestServiceServer
// for forward compatibility.
//
// ApplyManifestService is the public entry point for applying tenant manifests.
// It orchestrates validation, diffing, planning, and execution of manifest changes.
type ApplyManifestServiceServer interface {
	// ApplyManifest validates and applies a manifest, returning the execution result.
	// In dry_run mode, validation and planning are performed but no changes are committed.
	ApplyManifest(context.Context, *ApplyManifestRequest) (*ApplyManifestResponse, error)
	// ApplyResource applies a granular mutation to a single resource within the manifest.
	// It reads the current manifest from the database, patches the specified resource into
	// the composite manifest, validates the full dependency graph, computes a diff, and
	// executes only the affected phases. A new manifest version is created on success.
	// In dry_run mode, returns the diff without applying changes.
	ApplyResource(context.Context, *ApplyResourceRequest) (*ApplyResourceResponse, error)
	mustEmbedUnimplementedApplyManifestServiceServer()
}

// UnimplementedApplyManifestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApplyManifestServiceServer struct{}

func (UnimplementedApplyManifestServiceServer) ApplyManifest(context.Context, *ApplyManifestRequest) (*ApplyManifestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyManifest not implemented")
}
func (UnimplementedApplyManifestServiceServer) ApplyResource(context.Context, *ApplyResourceRequest) (*ApplyResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyResource not implemented")
}
func (UnimplementedApplyManifestServiceServer) mustEmbedUnimplementedApplyManifestServiceServer() {}
func (UnimplementedApplyManifestServiceServer) testEmbeddedByValue()                              {}

// UnsafeApplyManifestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApplyManifestServiceServer will
// result in compilation errors.
type UnsafeApplyManifestServiceServer interface {
	mustEmbedUnimplementedApplyManifestServiceServer()
}

func RegisterApplyManifestServiceServer(s grpc.ServiceRegistrar, srv ApplyManifestServiceServer) {
	// If the following call pancis, it indicates UnimplementedApplyManifestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApplyManifestService_ServiceDesc, srv)
}

func _ApplyManifestService_ApplyManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyManifestServiceServer).ApplyManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyManifestService_ApplyManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyManifestServiceServer).ApplyManifest(ctx, req.(*ApplyManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplyManifestService_ApplyResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplyManifestServiceServer).ApplyResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplyManifestService_ApplyResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplyManifestServiceServer).ApplyResource(ctx, req.(*ApplyResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApplyManifestService_ServiceDesc is the grpc.ServiceDesc for ApplyManifestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApplyManifestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meridian.control_plane.v1.ApplyManifestService",
	HandlerType: (*ApplyManifestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyManifest",
			Handler:    _ApplyManifestService_ApplyManifest_Handler,
		},
		{
			MethodName: "ApplyResource",
			Handler:    _ApplyManifestService_ApplyResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meridian/control_plane/v1/apply_manifest_service.proto",
}
