// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: meridian/control_plane/v1/economy_generator_service.proto

package controlplanev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EconomyGeneratorService_GenerateManifest_FullMethodName     = "/meridian.control_plane.v1.EconomyGeneratorService/GenerateManifest"
	EconomyGeneratorService_GetGenerationContext_FullMethodName = "/meridian.control_plane.v1.EconomyGeneratorService/GetGenerationContext"
)

// EconomyGeneratorServiceClient is the client API for EconomyGeneratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EconomyGeneratorService generates tenant manifests from natural language descriptions
// using AI assistance. It supports both creating new economies and amending existing ones.
type EconomyGeneratorServiceClient interface {
	// GenerateManifest takes a natural language description and produces a valid tenant manifest.
	// The service uses AI to translate the description into a structured manifest, validates it,
	// and iterates to fix any validation errors up to max_fix_iterations times.
	GenerateManifest(ctx context.Context, in *GenerateManifestRequest, opts ...grpc.CallOption) (*GenerateManifestResponse, error)
	// GetGenerationContext returns the context that would be used for generating a manifest
	// from the given description, without performing the actual generation. Useful for
	// understanding what patterns and handlers are relevant to a description.
	GetGenerationContext(ctx context.Context, in *GetGenerationContextRequest, opts ...grpc.CallOption) (*GetGenerationContextResponse, error)
}

type economyGeneratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEconomyGeneratorServiceClient(cc grpc.ClientConnInterface) EconomyGeneratorServiceClient {
	return &economyGeneratorServiceClient{cc}
}

func (c *economyGeneratorServiceClient) GenerateManifest(ctx context.Context, in *GenerateManifestRequest, opts ...grpc.CallOption) (*GenerateManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateManifestResponse)
	err := c.cc.Invoke(ctx, EconomyGeneratorService_GenerateManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *economyGeneratorServiceClient) GetGenerationContext(ctx context.Context, in *GetGenerationContextRequest, opts ...grpc.CallOption) (*GetGenerationContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGenerationContextResponse)
	err := c.cc.Invoke(ctx, EconomyGeneratorService_GetGenerationContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EconomyGeneratorServiceServer is the server API for EconomyGeneratorService service.
// All implementations must embed UnimplementedEconomyGeneratorServiceServer
// for forward compatibility.
//
// EconomyGeneratorService generates tenant manifests from natural language descriptions
// using AI assistance. It supports both creating new economies and amending existing ones.
type EconomyGeneratorServiceServer interface {
	// GenerateManifest takes a natural language description and produces a valid tenant manifest.
	// The service uses AI to translate the description into a structured manifest, validates it,
	// and iterates to fix any validation errors up to max_fix_iterations times.
	GenerateManifest(context.Context, *GenerateManifestRequest) (*GenerateManifestResponse, error)
	// GetGenerationContext returns the context that would be used for generating a manifest
	// from the given description, without performing the actual generation. Useful for
	// understanding what patterns and handlers are relevant to a description.
	GetGenerationContext(context.Context, *GetGenerationContextRequest) (*GetGenerationContextResponse, error)
	mustEmbedUnimplementedEconomyGeneratorServiceServer()
}

// UnimplementedEconomyGeneratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEconomyGeneratorServiceServer struct{}

func (UnimplementedEconomyGeneratorServiceServer) GenerateManifest(context.Context, *GenerateManifestRequest) (*GenerateManifestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateManifest not implemented")
}
func (UnimplementedEconomyGeneratorServiceServer) GetGenerationContext(context.Context, *GetGenerationContextRequest) (*GetGenerationContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGenerationContext not implemented")
}
func (UnimplementedEconomyGeneratorServiceServer) mustEmbedUnimplementedEconomyGeneratorServiceServer() {
}
func (UnimplementedEconomyGeneratorServiceServer) testEmbeddedByValue() {}

// UnsafeEconomyGeneratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EconomyGeneratorServiceServer will
// result in compilation errors.
type UnsafeEconomyGeneratorServiceServer interface {
	mustEmbedUnimplementedEconomyGeneratorServiceServer()
}

func RegisterEconomyGeneratorServiceServer(s grpc.ServiceRegistrar, srv EconomyGeneratorServiceServer) {
	// If the following call pancis, it indicates UnimplementedEconomyGeneratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EconomyGeneratorService_ServiceDesc, srv)
}

func _EconomyGeneratorService_GenerateManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EconomyGeneratorServiceServer).GenerateManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EconomyGeneratorService_GenerateManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EconomyGeneratorServiceServer).GenerateManifest(ctx, req.(*GenerateManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EconomyGeneratorService_GetGenerationContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGenerationContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EconomyGeneratorServiceServer).GetGenerationContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EconomyGeneratorService_GetGenerationContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EconomyGeneratorServiceServer).GetGenerationContext(ctx, req.(*GetGenerationContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EconomyGeneratorService_ServiceDesc is the grpc.ServiceDesc for EconomyGeneratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EconomyGeneratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meridian.control_plane.v1.EconomyGeneratorService",
	HandlerType: (*EconomyGeneratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateManifest",
			Handler:    _EconomyGeneratorService_GenerateManifest_Handler,
		},
		{
			MethodName: "GetGenerationContext",
			Handler:    _EconomyGeneratorService_GetGenerationContext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meridian/control_plane/v1/economy_generator_service.proto",
}
