// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: meridian/control_plane/v1/saga_execution_service.proto

package controlplanev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SagaExecutionService_ExecuteSaga_FullMethodName = "/meridian.control_plane.v1.SagaExecutionService/ExecuteSaga"
)

// SagaExecutionServiceClient is the client API for SagaExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SagaExecutionService provides an API for triggering saga workflows.
// External services (e.g., event-router) use this to start saga instances
// in response to domain events without requiring direct Starlark runtime access.
type SagaExecutionServiceClient interface {
	// ExecuteSaga triggers a new saga instance by name with the given input data.
	// Uses idempotency key to prevent duplicate saga instances from concurrent or
	// retry triggers (e.g., Kafka at-least-once delivery).
	ExecuteSaga(ctx context.Context, in *ExecuteSagaRequest, opts ...grpc.CallOption) (*ExecuteSagaResponse, error)
}

type sagaExecutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSagaExecutionServiceClient(cc grpc.ClientConnInterface) SagaExecutionServiceClient {
	return &sagaExecutionServiceClient{cc}
}

func (c *sagaExecutionServiceClient) ExecuteSaga(ctx context.Context, in *ExecuteSagaRequest, opts ...grpc.CallOption) (*ExecuteSagaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteSagaResponse)
	err := c.cc.Invoke(ctx, SagaExecutionService_ExecuteSaga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SagaExecutionServiceServer is the server API for SagaExecutionService service.
// All implementations must embed UnimplementedSagaExecutionServiceServer
// for forward compatibility.
//
// SagaExecutionService provides an API for triggering saga workflows.
// External services (e.g., event-router) use this to start saga instances
// in response to domain events without requiring direct Starlark runtime access.
type SagaExecutionServiceServer interface {
	// ExecuteSaga triggers a new saga instance by name with the given input data.
	// Uses idempotency key to prevent duplicate saga instances from concurrent or
	// retry triggers (e.g., Kafka at-least-once delivery).
	ExecuteSaga(context.Context, *ExecuteSagaRequest) (*ExecuteSagaResponse, error)
	mustEmbedUnimplementedSagaExecutionServiceServer()
}

// UnimplementedSagaExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSagaExecutionServiceServer struct{}

func (UnimplementedSagaExecutionServiceServer) ExecuteSaga(context.Context, *ExecuteSagaRequest) (*ExecuteSagaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteSaga not implemented")
}
func (UnimplementedSagaExecutionServiceServer) mustEmbedUnimplementedSagaExecutionServiceServer() {}
func (UnimplementedSagaExecutionServiceServer) testEmbeddedByValue()                              {}

// UnsafeSagaExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SagaExecutionServiceServer will
// result in compilation errors.
type UnsafeSagaExecutionServiceServer interface {
	mustEmbedUnimplementedSagaExecutionServiceServer()
}

func RegisterSagaExecutionServiceServer(s grpc.ServiceRegistrar, srv SagaExecutionServiceServer) {
	// If the following call pancis, it indicates UnimplementedSagaExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SagaExecutionService_ServiceDesc, srv)
}

func _SagaExecutionService_ExecuteSaga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteSagaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaExecutionServiceServer).ExecuteSaga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaExecutionService_ExecuteSaga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaExecutionServiceServer).ExecuteSaga(ctx, req.(*ExecuteSagaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SagaExecutionService_ServiceDesc is the grpc.ServiceDesc for SagaExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SagaExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meridian.control_plane.v1.SagaExecutionService",
	HandlerType: (*SagaExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteSaga",
			Handler:    _SagaExecutionService_ExecuteSaga_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meridian/control_plane/v1/saga_execution_service.proto",
}
