// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: meridian/current_account/v1/current_account.proto

package currentaccountv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	commonv1 "github.com/bjcoombs/meridian/api/proto/meridian/common/v1"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = commonv1.Currency(0)
)

// Validate checks the field values on CurrentAccountFacility with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CurrentAccountFacility) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CurrentAccountFacility with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CurrentAccountFacilityMultiError, or nil if none found.
func (m *CurrentAccountFacility) ValidateAll() error {
	return m.validate(true)
}

func (m *CurrentAccountFacility) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AccountId

	// no validation rules for AccountIdentification

	// no validation rules for AccountStatus

	// no validation rules for BaseCurrency

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CurrentAccountFacilityValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CurrentAccountFacilityValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CurrentAccountFacilityValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CurrentAccountFacilityValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CurrentAccountFacilityValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CurrentAccountFacilityValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Version

	if len(errors) > 0 {
		return CurrentAccountFacilityMultiError(errors)
	}

	return nil
}

// CurrentAccountFacilityMultiError is an error wrapping multiple validation
// errors returned by CurrentAccountFacility.ValidateAll() if the designated
// constraints aren't met.
type CurrentAccountFacilityMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CurrentAccountFacilityMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CurrentAccountFacilityMultiError) AllErrors() []error { return m }

// CurrentAccountFacilityValidationError is the validation error returned by
// CurrentAccountFacility.Validate if the designated constraints aren't met.
type CurrentAccountFacilityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CurrentAccountFacilityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CurrentAccountFacilityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CurrentAccountFacilityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CurrentAccountFacilityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CurrentAccountFacilityValidationError) ErrorName() string {
	return "CurrentAccountFacilityValidationError"
}

// Error satisfies the builtin error interface
func (e CurrentAccountFacilityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCurrentAccountFacility.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CurrentAccountFacilityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CurrentAccountFacilityValidationError{}
