// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: meridian/internal_account/v1/internal_account.proto

package internalaccountv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalAccountService_InitiateInternalAccount_FullMethodName = "/meridian.internal_account.v1.InternalAccountService/InitiateInternalAccount"
	InternalAccountService_UpdateInternalAccount_FullMethodName   = "/meridian.internal_account.v1.InternalAccountService/UpdateInternalAccount"
	InternalAccountService_ControlInternalAccount_FullMethodName  = "/meridian.internal_account.v1.InternalAccountService/ControlInternalAccount"
	InternalAccountService_RetrieveInternalAccount_FullMethodName = "/meridian.internal_account.v1.InternalAccountService/RetrieveInternalAccount"
	InternalAccountService_ListInternalAccounts_FullMethodName    = "/meridian.internal_account.v1.InternalAccountService/ListInternalAccounts"
	InternalAccountService_GetBalance_FullMethodName              = "/meridian.internal_account.v1.InternalAccountService/GetBalance"
	InternalAccountService_CreateValuationFeature_FullMethodName  = "/meridian.internal_account.v1.InternalAccountService/CreateValuationFeature"
	InternalAccountService_UpdateValuationFeature_FullMethodName  = "/meridian.internal_account.v1.InternalAccountService/UpdateValuationFeature"
	InternalAccountService_GetValuationFeature_FullMethodName     = "/meridian.internal_account.v1.InternalAccountService/GetValuationFeature"
	InternalAccountService_EvaluateAssetValuation_FullMethodName  = "/meridian.internal_account.v1.InternalAccountService/EvaluateAssetValuation"
	InternalAccountService_ListValuationFeatures_FullMethodName   = "/meridian.internal_account.v1.InternalAccountService/ListValuationFeatures"
	InternalAccountService_InitiateLien_FullMethodName            = "/meridian.internal_account.v1.InternalAccountService/InitiateLien"
	InternalAccountService_ExecuteLien_FullMethodName             = "/meridian.internal_account.v1.InternalAccountService/ExecuteLien"
	InternalAccountService_TerminateLien_FullMethodName           = "/meridian.internal_account.v1.InternalAccountService/TerminateLien"
	InternalAccountService_RetrieveLien_FullMethodName            = "/meridian.internal_account.v1.InternalAccountService/RetrieveLien"
)

// InternalAccountServiceClient is the client API for InternalAccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InternalAccountService provides BIAN-compliant internal account operations.
// Internal accounts are non-customer-facing accounts used for operational purposes
// such as clearing, correspondent banking (nostro/vostro), holding, suspense, and GL entries.
//
// Design Notes:
//   - DELETE operations are intentionally not provided. Accounts are managed through
//     status transitions (Active -> Suspended -> Closed) for audit compliance.
//   - Balance queries route to Position Keeping service - internal accounts participate
//     in the universal position tracking system.
//   - No RecordPosting RPC - postings flow through Financial Accounting -> Position Keeping.
type InternalAccountServiceClient interface {
	// InitiateInternalAccount creates a new internal account.
	// The account is created in ACTIVE status.
	InitiateInternalAccount(ctx context.Context, in *InitiateInternalAccountRequest, opts ...grpc.CallOption) (*InitiateInternalAccountResponse, error)
	// UpdateInternalAccount modifies account settings (partial update).
	// Cannot change account_type or instrument_code after creation.
	UpdateInternalAccount(ctx context.Context, in *UpdateInternalAccountRequest, opts ...grpc.CallOption) (*UpdateInternalAccountResponse, error)
	// ControlInternalAccount performs lifecycle state transitions.
	// Supports SUSPEND, ACTIVATE, and CLOSE actions with audit trail.
	ControlInternalAccount(ctx context.Context, in *ControlInternalAccountRequest, opts ...grpc.CallOption) (*ControlInternalAccountResponse, error)
	// RetrieveInternalAccount fetches a single account by ID.
	RetrieveInternalAccount(ctx context.Context, in *RetrieveInternalAccountRequest, opts ...grpc.CallOption) (*RetrieveInternalAccountResponse, error)
	// ListInternalAccounts queries accounts with filtering and pagination.
	ListInternalAccounts(ctx context.Context, in *ListInternalAccountsRequest, opts ...grpc.CallOption) (*ListInternalAccountsResponse, error)
	// GetBalance queries the current balance for an internal account.
	// The balance is retrieved from Position Keeping service (source of truth).
	// Internal Account does not store balance locally - Position Keeping maintains
	// the transaction log and computes balances per BIAN architecture.
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	// CreateValuationFeature adds a valuation method assignment to an internal account.
	// The valuation feature maps an input instrument to the account's native instrument.
	// CRITICAL: The method's output_instrument MUST match the account's native instrument.
	// Returns FAILED_PRECONDITION if there's a mismatch (MethodOutputMismatchError).
	CreateValuationFeature(ctx context.Context, in *CreateValuationFeatureRequest, opts ...grpc.CallOption) (*CreateValuationFeatureResponse, error)
	// UpdateValuationFeature performs lifecycle transitions on a valuation feature.
	// Supports ACTIVATE (INITIATED -> ACTIVE) and TERMINATE (ACTIVE -> TERMINATED) actions.
	UpdateValuationFeature(ctx context.Context, in *UpdateValuationFeatureRequest, opts ...grpc.CallOption) (*UpdateValuationFeatureResponse, error)
	// GetValuationFeature retrieves a valuation feature by ID or by account+instrument with bi-temporal query.
	// Supports two query modes:
	// 1. By feature_id: Direct lookup
	// 2. By account_id + instrument_code + knowledge_at: Find the valid feature at a specific time
	GetValuationFeature(ctx context.Context, in *GetValuationFeatureRequest, opts ...grpc.CallOption) (*GetValuationFeatureResponse, error)
	// EvaluateAssetValuation performs an inquiry-only (non-binding) valuation.
	// Returns the estimated valued amount without creating any financial commitment.
	// CRITICAL: Uses the same valuateInternal() logic as binding operations to prevent Ghost Pricing -
	// ensuring inquiry and binding always produce identical results for identical inputs.
	EvaluateAssetValuation(ctx context.Context, in *EvaluateAssetValuationRequest, opts ...grpc.CallOption) (*EvaluateAssetValuationResponse, error)
	// ListValuationFeatures retrieves all valuation features for an internal account.
	// Optionally filters by lifecycle status.
	ListValuationFeatures(ctx context.Context, in *ListValuationFeaturesRequest, opts ...grpc.CallOption) (*ListValuationFeaturesResponse, error)
	// InitiateLien creates a new fund reservation on an internal account.
	// Supports multi-asset input with atomic valuation for cross-instrument liens.
	// CRITICAL: Uses valuateInternal() shared with EvaluateAssetValuation to prevent Ghost Pricing.
	InitiateLien(ctx context.Context, in *InitiateLienRequest, opts ...grpc.CallOption) (*InitiateLienResponse, error)
	// ExecuteLien converts a lien reservation to an actual debit.
	// Transitions lien from ACTIVE to EXECUTED (terminal, idempotent).
	ExecuteLien(ctx context.Context, in *ExecuteLienRequest, opts ...grpc.CallOption) (*ExecuteLienResponse, error)
	// TerminateLien releases reserved funds without executing.
	// Transitions lien from ACTIVE to TERMINATED (terminal, idempotent).
	TerminateLien(ctx context.Context, in *TerminateLienRequest, opts ...grpc.CallOption) (*TerminateLienResponse, error)
	// RetrieveLien fetches a lien by ID.
	RetrieveLien(ctx context.Context, in *RetrieveLienRequest, opts ...grpc.CallOption) (*RetrieveLienResponse, error)
}

type internalAccountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalAccountServiceClient(cc grpc.ClientConnInterface) InternalAccountServiceClient {
	return &internalAccountServiceClient{cc}
}

func (c *internalAccountServiceClient) InitiateInternalAccount(ctx context.Context, in *InitiateInternalAccountRequest, opts ...grpc.CallOption) (*InitiateInternalAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateInternalAccountResponse)
	err := c.cc.Invoke(ctx, InternalAccountService_InitiateInternalAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalAccountServiceClient) UpdateInternalAccount(ctx context.Context, in *UpdateInternalAccountRequest, opts ...grpc.CallOption) (*UpdateInternalAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInternalAccountResponse)
	err := c.cc.Invoke(ctx, InternalAccountService_UpdateInternalAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalAccountServiceClient) ControlInternalAccount(ctx context.Context, in *ControlInternalAccountRequest, opts ...grpc.CallOption) (*ControlInternalAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlInternalAccountResponse)
	err := c.cc.Invoke(ctx, InternalAccountService_ControlInternalAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalAccountServiceClient) RetrieveInternalAccount(ctx context.Context, in *RetrieveInternalAccountRequest, opts ...grpc.CallOption) (*RetrieveInternalAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveInternalAccountResponse)
	err := c.cc.Invoke(ctx, InternalAccountService_RetrieveInternalAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalAccountServiceClient) ListInternalAccounts(ctx context.Context, in *ListInternalAccountsRequest, opts ...grpc.CallOption) (*ListInternalAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInternalAccountsResponse)
	err := c.cc.Invoke(ctx, InternalAccountService_ListInternalAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalAccountServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, InternalAccountService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalAccountServiceClient) CreateValuationFeature(ctx context.Context, in *CreateValuationFeatureRequest, opts ...grpc.CallOption) (*CreateValuationFeatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateValuationFeatureResponse)
	err := c.cc.Invoke(ctx, InternalAccountService_CreateValuationFeature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalAccountServiceClient) UpdateValuationFeature(ctx context.Context, in *UpdateValuationFeatureRequest, opts ...grpc.CallOption) (*UpdateValuationFeatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateValuationFeatureResponse)
	err := c.cc.Invoke(ctx, InternalAccountService_UpdateValuationFeature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalAccountServiceClient) GetValuationFeature(ctx context.Context, in *GetValuationFeatureRequest, opts ...grpc.CallOption) (*GetValuationFeatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetValuationFeatureResponse)
	err := c.cc.Invoke(ctx, InternalAccountService_GetValuationFeature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalAccountServiceClient) EvaluateAssetValuation(ctx context.Context, in *EvaluateAssetValuationRequest, opts ...grpc.CallOption) (*EvaluateAssetValuationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateAssetValuationResponse)
	err := c.cc.Invoke(ctx, InternalAccountService_EvaluateAssetValuation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalAccountServiceClient) ListValuationFeatures(ctx context.Context, in *ListValuationFeaturesRequest, opts ...grpc.CallOption) (*ListValuationFeaturesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListValuationFeaturesResponse)
	err := c.cc.Invoke(ctx, InternalAccountService_ListValuationFeatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalAccountServiceClient) InitiateLien(ctx context.Context, in *InitiateLienRequest, opts ...grpc.CallOption) (*InitiateLienResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateLienResponse)
	err := c.cc.Invoke(ctx, InternalAccountService_InitiateLien_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalAccountServiceClient) ExecuteLien(ctx context.Context, in *ExecuteLienRequest, opts ...grpc.CallOption) (*ExecuteLienResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteLienResponse)
	err := c.cc.Invoke(ctx, InternalAccountService_ExecuteLien_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalAccountServiceClient) TerminateLien(ctx context.Context, in *TerminateLienRequest, opts ...grpc.CallOption) (*TerminateLienResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateLienResponse)
	err := c.cc.Invoke(ctx, InternalAccountService_TerminateLien_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalAccountServiceClient) RetrieveLien(ctx context.Context, in *RetrieveLienRequest, opts ...grpc.CallOption) (*RetrieveLienResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveLienResponse)
	err := c.cc.Invoke(ctx, InternalAccountService_RetrieveLien_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalAccountServiceServer is the server API for InternalAccountService service.
// All implementations must embed UnimplementedInternalAccountServiceServer
// for forward compatibility.
//
// InternalAccountService provides BIAN-compliant internal account operations.
// Internal accounts are non-customer-facing accounts used for operational purposes
// such as clearing, correspondent banking (nostro/vostro), holding, suspense, and GL entries.
//
// Design Notes:
//   - DELETE operations are intentionally not provided. Accounts are managed through
//     status transitions (Active -> Suspended -> Closed) for audit compliance.
//   - Balance queries route to Position Keeping service - internal accounts participate
//     in the universal position tracking system.
//   - No RecordPosting RPC - postings flow through Financial Accounting -> Position Keeping.
type InternalAccountServiceServer interface {
	// InitiateInternalAccount creates a new internal account.
	// The account is created in ACTIVE status.
	InitiateInternalAccount(context.Context, *InitiateInternalAccountRequest) (*InitiateInternalAccountResponse, error)
	// UpdateInternalAccount modifies account settings (partial update).
	// Cannot change account_type or instrument_code after creation.
	UpdateInternalAccount(context.Context, *UpdateInternalAccountRequest) (*UpdateInternalAccountResponse, error)
	// ControlInternalAccount performs lifecycle state transitions.
	// Supports SUSPEND, ACTIVATE, and CLOSE actions with audit trail.
	ControlInternalAccount(context.Context, *ControlInternalAccountRequest) (*ControlInternalAccountResponse, error)
	// RetrieveInternalAccount fetches a single account by ID.
	RetrieveInternalAccount(context.Context, *RetrieveInternalAccountRequest) (*RetrieveInternalAccountResponse, error)
	// ListInternalAccounts queries accounts with filtering and pagination.
	ListInternalAccounts(context.Context, *ListInternalAccountsRequest) (*ListInternalAccountsResponse, error)
	// GetBalance queries the current balance for an internal account.
	// The balance is retrieved from Position Keeping service (source of truth).
	// Internal Account does not store balance locally - Position Keeping maintains
	// the transaction log and computes balances per BIAN architecture.
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	// CreateValuationFeature adds a valuation method assignment to an internal account.
	// The valuation feature maps an input instrument to the account's native instrument.
	// CRITICAL: The method's output_instrument MUST match the account's native instrument.
	// Returns FAILED_PRECONDITION if there's a mismatch (MethodOutputMismatchError).
	CreateValuationFeature(context.Context, *CreateValuationFeatureRequest) (*CreateValuationFeatureResponse, error)
	// UpdateValuationFeature performs lifecycle transitions on a valuation feature.
	// Supports ACTIVATE (INITIATED -> ACTIVE) and TERMINATE (ACTIVE -> TERMINATED) actions.
	UpdateValuationFeature(context.Context, *UpdateValuationFeatureRequest) (*UpdateValuationFeatureResponse, error)
	// GetValuationFeature retrieves a valuation feature by ID or by account+instrument with bi-temporal query.
	// Supports two query modes:
	// 1. By feature_id: Direct lookup
	// 2. By account_id + instrument_code + knowledge_at: Find the valid feature at a specific time
	GetValuationFeature(context.Context, *GetValuationFeatureRequest) (*GetValuationFeatureResponse, error)
	// EvaluateAssetValuation performs an inquiry-only (non-binding) valuation.
	// Returns the estimated valued amount without creating any financial commitment.
	// CRITICAL: Uses the same valuateInternal() logic as binding operations to prevent Ghost Pricing -
	// ensuring inquiry and binding always produce identical results for identical inputs.
	EvaluateAssetValuation(context.Context, *EvaluateAssetValuationRequest) (*EvaluateAssetValuationResponse, error)
	// ListValuationFeatures retrieves all valuation features for an internal account.
	// Optionally filters by lifecycle status.
	ListValuationFeatures(context.Context, *ListValuationFeaturesRequest) (*ListValuationFeaturesResponse, error)
	// InitiateLien creates a new fund reservation on an internal account.
	// Supports multi-asset input with atomic valuation for cross-instrument liens.
	// CRITICAL: Uses valuateInternal() shared with EvaluateAssetValuation to prevent Ghost Pricing.
	InitiateLien(context.Context, *InitiateLienRequest) (*InitiateLienResponse, error)
	// ExecuteLien converts a lien reservation to an actual debit.
	// Transitions lien from ACTIVE to EXECUTED (terminal, idempotent).
	ExecuteLien(context.Context, *ExecuteLienRequest) (*ExecuteLienResponse, error)
	// TerminateLien releases reserved funds without executing.
	// Transitions lien from ACTIVE to TERMINATED (terminal, idempotent).
	TerminateLien(context.Context, *TerminateLienRequest) (*TerminateLienResponse, error)
	// RetrieveLien fetches a lien by ID.
	RetrieveLien(context.Context, *RetrieveLienRequest) (*RetrieveLienResponse, error)
	mustEmbedUnimplementedInternalAccountServiceServer()
}

// UnimplementedInternalAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalAccountServiceServer struct{}

func (UnimplementedInternalAccountServiceServer) InitiateInternalAccount(context.Context, *InitiateInternalAccountRequest) (*InitiateInternalAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateInternalAccount not implemented")
}
func (UnimplementedInternalAccountServiceServer) UpdateInternalAccount(context.Context, *UpdateInternalAccountRequest) (*UpdateInternalAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInternalAccount not implemented")
}
func (UnimplementedInternalAccountServiceServer) ControlInternalAccount(context.Context, *ControlInternalAccountRequest) (*ControlInternalAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ControlInternalAccount not implemented")
}
func (UnimplementedInternalAccountServiceServer) RetrieveInternalAccount(context.Context, *RetrieveInternalAccountRequest) (*RetrieveInternalAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveInternalAccount not implemented")
}
func (UnimplementedInternalAccountServiceServer) ListInternalAccounts(context.Context, *ListInternalAccountsRequest) (*ListInternalAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInternalAccounts not implemented")
}
func (UnimplementedInternalAccountServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedInternalAccountServiceServer) CreateValuationFeature(context.Context, *CreateValuationFeatureRequest) (*CreateValuationFeatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateValuationFeature not implemented")
}
func (UnimplementedInternalAccountServiceServer) UpdateValuationFeature(context.Context, *UpdateValuationFeatureRequest) (*UpdateValuationFeatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateValuationFeature not implemented")
}
func (UnimplementedInternalAccountServiceServer) GetValuationFeature(context.Context, *GetValuationFeatureRequest) (*GetValuationFeatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValuationFeature not implemented")
}
func (UnimplementedInternalAccountServiceServer) EvaluateAssetValuation(context.Context, *EvaluateAssetValuationRequest) (*EvaluateAssetValuationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateAssetValuation not implemented")
}
func (UnimplementedInternalAccountServiceServer) ListValuationFeatures(context.Context, *ListValuationFeaturesRequest) (*ListValuationFeaturesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListValuationFeatures not implemented")
}
func (UnimplementedInternalAccountServiceServer) InitiateLien(context.Context, *InitiateLienRequest) (*InitiateLienResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateLien not implemented")
}
func (UnimplementedInternalAccountServiceServer) ExecuteLien(context.Context, *ExecuteLienRequest) (*ExecuteLienResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteLien not implemented")
}
func (UnimplementedInternalAccountServiceServer) TerminateLien(context.Context, *TerminateLienRequest) (*TerminateLienResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TerminateLien not implemented")
}
func (UnimplementedInternalAccountServiceServer) RetrieveLien(context.Context, *RetrieveLienRequest) (*RetrieveLienResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveLien not implemented")
}
func (UnimplementedInternalAccountServiceServer) mustEmbedUnimplementedInternalAccountServiceServer() {
}
func (UnimplementedInternalAccountServiceServer) testEmbeddedByValue() {}

// UnsafeInternalAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalAccountServiceServer will
// result in compilation errors.
type UnsafeInternalAccountServiceServer interface {
	mustEmbedUnimplementedInternalAccountServiceServer()
}

func RegisterInternalAccountServiceServer(s grpc.ServiceRegistrar, srv InternalAccountServiceServer) {
	// If the following call pancis, it indicates UnimplementedInternalAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalAccountService_ServiceDesc, srv)
}

func _InternalAccountService_InitiateInternalAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateInternalAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalAccountServiceServer).InitiateInternalAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalAccountService_InitiateInternalAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalAccountServiceServer).InitiateInternalAccount(ctx, req.(*InitiateInternalAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalAccountService_UpdateInternalAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInternalAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalAccountServiceServer).UpdateInternalAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalAccountService_UpdateInternalAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalAccountServiceServer).UpdateInternalAccount(ctx, req.(*UpdateInternalAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalAccountService_ControlInternalAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlInternalAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalAccountServiceServer).ControlInternalAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalAccountService_ControlInternalAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalAccountServiceServer).ControlInternalAccount(ctx, req.(*ControlInternalAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalAccountService_RetrieveInternalAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveInternalAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalAccountServiceServer).RetrieveInternalAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalAccountService_RetrieveInternalAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalAccountServiceServer).RetrieveInternalAccount(ctx, req.(*RetrieveInternalAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalAccountService_ListInternalAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInternalAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalAccountServiceServer).ListInternalAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalAccountService_ListInternalAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalAccountServiceServer).ListInternalAccounts(ctx, req.(*ListInternalAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalAccountService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalAccountServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalAccountService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalAccountServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalAccountService_CreateValuationFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateValuationFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalAccountServiceServer).CreateValuationFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalAccountService_CreateValuationFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalAccountServiceServer).CreateValuationFeature(ctx, req.(*CreateValuationFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalAccountService_UpdateValuationFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateValuationFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalAccountServiceServer).UpdateValuationFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalAccountService_UpdateValuationFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalAccountServiceServer).UpdateValuationFeature(ctx, req.(*UpdateValuationFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalAccountService_GetValuationFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValuationFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalAccountServiceServer).GetValuationFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalAccountService_GetValuationFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalAccountServiceServer).GetValuationFeature(ctx, req.(*GetValuationFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalAccountService_EvaluateAssetValuation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateAssetValuationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalAccountServiceServer).EvaluateAssetValuation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalAccountService_EvaluateAssetValuation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalAccountServiceServer).EvaluateAssetValuation(ctx, req.(*EvaluateAssetValuationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalAccountService_ListValuationFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListValuationFeaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalAccountServiceServer).ListValuationFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalAccountService_ListValuationFeatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalAccountServiceServer).ListValuationFeatures(ctx, req.(*ListValuationFeaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalAccountService_InitiateLien_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateLienRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalAccountServiceServer).InitiateLien(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalAccountService_InitiateLien_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalAccountServiceServer).InitiateLien(ctx, req.(*InitiateLienRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalAccountService_ExecuteLien_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteLienRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalAccountServiceServer).ExecuteLien(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalAccountService_ExecuteLien_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalAccountServiceServer).ExecuteLien(ctx, req.(*ExecuteLienRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalAccountService_TerminateLien_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateLienRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalAccountServiceServer).TerminateLien(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalAccountService_TerminateLien_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalAccountServiceServer).TerminateLien(ctx, req.(*TerminateLienRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalAccountService_RetrieveLien_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveLienRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalAccountServiceServer).RetrieveLien(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalAccountService_RetrieveLien_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalAccountServiceServer).RetrieveLien(ctx, req.(*RetrieveLienRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalAccountService_ServiceDesc is the grpc.ServiceDesc for InternalAccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalAccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meridian.internal_account.v1.InternalAccountService",
	HandlerType: (*InternalAccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateInternalAccount",
			Handler:    _InternalAccountService_InitiateInternalAccount_Handler,
		},
		{
			MethodName: "UpdateInternalAccount",
			Handler:    _InternalAccountService_UpdateInternalAccount_Handler,
		},
		{
			MethodName: "ControlInternalAccount",
			Handler:    _InternalAccountService_ControlInternalAccount_Handler,
		},
		{
			MethodName: "RetrieveInternalAccount",
			Handler:    _InternalAccountService_RetrieveInternalAccount_Handler,
		},
		{
			MethodName: "ListInternalAccounts",
			Handler:    _InternalAccountService_ListInternalAccounts_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _InternalAccountService_GetBalance_Handler,
		},
		{
			MethodName: "CreateValuationFeature",
			Handler:    _InternalAccountService_CreateValuationFeature_Handler,
		},
		{
			MethodName: "UpdateValuationFeature",
			Handler:    _InternalAccountService_UpdateValuationFeature_Handler,
		},
		{
			MethodName: "GetValuationFeature",
			Handler:    _InternalAccountService_GetValuationFeature_Handler,
		},
		{
			MethodName: "EvaluateAssetValuation",
			Handler:    _InternalAccountService_EvaluateAssetValuation_Handler,
		},
		{
			MethodName: "ListValuationFeatures",
			Handler:    _InternalAccountService_ListValuationFeatures_Handler,
		},
		{
			MethodName: "InitiateLien",
			Handler:    _InternalAccountService_InitiateLien_Handler,
		},
		{
			MethodName: "ExecuteLien",
			Handler:    _InternalAccountService_ExecuteLien_Handler,
		},
		{
			MethodName: "TerminateLien",
			Handler:    _InternalAccountService_TerminateLien_Handler,
		},
		{
			MethodName: "RetrieveLien",
			Handler:    _InternalAccountService_RetrieveLien_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meridian/internal_account/v1/internal_account.proto",
}
