package email_test

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"testing"

	"github.com/google/uuid"
	"github.com/meridianhub/meridian/shared/pkg/email"
	"github.com/meridianhub/meridian/shared/pkg/saga"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// mockOutboxRepository implements email.OutboxRepository for testing.
type mockOutboxRepository struct {
	enqueueFunc                       func(ctx context.Context, entry *email.OutboxEntry) error
	cancelByIdempotencyKeyPatternFunc func(ctx context.Context, pattern string) (int64, error)
	enqueuedEntries                   []*email.OutboxEntry
}

func (m *mockOutboxRepository) Enqueue(ctx context.Context, entry *email.OutboxEntry) error {
	m.enqueuedEntries = append(m.enqueuedEntries, entry)
	if m.enqueueFunc != nil {
		return m.enqueueFunc(ctx, entry)
	}
	entry.ID = uuid.New()
	return nil
}

func (m *mockOutboxRepository) FetchDispatchable(_ context.Context, _ int) ([]email.OutboxEntry, error) {
	return nil, nil
}

func (m *mockOutboxRepository) MarkSent(_ context.Context, _ uuid.UUID) error { return nil }
func (m *mockOutboxRepository) MarkFailed(_ context.Context, _ uuid.UUID, _ string) error {
	return nil
}
func (m *mockOutboxRepository) Cancel(_ context.Context, _ uuid.UUID) error { return nil }

func (m *mockOutboxRepository) CancelByIdempotencyKeyPattern(ctx context.Context, pattern string) (int64, error) {
	if m.cancelByIdempotencyKeyPatternFunc != nil {
		return m.cancelByIdempotencyKeyPatternFunc(ctx, pattern)
	}
	return 0, nil
}

// mockEmailResolver implements email.PartyEmailResolver for testing.
type mockEmailResolver struct {
	resolveFunc func(ctx context.Context, partyID string) (string, error)
}

func (m *mockEmailResolver) ResolveEmail(ctx context.Context, partyID string) (string, error) {
	if m.resolveFunc != nil {
		return m.resolveFunc(ctx, partyID)
	}
	return partyID + "@example.com", nil
}

func newTestStarlarkContext() *saga.StarlarkContext {
	return &saga.StarlarkContext{
		Context:         context.Background(),
		SagaExecutionID: uuid.New(),
		IdempotencyKey:  "step_1",
		Logger:          slog.Default(),
	}
}

func TestNotificationSendHandler_EmailType(t *testing.T) {
	outbox := &mockOutboxRepository{}
	resolver := &mockEmailResolver{}
	handler := email.NewNotificationSendHandler(email.NotificationHandlerDeps{
		Outbox:        outbox,
		EmailResolver: resolver,
		Logger:        slog.Default(),
	})

	ctx := newTestStarlarkContext()
	result, err := handler(ctx, map[string]any{
		"type":      "EMAIL",
		"recipient": "party-123",
		"template":  "dunning-notice",
		"data":      map[string]any{"severity": 1},
	})

	require.NoError(t, err)
	resultMap, ok := result.(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "QUEUED", resultMap["status"])
	assert.NotEmpty(t, resultMap["outbox_id"])
	assert.NotEmpty(t, resultMap["idempotency_key"])

	// Verify outbox entry
	require.Len(t, outbox.enqueuedEntries, 1)
	entry := outbox.enqueuedEntries[0]
	assert.Equal(t, []string{"party-123@example.com"}, entry.ToAddresses)
	assert.Equal(t, "dunning-notice", entry.TemplateName)
	assert.Equal(t, 1, entry.TemplateData["severity"])
}

func TestNotificationSendHandler_NonEmailTypeReturnsError(t *testing.T) {
	outbox := &mockOutboxRepository{}
	resolver := &mockEmailResolver{}
	handler := email.NewNotificationSendHandler(email.NotificationHandlerDeps{
		Outbox:        outbox,
		EmailResolver: resolver,
		Logger:        slog.Default(),
	})

	ctx := newTestStarlarkContext()
	_, err := handler(ctx, map[string]any{
		"type":      "SMS",
		"recipient": "party-123",
	})

	require.Error(t, err)
	assert.ErrorIs(t, err, email.ErrUnsupportedNotificationType)
}

func TestNotificationSendHandler_MissingType(t *testing.T) {
	handler := email.NewNotificationSendHandler(email.NotificationHandlerDeps{
		Outbox:        &mockOutboxRepository{},
		EmailResolver: &mockEmailResolver{},
		Logger:        slog.Default(),
	})

	ctx := newTestStarlarkContext()
	_, err := handler(ctx, map[string]any{
		"recipient": "party-123",
	})

	require.Error(t, err)
	assert.ErrorIs(t, err, email.ErrMissingType)
}

func TestNotificationSendHandler_MissingRecipient(t *testing.T) {
	handler := email.NewNotificationSendHandler(email.NotificationHandlerDeps{
		Outbox:        &mockOutboxRepository{},
		EmailResolver: &mockEmailResolver{},
		Logger:        slog.Default(),
	})

	ctx := newTestStarlarkContext()
	_, err := handler(ctx, map[string]any{
		"type": "EMAIL",
	})

	require.Error(t, err)
	assert.ErrorIs(t, err, email.ErrMissingRecipient)
}

func TestNotificationSendHandler_IdempotencyKeyAutoGenerated(t *testing.T) {
	outbox := &mockOutboxRepository{}
	handler := email.NewNotificationSendHandler(email.NotificationHandlerDeps{
		Outbox:        outbox,
		EmailResolver: &mockEmailResolver{},
		Logger:        slog.Default(),
	})

	ctx := newTestStarlarkContext()
	result, err := handler(ctx, map[string]any{
		"type":      "EMAIL",
		"recipient": "party-123",
	})

	require.NoError(t, err)
	resultMap := result.(map[string]any)
	expectedKey := fmt.Sprintf("saga_%s_step_%s", ctx.SagaExecutionID.String(), ctx.IdempotencyKey)
	assert.Equal(t, expectedKey, resultMap["idempotency_key"])
	assert.Equal(t, expectedKey, outbox.enqueuedEntries[0].IdempotencyKey)
}

func TestNotificationSendHandler_ExplicitIdempotencyKey(t *testing.T) {
	outbox := &mockOutboxRepository{}
	handler := email.NewNotificationSendHandler(email.NotificationHandlerDeps{
		Outbox:        outbox,
		EmailResolver: &mockEmailResolver{},
		Logger:        slog.Default(),
	})

	ctx := newTestStarlarkContext()
	result, err := handler(ctx, map[string]any{
		"type":            "EMAIL",
		"recipient":       "party-123",
		"idempotency_key": "dunning-1-billing-run-abc",
	})

	require.NoError(t, err)
	resultMap := result.(map[string]any)
	assert.Equal(t, "dunning-1-billing-run-abc", resultMap["idempotency_key"])
}

func TestNotificationSendHandler_DuplicateIdempotencyIsNotError(t *testing.T) {
	outboxID := uuid.New()
	outbox := &mockOutboxRepository{
		enqueueFunc: func(_ context.Context, entry *email.OutboxEntry) error {
			entry.ID = outboxID
			return fmt.Errorf("%w: %q", email.ErrDuplicateIdempotency, entry.IdempotencyKey)
		},
	}
	handler := email.NewNotificationSendHandler(email.NotificationHandlerDeps{
		Outbox:        outbox,
		EmailResolver: &mockEmailResolver{},
		Logger:        slog.Default(),
	})

	ctx := newTestStarlarkContext()
	result, err := handler(ctx, map[string]any{
		"type":      "EMAIL",
		"recipient": "party-123",
	})

	require.NoError(t, err)
	resultMap := result.(map[string]any)
	assert.Equal(t, "QUEUED", resultMap["status"])
	assert.Equal(t, true, resultMap["replay"])
}

func TestNotificationSendHandler_EmailResolverError(t *testing.T) {
	resolver := &mockEmailResolver{
		resolveFunc: func(_ context.Context, _ string) (string, error) {
			return "", errors.New("party not found")
		},
	}
	handler := email.NewNotificationSendHandler(email.NotificationHandlerDeps{
		Outbox:        &mockOutboxRepository{},
		EmailResolver: resolver,
		Logger:        slog.Default(),
	})

	ctx := newTestStarlarkContext()
	_, err := handler(ctx, map[string]any{
		"type":      "EMAIL",
		"recipient": "unknown-party",
	})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "failed to resolve email")
}

func TestNotificationSendHandler_DefaultTemplate(t *testing.T) {
	outbox := &mockOutboxRepository{}
	handler := email.NewNotificationSendHandler(email.NotificationHandlerDeps{
		Outbox:        outbox,
		EmailResolver: &mockEmailResolver{},
		Logger:        slog.Default(),
	})

	ctx := newTestStarlarkContext()
	_, err := handler(ctx, map[string]any{
		"type":      "EMAIL",
		"recipient": "party-123",
	})

	require.NoError(t, err)
	require.Len(t, outbox.enqueuedEntries, 1)
	assert.Equal(t, "generic-notification", outbox.enqueuedEntries[0].TemplateName)
}

func TestNotificationSendHandler_SubjectGeneration(t *testing.T) {
	tests := []struct {
		name     string
		template string
		data     map[string]any
		expected string
	}{
		{
			name:     "dunning notice",
			template: "dunning-notice",
			data:     map[string]any{"severity": 2},
			expected: "Payment reminder - severity 2",
		},
		{
			name:     "account frozen",
			template: "account-frozen",
			data:     nil,
			expected: "Your account has been frozen",
		},
		{
			name:     "generic template",
			template: "custom-template",
			data:     nil,
			expected: "Notification: custom-template",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			outbox := &mockOutboxRepository{}
			handler := email.NewNotificationSendHandler(email.NotificationHandlerDeps{
				Outbox:        outbox,
				EmailResolver: &mockEmailResolver{},
				Logger:        slog.Default(),
			})

			params := map[string]any{
				"type":      "EMAIL",
				"recipient": "party-123",
				"template":  tc.template,
			}
			if tc.data != nil {
				params["data"] = tc.data
			}

			_, err := handler(newTestStarlarkContext(), params)
			require.NoError(t, err)
			require.Len(t, outbox.enqueuedEntries, 1)
			assert.Equal(t, tc.expected, outbox.enqueuedEntries[0].Subject)
		})
	}
}
