// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: meridian/financial_accounting/v1/financial_accounting.proto

package financialaccountingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FinancialAccountingService_InitiateFinancialBookingLog_FullMethodName = "/meridian.financial_accounting.v1.FinancialAccountingService/InitiateFinancialBookingLog"
	FinancialAccountingService_UpdateFinancialBookingLog_FullMethodName   = "/meridian.financial_accounting.v1.FinancialAccountingService/UpdateFinancialBookingLog"
	FinancialAccountingService_RetrieveFinancialBookingLog_FullMethodName = "/meridian.financial_accounting.v1.FinancialAccountingService/RetrieveFinancialBookingLog"
	FinancialAccountingService_ListFinancialBookingLogs_FullMethodName    = "/meridian.financial_accounting.v1.FinancialAccountingService/ListFinancialBookingLogs"
	FinancialAccountingService_CaptureLedgerPosting_FullMethodName        = "/meridian.financial_accounting.v1.FinancialAccountingService/CaptureLedgerPosting"
	FinancialAccountingService_RetrieveLedgerPosting_FullMethodName       = "/meridian.financial_accounting.v1.FinancialAccountingService/RetrieveLedgerPosting"
)

// FinancialAccountingServiceClient is the client API for FinancialAccountingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FinancialAccountingService provides the BIAN Financial Accounting service interface.
type FinancialAccountingServiceClient interface {
	// InitiateFinancialBookingLog creates a new financial booking log.
	InitiateFinancialBookingLog(ctx context.Context, in *InitiateFinancialBookingLogRequest, opts ...grpc.CallOption) (*InitiateFinancialBookingLogResponse, error)
	// UpdateFinancialBookingLog updates an existing booking log.
	UpdateFinancialBookingLog(ctx context.Context, in *UpdateFinancialBookingLogRequest, opts ...grpc.CallOption) (*UpdateFinancialBookingLogResponse, error)
	// RetrieveFinancialBookingLog retrieves a specific booking log.
	RetrieveFinancialBookingLog(ctx context.Context, in *RetrieveFinancialBookingLogRequest, opts ...grpc.CallOption) (*RetrieveFinancialBookingLogResponse, error)
	// ListFinancialBookingLogs lists booking logs with optional filtering.
	ListFinancialBookingLogs(ctx context.Context, in *ListFinancialBookingLogsRequest, opts ...grpc.CallOption) (*ListFinancialBookingLogsResponse, error)
	// CaptureLedgerPosting creates a new ledger posting.
	CaptureLedgerPosting(ctx context.Context, in *CaptureLedgerPostingRequest, opts ...grpc.CallOption) (*CaptureLedgerPostingResponse, error)
	// RetrieveLedgerPosting retrieves a specific posting.
	RetrieveLedgerPosting(ctx context.Context, in *RetrieveLedgerPostingRequest, opts ...grpc.CallOption) (*RetrieveLedgerPostingResponse, error)
}

type financialAccountingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFinancialAccountingServiceClient(cc grpc.ClientConnInterface) FinancialAccountingServiceClient {
	return &financialAccountingServiceClient{cc}
}

func (c *financialAccountingServiceClient) InitiateFinancialBookingLog(ctx context.Context, in *InitiateFinancialBookingLogRequest, opts ...grpc.CallOption) (*InitiateFinancialBookingLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateFinancialBookingLogResponse)
	err := c.cc.Invoke(ctx, FinancialAccountingService_InitiateFinancialBookingLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialAccountingServiceClient) UpdateFinancialBookingLog(ctx context.Context, in *UpdateFinancialBookingLogRequest, opts ...grpc.CallOption) (*UpdateFinancialBookingLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFinancialBookingLogResponse)
	err := c.cc.Invoke(ctx, FinancialAccountingService_UpdateFinancialBookingLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialAccountingServiceClient) RetrieveFinancialBookingLog(ctx context.Context, in *RetrieveFinancialBookingLogRequest, opts ...grpc.CallOption) (*RetrieveFinancialBookingLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveFinancialBookingLogResponse)
	err := c.cc.Invoke(ctx, FinancialAccountingService_RetrieveFinancialBookingLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialAccountingServiceClient) ListFinancialBookingLogs(ctx context.Context, in *ListFinancialBookingLogsRequest, opts ...grpc.CallOption) (*ListFinancialBookingLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFinancialBookingLogsResponse)
	err := c.cc.Invoke(ctx, FinancialAccountingService_ListFinancialBookingLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialAccountingServiceClient) CaptureLedgerPosting(ctx context.Context, in *CaptureLedgerPostingRequest, opts ...grpc.CallOption) (*CaptureLedgerPostingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureLedgerPostingResponse)
	err := c.cc.Invoke(ctx, FinancialAccountingService_CaptureLedgerPosting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialAccountingServiceClient) RetrieveLedgerPosting(ctx context.Context, in *RetrieveLedgerPostingRequest, opts ...grpc.CallOption) (*RetrieveLedgerPostingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveLedgerPostingResponse)
	err := c.cc.Invoke(ctx, FinancialAccountingService_RetrieveLedgerPosting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinancialAccountingServiceServer is the server API for FinancialAccountingService service.
// All implementations must embed UnimplementedFinancialAccountingServiceServer
// for forward compatibility.
//
// FinancialAccountingService provides the BIAN Financial Accounting service interface.
type FinancialAccountingServiceServer interface {
	// InitiateFinancialBookingLog creates a new financial booking log.
	InitiateFinancialBookingLog(context.Context, *InitiateFinancialBookingLogRequest) (*InitiateFinancialBookingLogResponse, error)
	// UpdateFinancialBookingLog updates an existing booking log.
	UpdateFinancialBookingLog(context.Context, *UpdateFinancialBookingLogRequest) (*UpdateFinancialBookingLogResponse, error)
	// RetrieveFinancialBookingLog retrieves a specific booking log.
	RetrieveFinancialBookingLog(context.Context, *RetrieveFinancialBookingLogRequest) (*RetrieveFinancialBookingLogResponse, error)
	// ListFinancialBookingLogs lists booking logs with optional filtering.
	ListFinancialBookingLogs(context.Context, *ListFinancialBookingLogsRequest) (*ListFinancialBookingLogsResponse, error)
	// CaptureLedgerPosting creates a new ledger posting.
	CaptureLedgerPosting(context.Context, *CaptureLedgerPostingRequest) (*CaptureLedgerPostingResponse, error)
	// RetrieveLedgerPosting retrieves a specific posting.
	RetrieveLedgerPosting(context.Context, *RetrieveLedgerPostingRequest) (*RetrieveLedgerPostingResponse, error)
	mustEmbedUnimplementedFinancialAccountingServiceServer()
}

// UnimplementedFinancialAccountingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFinancialAccountingServiceServer struct{}

func (UnimplementedFinancialAccountingServiceServer) InitiateFinancialBookingLog(context.Context, *InitiateFinancialBookingLogRequest) (*InitiateFinancialBookingLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateFinancialBookingLog not implemented")
}
func (UnimplementedFinancialAccountingServiceServer) UpdateFinancialBookingLog(context.Context, *UpdateFinancialBookingLogRequest) (*UpdateFinancialBookingLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFinancialBookingLog not implemented")
}
func (UnimplementedFinancialAccountingServiceServer) RetrieveFinancialBookingLog(context.Context, *RetrieveFinancialBookingLogRequest) (*RetrieveFinancialBookingLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveFinancialBookingLog not implemented")
}
func (UnimplementedFinancialAccountingServiceServer) ListFinancialBookingLogs(context.Context, *ListFinancialBookingLogsRequest) (*ListFinancialBookingLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFinancialBookingLogs not implemented")
}
func (UnimplementedFinancialAccountingServiceServer) CaptureLedgerPosting(context.Context, *CaptureLedgerPostingRequest) (*CaptureLedgerPostingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CaptureLedgerPosting not implemented")
}
func (UnimplementedFinancialAccountingServiceServer) RetrieveLedgerPosting(context.Context, *RetrieveLedgerPostingRequest) (*RetrieveLedgerPostingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveLedgerPosting not implemented")
}
func (UnimplementedFinancialAccountingServiceServer) mustEmbedUnimplementedFinancialAccountingServiceServer() {
}
func (UnimplementedFinancialAccountingServiceServer) testEmbeddedByValue() {}

// UnsafeFinancialAccountingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinancialAccountingServiceServer will
// result in compilation errors.
type UnsafeFinancialAccountingServiceServer interface {
	mustEmbedUnimplementedFinancialAccountingServiceServer()
}

func RegisterFinancialAccountingServiceServer(s grpc.ServiceRegistrar, srv FinancialAccountingServiceServer) {
	// If the following call pancis, it indicates UnimplementedFinancialAccountingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FinancialAccountingService_ServiceDesc, srv)
}

func _FinancialAccountingService_InitiateFinancialBookingLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateFinancialBookingLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialAccountingServiceServer).InitiateFinancialBookingLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialAccountingService_InitiateFinancialBookingLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialAccountingServiceServer).InitiateFinancialBookingLog(ctx, req.(*InitiateFinancialBookingLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialAccountingService_UpdateFinancialBookingLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFinancialBookingLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialAccountingServiceServer).UpdateFinancialBookingLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialAccountingService_UpdateFinancialBookingLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialAccountingServiceServer).UpdateFinancialBookingLog(ctx, req.(*UpdateFinancialBookingLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialAccountingService_RetrieveFinancialBookingLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveFinancialBookingLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialAccountingServiceServer).RetrieveFinancialBookingLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialAccountingService_RetrieveFinancialBookingLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialAccountingServiceServer).RetrieveFinancialBookingLog(ctx, req.(*RetrieveFinancialBookingLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialAccountingService_ListFinancialBookingLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFinancialBookingLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialAccountingServiceServer).ListFinancialBookingLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialAccountingService_ListFinancialBookingLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialAccountingServiceServer).ListFinancialBookingLogs(ctx, req.(*ListFinancialBookingLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialAccountingService_CaptureLedgerPosting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureLedgerPostingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialAccountingServiceServer).CaptureLedgerPosting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialAccountingService_CaptureLedgerPosting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialAccountingServiceServer).CaptureLedgerPosting(ctx, req.(*CaptureLedgerPostingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialAccountingService_RetrieveLedgerPosting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveLedgerPostingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialAccountingServiceServer).RetrieveLedgerPosting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialAccountingService_RetrieveLedgerPosting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialAccountingServiceServer).RetrieveLedgerPosting(ctx, req.(*RetrieveLedgerPostingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FinancialAccountingService_ServiceDesc is the grpc.ServiceDesc for FinancialAccountingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FinancialAccountingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meridian.financial_accounting.v1.FinancialAccountingService",
	HandlerType: (*FinancialAccountingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateFinancialBookingLog",
			Handler:    _FinancialAccountingService_InitiateFinancialBookingLog_Handler,
		},
		{
			MethodName: "UpdateFinancialBookingLog",
			Handler:    _FinancialAccountingService_UpdateFinancialBookingLog_Handler,
		},
		{
			MethodName: "RetrieveFinancialBookingLog",
			Handler:    _FinancialAccountingService_RetrieveFinancialBookingLog_Handler,
		},
		{
			MethodName: "ListFinancialBookingLogs",
			Handler:    _FinancialAccountingService_ListFinancialBookingLogs_Handler,
		},
		{
			MethodName: "CaptureLedgerPosting",
			Handler:    _FinancialAccountingService_CaptureLedgerPosting_Handler,
		},
		{
			MethodName: "RetrieveLedgerPosting",
			Handler:    _FinancialAccountingService_RetrieveLedgerPosting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meridian/financial_accounting/v1/financial_accounting.proto",
}
