// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: meridian/tenant/v1/tenant.proto

package tenantv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TenantService_InitiateTenant_FullMethodName              = "/meridian.tenant.v1.TenantService/InitiateTenant"
	TenantService_RetrieveTenant_FullMethodName              = "/meridian.tenant.v1.TenantService/RetrieveTenant"
	TenantService_UpdateTenantStatus_FullMethodName          = "/meridian.tenant.v1.TenantService/UpdateTenantStatus"
	TenantService_ListTenants_FullMethodName                 = "/meridian.tenant.v1.TenantService/ListTenants"
	TenantService_ReconcileMigrations_FullMethodName         = "/meridian.tenant.v1.TenantService/ReconcileMigrations"
	TenantService_GetTenantProvisioningStatus_FullMethodName = "/meridian.tenant.v1.TenantService/GetTenantProvisioningStatus"
)

// TenantServiceClient is the client API for TenantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TenantService provides platform tenant lifecycle management.
//
// Design Notes:
//   - DELETE operations are intentionally not provided. Tenants are managed
//     through status transitions (Active -> Suspended -> Deprovisioned) for audit compliance.
//   - This service manages platform infrastructure tenants, distinct from BIAN Party domain entities.
//   - Tenants map to PostgreSQL schemas (org_{id}) for data isolation.
type TenantServiceClient interface {
	// InitiateTenant creates a new tenant in the platform registry (BIAN: Initiate).
	//
	// This operation may complete synchronously or asynchronously depending on system load.
	// Always check the provisioning_hint field in the response to determine next steps.
	InitiateTenant(ctx context.Context, in *InitiateTenantRequest, opts ...grpc.CallOption) (*InitiateTenantResponse, error)
	// RetrieveTenant gets tenant details by ID (BIAN: Retrieve).
	//
	// This endpoint is used for:
	// 1. Retrieving current tenant details
	// 2. Polling provisioning status when InitiateTenant returns provisioning_hint="pending"
	//
	// When polling for provisioning completion:
	// - Use exponential backoff (start at 1s, max 30s interval)
	// - Check tenant.status field for current state
	// - Stop polling when status becomes ACTIVE or PROVISIONING_FAILED
	// - If PROVISIONING_FAILED, check tenant.error_message for details
	RetrieveTenant(ctx context.Context, in *RetrieveTenantRequest, opts ...grpc.CallOption) (*RetrieveTenantResponse, error)
	// UpdateTenantStatus changes the lifecycle status of a tenant (BIAN: Update).
	UpdateTenantStatus(ctx context.Context, in *UpdateTenantStatusRequest, opts ...grpc.CallOption) (*UpdateTenantStatusResponse, error)
	// ListTenants returns all tenants with optional status filter (BIAN: Control).
	ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsResponse, error)
	// ReconcileMigrations applies new migrations to existing tenant schemas.
	// When services add new migrations after tenants are created, existing tenant
	// schemas may be missing these migrations. This operation detects and applies
	// new migrations to bring tenant schemas up to date.
	ReconcileMigrations(ctx context.Context, in *ReconcileMigrationsRequest, opts ...grpc.CallOption) (*ReconcileMigrationsResponse, error)
	// GetTenantProvisioningStatus retrieves detailed provisioning status for a tenant.
	// Returns per-service provisioning progress including migration versions and error details.
	GetTenantProvisioningStatus(ctx context.Context, in *GetTenantProvisioningStatusRequest, opts ...grpc.CallOption) (*GetTenantProvisioningStatusResponse, error)
}

type tenantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantServiceClient(cc grpc.ClientConnInterface) TenantServiceClient {
	return &tenantServiceClient{cc}
}

func (c *tenantServiceClient) InitiateTenant(ctx context.Context, in *InitiateTenantRequest, opts ...grpc.CallOption) (*InitiateTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateTenantResponse)
	err := c.cc.Invoke(ctx, TenantService_InitiateTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) RetrieveTenant(ctx context.Context, in *RetrieveTenantRequest, opts ...grpc.CallOption) (*RetrieveTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveTenantResponse)
	err := c.cc.Invoke(ctx, TenantService_RetrieveTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) UpdateTenantStatus(ctx context.Context, in *UpdateTenantStatusRequest, opts ...grpc.CallOption) (*UpdateTenantStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTenantStatusResponse)
	err := c.cc.Invoke(ctx, TenantService_UpdateTenantStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTenantsResponse)
	err := c.cc.Invoke(ctx, TenantService_ListTenants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) ReconcileMigrations(ctx context.Context, in *ReconcileMigrationsRequest, opts ...grpc.CallOption) (*ReconcileMigrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconcileMigrationsResponse)
	err := c.cc.Invoke(ctx, TenantService_ReconcileMigrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) GetTenantProvisioningStatus(ctx context.Context, in *GetTenantProvisioningStatusRequest, opts ...grpc.CallOption) (*GetTenantProvisioningStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTenantProvisioningStatusResponse)
	err := c.cc.Invoke(ctx, TenantService_GetTenantProvisioningStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantServiceServer is the server API for TenantService service.
// All implementations must embed UnimplementedTenantServiceServer
// for forward compatibility.
//
// TenantService provides platform tenant lifecycle management.
//
// Design Notes:
//   - DELETE operations are intentionally not provided. Tenants are managed
//     through status transitions (Active -> Suspended -> Deprovisioned) for audit compliance.
//   - This service manages platform infrastructure tenants, distinct from BIAN Party domain entities.
//   - Tenants map to PostgreSQL schemas (org_{id}) for data isolation.
type TenantServiceServer interface {
	// InitiateTenant creates a new tenant in the platform registry (BIAN: Initiate).
	//
	// This operation may complete synchronously or asynchronously depending on system load.
	// Always check the provisioning_hint field in the response to determine next steps.
	InitiateTenant(context.Context, *InitiateTenantRequest) (*InitiateTenantResponse, error)
	// RetrieveTenant gets tenant details by ID (BIAN: Retrieve).
	//
	// This endpoint is used for:
	// 1. Retrieving current tenant details
	// 2. Polling provisioning status when InitiateTenant returns provisioning_hint="pending"
	//
	// When polling for provisioning completion:
	// - Use exponential backoff (start at 1s, max 30s interval)
	// - Check tenant.status field for current state
	// - Stop polling when status becomes ACTIVE or PROVISIONING_FAILED
	// - If PROVISIONING_FAILED, check tenant.error_message for details
	RetrieveTenant(context.Context, *RetrieveTenantRequest) (*RetrieveTenantResponse, error)
	// UpdateTenantStatus changes the lifecycle status of a tenant (BIAN: Update).
	UpdateTenantStatus(context.Context, *UpdateTenantStatusRequest) (*UpdateTenantStatusResponse, error)
	// ListTenants returns all tenants with optional status filter (BIAN: Control).
	ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsResponse, error)
	// ReconcileMigrations applies new migrations to existing tenant schemas.
	// When services add new migrations after tenants are created, existing tenant
	// schemas may be missing these migrations. This operation detects and applies
	// new migrations to bring tenant schemas up to date.
	ReconcileMigrations(context.Context, *ReconcileMigrationsRequest) (*ReconcileMigrationsResponse, error)
	// GetTenantProvisioningStatus retrieves detailed provisioning status for a tenant.
	// Returns per-service provisioning progress including migration versions and error details.
	GetTenantProvisioningStatus(context.Context, *GetTenantProvisioningStatusRequest) (*GetTenantProvisioningStatusResponse, error)
	mustEmbedUnimplementedTenantServiceServer()
}

// UnimplementedTenantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTenantServiceServer struct{}

func (UnimplementedTenantServiceServer) InitiateTenant(context.Context, *InitiateTenantRequest) (*InitiateTenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateTenant not implemented")
}
func (UnimplementedTenantServiceServer) RetrieveTenant(context.Context, *RetrieveTenantRequest) (*RetrieveTenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveTenant not implemented")
}
func (UnimplementedTenantServiceServer) UpdateTenantStatus(context.Context, *UpdateTenantStatusRequest) (*UpdateTenantStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTenantStatus not implemented")
}
func (UnimplementedTenantServiceServer) ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTenants not implemented")
}
func (UnimplementedTenantServiceServer) ReconcileMigrations(context.Context, *ReconcileMigrationsRequest) (*ReconcileMigrationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReconcileMigrations not implemented")
}
func (UnimplementedTenantServiceServer) GetTenantProvisioningStatus(context.Context, *GetTenantProvisioningStatusRequest) (*GetTenantProvisioningStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenantProvisioningStatus not implemented")
}
func (UnimplementedTenantServiceServer) mustEmbedUnimplementedTenantServiceServer() {}
func (UnimplementedTenantServiceServer) testEmbeddedByValue()                       {}

// UnsafeTenantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantServiceServer will
// result in compilation errors.
type UnsafeTenantServiceServer interface {
	mustEmbedUnimplementedTenantServiceServer()
}

func RegisterTenantServiceServer(s grpc.ServiceRegistrar, srv TenantServiceServer) {
	// If the following call pancis, it indicates UnimplementedTenantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TenantService_ServiceDesc, srv)
}

func _TenantService_InitiateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).InitiateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_InitiateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).InitiateTenant(ctx, req.(*InitiateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_RetrieveTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).RetrieveTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_RetrieveTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).RetrieveTenant(ctx, req.(*RetrieveTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_UpdateTenantStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).UpdateTenantStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_UpdateTenantStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).UpdateTenantStatus(ctx, req.(*UpdateTenantStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_ListTenants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).ListTenants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_ListTenants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).ListTenants(ctx, req.(*ListTenantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_ReconcileMigrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileMigrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).ReconcileMigrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_ReconcileMigrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).ReconcileMigrations(ctx, req.(*ReconcileMigrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_GetTenantProvisioningStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantProvisioningStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).GetTenantProvisioningStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_GetTenantProvisioningStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).GetTenantProvisioningStatus(ctx, req.(*GetTenantProvisioningStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TenantService_ServiceDesc is the grpc.ServiceDesc for TenantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TenantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meridian.tenant.v1.TenantService",
	HandlerType: (*TenantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateTenant",
			Handler:    _TenantService_InitiateTenant_Handler,
		},
		{
			MethodName: "RetrieveTenant",
			Handler:    _TenantService_RetrieveTenant_Handler,
		},
		{
			MethodName: "UpdateTenantStatus",
			Handler:    _TenantService_UpdateTenantStatus_Handler,
		},
		{
			MethodName: "ListTenants",
			Handler:    _TenantService_ListTenants_Handler,
		},
		{
			MethodName: "ReconcileMigrations",
			Handler:    _TenantService_ReconcileMigrations_Handler,
		},
		{
			MethodName: "GetTenantProvisioningStatus",
			Handler:    _TenantService_GetTenantProvisioningStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meridian/tenant/v1/tenant.proto",
}
