// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: meridian/party/v1/party.proto

package partyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PartyService_RegisterParty_FullMethodName           = "/meridian.party.v1.PartyService/RegisterParty"
	PartyService_ListParties_FullMethodName             = "/meridian.party.v1.PartyService/ListParties"
	PartyService_RetrieveParty_FullMethodName           = "/meridian.party.v1.PartyService/RetrieveParty"
	PartyService_UpdateParty_FullMethodName             = "/meridian.party.v1.PartyService/UpdateParty"
	PartyService_ControlParty_FullMethodName            = "/meridian.party.v1.PartyService/ControlParty"
	PartyService_UpdateReference_FullMethodName         = "/meridian.party.v1.PartyService/UpdateReference"
	PartyService_RetrieveReference_FullMethodName       = "/meridian.party.v1.PartyService/RetrieveReference"
	PartyService_RegisterAssociations_FullMethodName    = "/meridian.party.v1.PartyService/RegisterAssociations"
	PartyService_UpdateAssociations_FullMethodName      = "/meridian.party.v1.PartyService/UpdateAssociations"
	PartyService_RetrieveAssociations_FullMethodName    = "/meridian.party.v1.PartyService/RetrieveAssociations"
	PartyService_ExchangeDemographics_FullMethodName    = "/meridian.party.v1.PartyService/ExchangeDemographics"
	PartyService_UpdateDemographics_FullMethodName      = "/meridian.party.v1.PartyService/UpdateDemographics"
	PartyService_RetrieveDemographics_FullMethodName    = "/meridian.party.v1.PartyService/RetrieveDemographics"
	PartyService_UpdateBankRelations_FullMethodName     = "/meridian.party.v1.PartyService/UpdateBankRelations"
	PartyService_RetrieveBankRelations_FullMethodName   = "/meridian.party.v1.PartyService/RetrieveBankRelations"
	PartyService_ListParticipants_FullMethodName        = "/meridian.party.v1.PartyService/ListParticipants"
	PartyService_GetStructuringData_FullMethodName      = "/meridian.party.v1.PartyService/GetStructuringData"
	PartyService_AddPaymentMethod_FullMethodName        = "/meridian.party.v1.PartyService/AddPaymentMethod"
	PartyService_RemovePaymentMethod_FullMethodName     = "/meridian.party.v1.PartyService/RemovePaymentMethod"
	PartyService_SetDefaultPaymentMethod_FullMethodName = "/meridian.party.v1.PartyService/SetDefaultPaymentMethod"
	PartyService_ListPaymentMethods_FullMethodName      = "/meridian.party.v1.PartyService/ListPaymentMethods"
	PartyService_GetDefaultPaymentMethod_FullMethodName = "/meridian.party.v1.PartyService/GetDefaultPaymentMethod"
	PartyService_RegisterPartyType_FullMethodName       = "/meridian.party.v1.PartyService/RegisterPartyType"
	PartyService_GetPartyType_FullMethodName            = "/meridian.party.v1.PartyService/GetPartyType"
	PartyService_ListPartyTypes_FullMethodName          = "/meridian.party.v1.PartyService/ListPartyTypes"
	PartyService_UpdatePartyType_FullMethodName         = "/meridian.party.v1.PartyService/UpdatePartyType"
)

// PartyServiceClient is the client API for PartyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PartyService provides BIAN-compliant party reference data management.
//
// Design Notes:
//   - DELETE operations are intentionally not provided. Parties are managed
//     through status transitions (Active → Restricted → Terminated) for audit compliance.
//   - This service follows the BIAN Party Reference Data Directory pattern.
type PartyServiceClient interface {
	// RegisterParty creates a new party in the reference data directory.
	RegisterParty(ctx context.Context, in *RegisterPartyRequest, opts ...grpc.CallOption) (*RegisterPartyResponse, error)
	// ListParties returns a paginated list of parties with optional filtering.
	ListParties(ctx context.Context, in *ListPartiesRequest, opts ...grpc.CallOption) (*ListPartiesResponse, error)
	// RetrieveParty gets party details by ID.
	RetrieveParty(ctx context.Context, in *RetrievePartyRequest, opts ...grpc.CallOption) (*RetrievePartyResponse, error)
	// UpdateParty updates party details (BIAN UpCR).
	UpdateParty(ctx context.Context, in *UpdatePartyRequest, opts ...grpc.CallOption) (*UpdatePartyResponse, error)
	// ControlParty manages party lifecycle (BIAN CoCR).
	ControlParty(ctx context.Context, in *ControlPartyRequest, opts ...grpc.CallOption) (*ControlPartyResponse, error)
	// UpdateReference updates party reference data.
	UpdateReference(ctx context.Context, in *UpdateReferenceRequest, opts ...grpc.CallOption) (*UpdateReferenceResponse, error)
	// RetrieveReference gets party reference data.
	RetrieveReference(ctx context.Context, in *RetrieveReferenceRequest, opts ...grpc.CallOption) (*RetrieveReferenceResponse, error)
	// RegisterAssociations creates a party association.
	RegisterAssociations(ctx context.Context, in *RegisterAssociationsRequest, opts ...grpc.CallOption) (*RegisterAssociationsResponse, error)
	// UpdateAssociations updates a party association.
	UpdateAssociations(ctx context.Context, in *UpdateAssociationsRequest, opts ...grpc.CallOption) (*UpdateAssociationsResponse, error)
	// RetrieveAssociations gets party associations.
	RetrieveAssociations(ctx context.Context, in *RetrieveAssociationsRequest, opts ...grpc.CallOption) (*RetrieveAssociationsResponse, error)
	// ExchangeDemographics verifies party demographics data.
	ExchangeDemographics(ctx context.Context, in *ExchangeDemographicsRequest, opts ...grpc.CallOption) (*ExchangeDemographicsResponse, error)
	// UpdateDemographics updates party demographics data.
	UpdateDemographics(ctx context.Context, in *UpdateDemographicsRequest, opts ...grpc.CallOption) (*UpdateDemographicsResponse, error)
	// RetrieveDemographics gets party demographics data.
	RetrieveDemographics(ctx context.Context, in *RetrieveDemographicsRequest, opts ...grpc.CallOption) (*RetrieveDemographicsResponse, error)
	// UpdateBankRelations updates party bank relationship data.
	UpdateBankRelations(ctx context.Context, in *UpdateBankRelationsRequest, opts ...grpc.CallOption) (*UpdateBankRelationsResponse, error)
	// RetrieveBankRelations gets party bank relationship data.
	RetrieveBankRelations(ctx context.Context, in *RetrieveBankRelationsRequest, opts ...grpc.CallOption) (*RetrieveBankRelationsResponse, error)
	// ListParticipants returns all active participants for a syndicate (org party).
	ListParticipants(ctx context.Context, in *ListParticipantsRequest, opts ...grpc.CallOption) (*ListParticipantsResponse, error)
	// GetStructuringData returns the structuring metadata for a specific participant in a syndicate.
	GetStructuringData(ctx context.Context, in *GetStructuringDataRequest, opts ...grpc.CallOption) (*GetStructuringDataResponse, error)
	// AddPaymentMethod registers a tokenized payment method for a party.
	AddPaymentMethod(ctx context.Context, in *AddPaymentMethodRequest, opts ...grpc.CallOption) (*AddPaymentMethodResponse, error)
	// RemovePaymentMethod soft-deletes a payment method.
	RemovePaymentMethod(ctx context.Context, in *RemovePaymentMethodRequest, opts ...grpc.CallOption) (*RemovePaymentMethodResponse, error)
	// SetDefaultPaymentMethod sets a payment method as the party's default.
	SetDefaultPaymentMethod(ctx context.Context, in *SetDefaultPaymentMethodRequest, opts ...grpc.CallOption) (*SetDefaultPaymentMethodResponse, error)
	// ListPaymentMethods returns all active payment methods for a party.
	ListPaymentMethods(ctx context.Context, in *ListPaymentMethodsRequest, opts ...grpc.CallOption) (*ListPaymentMethodsResponse, error)
	// GetDefaultPaymentMethod returns the default payment method for a party.
	GetDefaultPaymentMethod(ctx context.Context, in *GetDefaultPaymentMethodRequest, opts ...grpc.CallOption) (*GetDefaultPaymentMethodResponse, error)
	// RegisterPartyType creates a new tenant-configurable party type definition.
	RegisterPartyType(ctx context.Context, in *RegisterPartyTypeRequest, opts ...grpc.CallOption) (*RegisterPartyTypeResponse, error)
	// GetPartyType retrieves a party type definition by ID.
	GetPartyType(ctx context.Context, in *GetPartyTypeRequest, opts ...grpc.CallOption) (*GetPartyTypeResponse, error)
	// ListPartyTypes lists all party type definitions for the tenant.
	ListPartyTypes(ctx context.Context, in *ListPartyTypesRequest, opts ...grpc.CallOption) (*ListPartyTypesResponse, error)
	// UpdatePartyType updates a party type definition.
	UpdatePartyType(ctx context.Context, in *UpdatePartyTypeRequest, opts ...grpc.CallOption) (*UpdatePartyTypeResponse, error)
}

type partyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartyServiceClient(cc grpc.ClientConnInterface) PartyServiceClient {
	return &partyServiceClient{cc}
}

func (c *partyServiceClient) RegisterParty(ctx context.Context, in *RegisterPartyRequest, opts ...grpc.CallOption) (*RegisterPartyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterPartyResponse)
	err := c.cc.Invoke(ctx, PartyService_RegisterParty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) ListParties(ctx context.Context, in *ListPartiesRequest, opts ...grpc.CallOption) (*ListPartiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPartiesResponse)
	err := c.cc.Invoke(ctx, PartyService_ListParties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) RetrieveParty(ctx context.Context, in *RetrievePartyRequest, opts ...grpc.CallOption) (*RetrievePartyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrievePartyResponse)
	err := c.cc.Invoke(ctx, PartyService_RetrieveParty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) UpdateParty(ctx context.Context, in *UpdatePartyRequest, opts ...grpc.CallOption) (*UpdatePartyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePartyResponse)
	err := c.cc.Invoke(ctx, PartyService_UpdateParty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) ControlParty(ctx context.Context, in *ControlPartyRequest, opts ...grpc.CallOption) (*ControlPartyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlPartyResponse)
	err := c.cc.Invoke(ctx, PartyService_ControlParty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) UpdateReference(ctx context.Context, in *UpdateReferenceRequest, opts ...grpc.CallOption) (*UpdateReferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateReferenceResponse)
	err := c.cc.Invoke(ctx, PartyService_UpdateReference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) RetrieveReference(ctx context.Context, in *RetrieveReferenceRequest, opts ...grpc.CallOption) (*RetrieveReferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveReferenceResponse)
	err := c.cc.Invoke(ctx, PartyService_RetrieveReference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) RegisterAssociations(ctx context.Context, in *RegisterAssociationsRequest, opts ...grpc.CallOption) (*RegisterAssociationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAssociationsResponse)
	err := c.cc.Invoke(ctx, PartyService_RegisterAssociations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) UpdateAssociations(ctx context.Context, in *UpdateAssociationsRequest, opts ...grpc.CallOption) (*UpdateAssociationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAssociationsResponse)
	err := c.cc.Invoke(ctx, PartyService_UpdateAssociations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) RetrieveAssociations(ctx context.Context, in *RetrieveAssociationsRequest, opts ...grpc.CallOption) (*RetrieveAssociationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveAssociationsResponse)
	err := c.cc.Invoke(ctx, PartyService_RetrieveAssociations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) ExchangeDemographics(ctx context.Context, in *ExchangeDemographicsRequest, opts ...grpc.CallOption) (*ExchangeDemographicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeDemographicsResponse)
	err := c.cc.Invoke(ctx, PartyService_ExchangeDemographics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) UpdateDemographics(ctx context.Context, in *UpdateDemographicsRequest, opts ...grpc.CallOption) (*UpdateDemographicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDemographicsResponse)
	err := c.cc.Invoke(ctx, PartyService_UpdateDemographics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) RetrieveDemographics(ctx context.Context, in *RetrieveDemographicsRequest, opts ...grpc.CallOption) (*RetrieveDemographicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveDemographicsResponse)
	err := c.cc.Invoke(ctx, PartyService_RetrieveDemographics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) UpdateBankRelations(ctx context.Context, in *UpdateBankRelationsRequest, opts ...grpc.CallOption) (*UpdateBankRelationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBankRelationsResponse)
	err := c.cc.Invoke(ctx, PartyService_UpdateBankRelations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) RetrieveBankRelations(ctx context.Context, in *RetrieveBankRelationsRequest, opts ...grpc.CallOption) (*RetrieveBankRelationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveBankRelationsResponse)
	err := c.cc.Invoke(ctx, PartyService_RetrieveBankRelations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) ListParticipants(ctx context.Context, in *ListParticipantsRequest, opts ...grpc.CallOption) (*ListParticipantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListParticipantsResponse)
	err := c.cc.Invoke(ctx, PartyService_ListParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) GetStructuringData(ctx context.Context, in *GetStructuringDataRequest, opts ...grpc.CallOption) (*GetStructuringDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStructuringDataResponse)
	err := c.cc.Invoke(ctx, PartyService_GetStructuringData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) AddPaymentMethod(ctx context.Context, in *AddPaymentMethodRequest, opts ...grpc.CallOption) (*AddPaymentMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPaymentMethodResponse)
	err := c.cc.Invoke(ctx, PartyService_AddPaymentMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) RemovePaymentMethod(ctx context.Context, in *RemovePaymentMethodRequest, opts ...grpc.CallOption) (*RemovePaymentMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemovePaymentMethodResponse)
	err := c.cc.Invoke(ctx, PartyService_RemovePaymentMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) SetDefaultPaymentMethod(ctx context.Context, in *SetDefaultPaymentMethodRequest, opts ...grpc.CallOption) (*SetDefaultPaymentMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDefaultPaymentMethodResponse)
	err := c.cc.Invoke(ctx, PartyService_SetDefaultPaymentMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) ListPaymentMethods(ctx context.Context, in *ListPaymentMethodsRequest, opts ...grpc.CallOption) (*ListPaymentMethodsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPaymentMethodsResponse)
	err := c.cc.Invoke(ctx, PartyService_ListPaymentMethods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) GetDefaultPaymentMethod(ctx context.Context, in *GetDefaultPaymentMethodRequest, opts ...grpc.CallOption) (*GetDefaultPaymentMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDefaultPaymentMethodResponse)
	err := c.cc.Invoke(ctx, PartyService_GetDefaultPaymentMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) RegisterPartyType(ctx context.Context, in *RegisterPartyTypeRequest, opts ...grpc.CallOption) (*RegisterPartyTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterPartyTypeResponse)
	err := c.cc.Invoke(ctx, PartyService_RegisterPartyType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) GetPartyType(ctx context.Context, in *GetPartyTypeRequest, opts ...grpc.CallOption) (*GetPartyTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPartyTypeResponse)
	err := c.cc.Invoke(ctx, PartyService_GetPartyType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) ListPartyTypes(ctx context.Context, in *ListPartyTypesRequest, opts ...grpc.CallOption) (*ListPartyTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPartyTypesResponse)
	err := c.cc.Invoke(ctx, PartyService_ListPartyTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) UpdatePartyType(ctx context.Context, in *UpdatePartyTypeRequest, opts ...grpc.CallOption) (*UpdatePartyTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePartyTypeResponse)
	err := c.cc.Invoke(ctx, PartyService_UpdatePartyType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartyServiceServer is the server API for PartyService service.
// All implementations must embed UnimplementedPartyServiceServer
// for forward compatibility.
//
// PartyService provides BIAN-compliant party reference data management.
//
// Design Notes:
//   - DELETE operations are intentionally not provided. Parties are managed
//     through status transitions (Active → Restricted → Terminated) for audit compliance.
//   - This service follows the BIAN Party Reference Data Directory pattern.
type PartyServiceServer interface {
	// RegisterParty creates a new party in the reference data directory.
	RegisterParty(context.Context, *RegisterPartyRequest) (*RegisterPartyResponse, error)
	// ListParties returns a paginated list of parties with optional filtering.
	ListParties(context.Context, *ListPartiesRequest) (*ListPartiesResponse, error)
	// RetrieveParty gets party details by ID.
	RetrieveParty(context.Context, *RetrievePartyRequest) (*RetrievePartyResponse, error)
	// UpdateParty updates party details (BIAN UpCR).
	UpdateParty(context.Context, *UpdatePartyRequest) (*UpdatePartyResponse, error)
	// ControlParty manages party lifecycle (BIAN CoCR).
	ControlParty(context.Context, *ControlPartyRequest) (*ControlPartyResponse, error)
	// UpdateReference updates party reference data.
	UpdateReference(context.Context, *UpdateReferenceRequest) (*UpdateReferenceResponse, error)
	// RetrieveReference gets party reference data.
	RetrieveReference(context.Context, *RetrieveReferenceRequest) (*RetrieveReferenceResponse, error)
	// RegisterAssociations creates a party association.
	RegisterAssociations(context.Context, *RegisterAssociationsRequest) (*RegisterAssociationsResponse, error)
	// UpdateAssociations updates a party association.
	UpdateAssociations(context.Context, *UpdateAssociationsRequest) (*UpdateAssociationsResponse, error)
	// RetrieveAssociations gets party associations.
	RetrieveAssociations(context.Context, *RetrieveAssociationsRequest) (*RetrieveAssociationsResponse, error)
	// ExchangeDemographics verifies party demographics data.
	ExchangeDemographics(context.Context, *ExchangeDemographicsRequest) (*ExchangeDemographicsResponse, error)
	// UpdateDemographics updates party demographics data.
	UpdateDemographics(context.Context, *UpdateDemographicsRequest) (*UpdateDemographicsResponse, error)
	// RetrieveDemographics gets party demographics data.
	RetrieveDemographics(context.Context, *RetrieveDemographicsRequest) (*RetrieveDemographicsResponse, error)
	// UpdateBankRelations updates party bank relationship data.
	UpdateBankRelations(context.Context, *UpdateBankRelationsRequest) (*UpdateBankRelationsResponse, error)
	// RetrieveBankRelations gets party bank relationship data.
	RetrieveBankRelations(context.Context, *RetrieveBankRelationsRequest) (*RetrieveBankRelationsResponse, error)
	// ListParticipants returns all active participants for a syndicate (org party).
	ListParticipants(context.Context, *ListParticipantsRequest) (*ListParticipantsResponse, error)
	// GetStructuringData returns the structuring metadata for a specific participant in a syndicate.
	GetStructuringData(context.Context, *GetStructuringDataRequest) (*GetStructuringDataResponse, error)
	// AddPaymentMethod registers a tokenized payment method for a party.
	AddPaymentMethod(context.Context, *AddPaymentMethodRequest) (*AddPaymentMethodResponse, error)
	// RemovePaymentMethod soft-deletes a payment method.
	RemovePaymentMethod(context.Context, *RemovePaymentMethodRequest) (*RemovePaymentMethodResponse, error)
	// SetDefaultPaymentMethod sets a payment method as the party's default.
	SetDefaultPaymentMethod(context.Context, *SetDefaultPaymentMethodRequest) (*SetDefaultPaymentMethodResponse, error)
	// ListPaymentMethods returns all active payment methods for a party.
	ListPaymentMethods(context.Context, *ListPaymentMethodsRequest) (*ListPaymentMethodsResponse, error)
	// GetDefaultPaymentMethod returns the default payment method for a party.
	GetDefaultPaymentMethod(context.Context, *GetDefaultPaymentMethodRequest) (*GetDefaultPaymentMethodResponse, error)
	// RegisterPartyType creates a new tenant-configurable party type definition.
	RegisterPartyType(context.Context, *RegisterPartyTypeRequest) (*RegisterPartyTypeResponse, error)
	// GetPartyType retrieves a party type definition by ID.
	GetPartyType(context.Context, *GetPartyTypeRequest) (*GetPartyTypeResponse, error)
	// ListPartyTypes lists all party type definitions for the tenant.
	ListPartyTypes(context.Context, *ListPartyTypesRequest) (*ListPartyTypesResponse, error)
	// UpdatePartyType updates a party type definition.
	UpdatePartyType(context.Context, *UpdatePartyTypeRequest) (*UpdatePartyTypeResponse, error)
	mustEmbedUnimplementedPartyServiceServer()
}

// UnimplementedPartyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPartyServiceServer struct{}

func (UnimplementedPartyServiceServer) RegisterParty(context.Context, *RegisterPartyRequest) (*RegisterPartyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterParty not implemented")
}
func (UnimplementedPartyServiceServer) ListParties(context.Context, *ListPartiesRequest) (*ListPartiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListParties not implemented")
}
func (UnimplementedPartyServiceServer) RetrieveParty(context.Context, *RetrievePartyRequest) (*RetrievePartyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveParty not implemented")
}
func (UnimplementedPartyServiceServer) UpdateParty(context.Context, *UpdatePartyRequest) (*UpdatePartyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParty not implemented")
}
func (UnimplementedPartyServiceServer) ControlParty(context.Context, *ControlPartyRequest) (*ControlPartyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ControlParty not implemented")
}
func (UnimplementedPartyServiceServer) UpdateReference(context.Context, *UpdateReferenceRequest) (*UpdateReferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateReference not implemented")
}
func (UnimplementedPartyServiceServer) RetrieveReference(context.Context, *RetrieveReferenceRequest) (*RetrieveReferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveReference not implemented")
}
func (UnimplementedPartyServiceServer) RegisterAssociations(context.Context, *RegisterAssociationsRequest) (*RegisterAssociationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAssociations not implemented")
}
func (UnimplementedPartyServiceServer) UpdateAssociations(context.Context, *UpdateAssociationsRequest) (*UpdateAssociationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAssociations not implemented")
}
func (UnimplementedPartyServiceServer) RetrieveAssociations(context.Context, *RetrieveAssociationsRequest) (*RetrieveAssociationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveAssociations not implemented")
}
func (UnimplementedPartyServiceServer) ExchangeDemographics(context.Context, *ExchangeDemographicsRequest) (*ExchangeDemographicsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExchangeDemographics not implemented")
}
func (UnimplementedPartyServiceServer) UpdateDemographics(context.Context, *UpdateDemographicsRequest) (*UpdateDemographicsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDemographics not implemented")
}
func (UnimplementedPartyServiceServer) RetrieveDemographics(context.Context, *RetrieveDemographicsRequest) (*RetrieveDemographicsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveDemographics not implemented")
}
func (UnimplementedPartyServiceServer) UpdateBankRelations(context.Context, *UpdateBankRelationsRequest) (*UpdateBankRelationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBankRelations not implemented")
}
func (UnimplementedPartyServiceServer) RetrieveBankRelations(context.Context, *RetrieveBankRelationsRequest) (*RetrieveBankRelationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveBankRelations not implemented")
}
func (UnimplementedPartyServiceServer) ListParticipants(context.Context, *ListParticipantsRequest) (*ListParticipantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListParticipants not implemented")
}
func (UnimplementedPartyServiceServer) GetStructuringData(context.Context, *GetStructuringDataRequest) (*GetStructuringDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStructuringData not implemented")
}
func (UnimplementedPartyServiceServer) AddPaymentMethod(context.Context, *AddPaymentMethodRequest) (*AddPaymentMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPaymentMethod not implemented")
}
func (UnimplementedPartyServiceServer) RemovePaymentMethod(context.Context, *RemovePaymentMethodRequest) (*RemovePaymentMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePaymentMethod not implemented")
}
func (UnimplementedPartyServiceServer) SetDefaultPaymentMethod(context.Context, *SetDefaultPaymentMethodRequest) (*SetDefaultPaymentMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDefaultPaymentMethod not implemented")
}
func (UnimplementedPartyServiceServer) ListPaymentMethods(context.Context, *ListPaymentMethodsRequest) (*ListPaymentMethodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPaymentMethods not implemented")
}
func (UnimplementedPartyServiceServer) GetDefaultPaymentMethod(context.Context, *GetDefaultPaymentMethodRequest) (*GetDefaultPaymentMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDefaultPaymentMethod not implemented")
}
func (UnimplementedPartyServiceServer) RegisterPartyType(context.Context, *RegisterPartyTypeRequest) (*RegisterPartyTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterPartyType not implemented")
}
func (UnimplementedPartyServiceServer) GetPartyType(context.Context, *GetPartyTypeRequest) (*GetPartyTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPartyType not implemented")
}
func (UnimplementedPartyServiceServer) ListPartyTypes(context.Context, *ListPartyTypesRequest) (*ListPartyTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPartyTypes not implemented")
}
func (UnimplementedPartyServiceServer) UpdatePartyType(context.Context, *UpdatePartyTypeRequest) (*UpdatePartyTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePartyType not implemented")
}
func (UnimplementedPartyServiceServer) mustEmbedUnimplementedPartyServiceServer() {}
func (UnimplementedPartyServiceServer) testEmbeddedByValue()                      {}

// UnsafePartyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartyServiceServer will
// result in compilation errors.
type UnsafePartyServiceServer interface {
	mustEmbedUnimplementedPartyServiceServer()
}

func RegisterPartyServiceServer(s grpc.ServiceRegistrar, srv PartyServiceServer) {
	// If the following call pancis, it indicates UnimplementedPartyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PartyService_ServiceDesc, srv)
}

func _PartyService_RegisterParty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPartyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).RegisterParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_RegisterParty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).RegisterParty(ctx, req.(*RegisterPartyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_ListParties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPartiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).ListParties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_ListParties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).ListParties(ctx, req.(*ListPartiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_RetrieveParty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrievePartyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).RetrieveParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_RetrieveParty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).RetrieveParty(ctx, req.(*RetrievePartyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_UpdateParty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePartyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).UpdateParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_UpdateParty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).UpdateParty(ctx, req.(*UpdatePartyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_ControlParty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlPartyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).ControlParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_ControlParty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).ControlParty(ctx, req.(*ControlPartyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_UpdateReference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).UpdateReference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_UpdateReference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).UpdateReference(ctx, req.(*UpdateReferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_RetrieveReference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveReferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).RetrieveReference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_RetrieveReference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).RetrieveReference(ctx, req.(*RetrieveReferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_RegisterAssociations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAssociationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).RegisterAssociations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_RegisterAssociations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).RegisterAssociations(ctx, req.(*RegisterAssociationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_UpdateAssociations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssociationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).UpdateAssociations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_UpdateAssociations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).UpdateAssociations(ctx, req.(*UpdateAssociationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_RetrieveAssociations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveAssociationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).RetrieveAssociations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_RetrieveAssociations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).RetrieveAssociations(ctx, req.(*RetrieveAssociationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_ExchangeDemographics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeDemographicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).ExchangeDemographics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_ExchangeDemographics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).ExchangeDemographics(ctx, req.(*ExchangeDemographicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_UpdateDemographics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDemographicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).UpdateDemographics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_UpdateDemographics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).UpdateDemographics(ctx, req.(*UpdateDemographicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_RetrieveDemographics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveDemographicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).RetrieveDemographics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_RetrieveDemographics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).RetrieveDemographics(ctx, req.(*RetrieveDemographicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_UpdateBankRelations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBankRelationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).UpdateBankRelations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_UpdateBankRelations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).UpdateBankRelations(ctx, req.(*UpdateBankRelationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_RetrieveBankRelations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveBankRelationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).RetrieveBankRelations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_RetrieveBankRelations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).RetrieveBankRelations(ctx, req.(*RetrieveBankRelationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_ListParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).ListParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_ListParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).ListParticipants(ctx, req.(*ListParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_GetStructuringData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStructuringDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).GetStructuringData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_GetStructuringData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).GetStructuringData(ctx, req.(*GetStructuringDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_AddPaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).AddPaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_AddPaymentMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).AddPaymentMethod(ctx, req.(*AddPaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_RemovePaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).RemovePaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_RemovePaymentMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).RemovePaymentMethod(ctx, req.(*RemovePaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_SetDefaultPaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultPaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).SetDefaultPaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_SetDefaultPaymentMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).SetDefaultPaymentMethod(ctx, req.(*SetDefaultPaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_ListPaymentMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPaymentMethodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).ListPaymentMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_ListPaymentMethods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).ListPaymentMethods(ctx, req.(*ListPaymentMethodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_GetDefaultPaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefaultPaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).GetDefaultPaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_GetDefaultPaymentMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).GetDefaultPaymentMethod(ctx, req.(*GetDefaultPaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_RegisterPartyType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPartyTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).RegisterPartyType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_RegisterPartyType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).RegisterPartyType(ctx, req.(*RegisterPartyTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_GetPartyType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartyTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).GetPartyType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_GetPartyType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).GetPartyType(ctx, req.(*GetPartyTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_ListPartyTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPartyTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).ListPartyTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_ListPartyTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).ListPartyTypes(ctx, req.(*ListPartyTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_UpdatePartyType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePartyTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).UpdatePartyType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_UpdatePartyType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).UpdatePartyType(ctx, req.(*UpdatePartyTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PartyService_ServiceDesc is the grpc.ServiceDesc for PartyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meridian.party.v1.PartyService",
	HandlerType: (*PartyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterParty",
			Handler:    _PartyService_RegisterParty_Handler,
		},
		{
			MethodName: "ListParties",
			Handler:    _PartyService_ListParties_Handler,
		},
		{
			MethodName: "RetrieveParty",
			Handler:    _PartyService_RetrieveParty_Handler,
		},
		{
			MethodName: "UpdateParty",
			Handler:    _PartyService_UpdateParty_Handler,
		},
		{
			MethodName: "ControlParty",
			Handler:    _PartyService_ControlParty_Handler,
		},
		{
			MethodName: "UpdateReference",
			Handler:    _PartyService_UpdateReference_Handler,
		},
		{
			MethodName: "RetrieveReference",
			Handler:    _PartyService_RetrieveReference_Handler,
		},
		{
			MethodName: "RegisterAssociations",
			Handler:    _PartyService_RegisterAssociations_Handler,
		},
		{
			MethodName: "UpdateAssociations",
			Handler:    _PartyService_UpdateAssociations_Handler,
		},
		{
			MethodName: "RetrieveAssociations",
			Handler:    _PartyService_RetrieveAssociations_Handler,
		},
		{
			MethodName: "ExchangeDemographics",
			Handler:    _PartyService_ExchangeDemographics_Handler,
		},
		{
			MethodName: "UpdateDemographics",
			Handler:    _PartyService_UpdateDemographics_Handler,
		},
		{
			MethodName: "RetrieveDemographics",
			Handler:    _PartyService_RetrieveDemographics_Handler,
		},
		{
			MethodName: "UpdateBankRelations",
			Handler:    _PartyService_UpdateBankRelations_Handler,
		},
		{
			MethodName: "RetrieveBankRelations",
			Handler:    _PartyService_RetrieveBankRelations_Handler,
		},
		{
			MethodName: "ListParticipants",
			Handler:    _PartyService_ListParticipants_Handler,
		},
		{
			MethodName: "GetStructuringData",
			Handler:    _PartyService_GetStructuringData_Handler,
		},
		{
			MethodName: "AddPaymentMethod",
			Handler:    _PartyService_AddPaymentMethod_Handler,
		},
		{
			MethodName: "RemovePaymentMethod",
			Handler:    _PartyService_RemovePaymentMethod_Handler,
		},
		{
			MethodName: "SetDefaultPaymentMethod",
			Handler:    _PartyService_SetDefaultPaymentMethod_Handler,
		},
		{
			MethodName: "ListPaymentMethods",
			Handler:    _PartyService_ListPaymentMethods_Handler,
		},
		{
			MethodName: "GetDefaultPaymentMethod",
			Handler:    _PartyService_GetDefaultPaymentMethod_Handler,
		},
		{
			MethodName: "RegisterPartyType",
			Handler:    _PartyService_RegisterPartyType_Handler,
		},
		{
			MethodName: "GetPartyType",
			Handler:    _PartyService_GetPartyType_Handler,
		},
		{
			MethodName: "ListPartyTypes",
			Handler:    _PartyService_ListPartyTypes_Handler,
		},
		{
			MethodName: "UpdatePartyType",
			Handler:    _PartyService_UpdatePartyType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meridian/party/v1/party.proto",
}
