apiVersion: v1
kind: Service
metadata:
  name: current-account
  labels:
    app: current-account
    component: microservice
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 50051
    targetPort: grpc
    protocol: TCP
  selector:
    app: current-account
