package main

import _ "embed"

//go:embed descriptor.binpb
var protoDescriptors []byte

// GetProtoDescriptors returns the compiled FileDescriptorSet for all Meridian
// proto files. The descriptor is generated by `make proto-descriptors` (which
// runs `buf build api/proto -o cmd/meridian/descriptor.binpb`) and embedded at
// compile time. It is consumed by the Vanguard HTTP/JSON transcoder to enable
// REST-to-gRPC transcoding without a running gRPC reflection server.
func GetProtoDescriptors() []byte {
	return protoDescriptors
}
