package service_test

import (
	"testing"

	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Contract tests validate assumptions about inter-service communication.
// These tests catch integration issues that unit tests with mocks miss.

// TestTransactionIDFormat validates that transaction IDs generated by
// current-account are valid UUIDs as required by position-keeping service.
//
// This test was added after discovering that current-account was generating
// "TXN-12345678" format IDs while position-keeping expected valid UUIDs.
func TestTransactionIDFormat(t *testing.T) {
	// Simulate how current-account generates transaction IDs
	transactionID := uuid.New().String()

	// Verify it's a valid UUID (as position-keeping expects)
	parsed, err := uuid.Parse(transactionID)
	require.NoError(t, err, "Transaction ID must be a valid UUID for position-keeping service")
	assert.NotEqual(t, uuid.Nil, parsed, "Transaction ID must not be nil UUID")

	// Verify format (should be 36 chars with dashes)
	assert.Len(t, transactionID, 36, "UUID string should be 36 characters")
}

// TestTransactionIDNotTruncated ensures we don't accidentally truncate UUIDs.
// This catches the original bug where we used uuid.New().String()[:8].
func TestTransactionIDNotTruncated(t *testing.T) {
	fullUUID := uuid.New().String()

	// The bug was: transactionID := fmt.Sprintf("TXN-%s", uuid.New().String()[:8])
	// which produced "TXN-12345678" (12 chars) instead of a valid UUID

	// Verify full UUID is parseable
	_, err := uuid.Parse(fullUUID)
	require.NoError(t, err, "Full UUID must be parseable")

	// Verify truncated UUID is NOT parseable (this is what we want to prevent)
	truncated := fullUUID[:8]
	_, err = uuid.Parse(truncated)
	assert.Error(t, err, "Truncated UUID should NOT be parseable - this catches the bug")
}

// TestAccountIDVsAccountIdentification documents the difference between
// account_id and account_identification to prevent lookup bugs.
//
// - account_id: Internal short ID like "ACC-12345678" (used for lookups)
// - account_identification: IBAN-style identifier like "GB29NWBK60161331926819"
func TestAccountIDVsAccountIdentification(t *testing.T) {
	// Example values showing the difference
	accountID := "ACC-12345678"
	accountIdentification := "GB29NWBK60161331926819"

	// They are different
	assert.NotEqual(t, accountID, accountIdentification,
		"account_id and account_identification are different fields")

	// Account ID format
	assert.True(t, len(accountID) == 12 && accountID[:4] == "ACC-",
		"account_id should be in format ACC-XXXXXXXX")

	// Account identification is longer (IBAN format)
	assert.True(t, len(accountIdentification) > 12,
		"account_identification (IBAN) is longer than account_id")
}
