// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: meridian/events/v1/deposit_event.proto

package eventsv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	commonv1 "github.com/meridianhub/meridian/api/proto/meridian/common/v1"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = commonv1.Currency(0)
)

// Validate checks the field values on DepositEvent with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DepositEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DepositEvent with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DepositEventMultiError, or
// nil if none found.
func (m *DepositEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *DepositEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AccountId

	// no validation rules for AmountCents

	// no validation rules for Currency

	// no validation rules for CorrelationId

	if all {
		switch v := interface{}(m.GetValueDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DepositEventValidationError{
					field:  "ValueDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DepositEventValidationError{
					field:  "ValueDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetValueDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DepositEventValidationError{
				field:  "ValueDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetTimestamp()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DepositEventValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DepositEventValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTimestamp()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DepositEventValidationError{
				field:  "Timestamp",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DepositEventMultiError(errors)
	}

	return nil
}

// DepositEventMultiError is an error wrapping multiple validation errors
// returned by DepositEvent.ValidateAll() if the designated constraints aren't met.
type DepositEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DepositEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DepositEventMultiError) AllErrors() []error { return m }

// DepositEventValidationError is the validation error returned by
// DepositEvent.Validate if the designated constraints aren't met.
type DepositEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DepositEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DepositEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DepositEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DepositEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DepositEventValidationError) ErrorName() string { return "DepositEventValidationError" }

// Error satisfies the builtin error interface
func (e DepositEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDepositEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DepositEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DepositEventValidationError{}
