// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: meridian/saga/v1/saga_admin.proto

package sagav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SagaAdminService_GetCausationTree_FullMethodName = "/meridian.saga.v1.SagaAdminService/GetCausationTree"
)

// SagaAdminServiceClient is the client API for SagaAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SagaAdminService provides administrative operations for saga debugging and visualization.
// These endpoints are intended for support teams to debug complex nested workflow failures.
type SagaAdminServiceClient interface {
	// GetCausationTree returns the full parent->child saga hierarchy for debugging.
	// The tree includes all descendant sagas spawned from the root saga,
	// along with their step execution details and failure information.
	//
	// Per FR-32: Enables Ken's support team to debug complex nested saga failures
	// (e.g., energy settlement with 1 parent + 3 child sagas across pod restarts).
	GetCausationTree(ctx context.Context, in *GetCausationTreeRequest, opts ...grpc.CallOption) (*GetCausationTreeResponse, error)
}

type sagaAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSagaAdminServiceClient(cc grpc.ClientConnInterface) SagaAdminServiceClient {
	return &sagaAdminServiceClient{cc}
}

func (c *sagaAdminServiceClient) GetCausationTree(ctx context.Context, in *GetCausationTreeRequest, opts ...grpc.CallOption) (*GetCausationTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCausationTreeResponse)
	err := c.cc.Invoke(ctx, SagaAdminService_GetCausationTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SagaAdminServiceServer is the server API for SagaAdminService service.
// All implementations must embed UnimplementedSagaAdminServiceServer
// for forward compatibility.
//
// SagaAdminService provides administrative operations for saga debugging and visualization.
// These endpoints are intended for support teams to debug complex nested workflow failures.
type SagaAdminServiceServer interface {
	// GetCausationTree returns the full parent->child saga hierarchy for debugging.
	// The tree includes all descendant sagas spawned from the root saga,
	// along with their step execution details and failure information.
	//
	// Per FR-32: Enables Ken's support team to debug complex nested saga failures
	// (e.g., energy settlement with 1 parent + 3 child sagas across pod restarts).
	GetCausationTree(context.Context, *GetCausationTreeRequest) (*GetCausationTreeResponse, error)
	mustEmbedUnimplementedSagaAdminServiceServer()
}

// UnimplementedSagaAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSagaAdminServiceServer struct{}

func (UnimplementedSagaAdminServiceServer) GetCausationTree(context.Context, *GetCausationTreeRequest) (*GetCausationTreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCausationTree not implemented")
}
func (UnimplementedSagaAdminServiceServer) mustEmbedUnimplementedSagaAdminServiceServer() {}
func (UnimplementedSagaAdminServiceServer) testEmbeddedByValue()                          {}

// UnsafeSagaAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SagaAdminServiceServer will
// result in compilation errors.
type UnsafeSagaAdminServiceServer interface {
	mustEmbedUnimplementedSagaAdminServiceServer()
}

func RegisterSagaAdminServiceServer(s grpc.ServiceRegistrar, srv SagaAdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedSagaAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SagaAdminService_ServiceDesc, srv)
}

func _SagaAdminService_GetCausationTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCausationTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaAdminServiceServer).GetCausationTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaAdminService_GetCausationTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaAdminServiceServer).GetCausationTree(ctx, req.(*GetCausationTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SagaAdminService_ServiceDesc is the grpc.ServiceDesc for SagaAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SagaAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meridian.saga.v1.SagaAdminService",
	HandlerType: (*SagaAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCausationTree",
			Handler:    _SagaAdminService_GetCausationTree_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meridian/saga/v1/saga_admin.proto",
}
